//! Mobile primitive emit: `@back_button`, `@deep_link`, `@push` → `mobile.ts`.
//!
//! Emits **target-agnostic** JavaScript that calls `@vox/runtime` methods. The Vox source
//! is identical regardless of platform; each target's implementation of the
//! [`@vox/runtime-types::VoxRuntime`](../../../../clients/runtime-types/src/index.ts)
//! contract fulfills the calls:
//!
//! - **Desktop (Tauri 2):** `@vox/runtime` wraps `@tauri-apps/api/event` listeners and
//!   `@tauri-apps/api/core` invoke calls.
//! - **Mobile (React Native + Expo):** `@vox/runtime-rn` wraps `BackHandler`,
//!   `expo-linking`, `expo-notifications`, and the uniffi-bridged Rust runtime.
//!
//! **Capability SSOT:** Android/iOS permission hints for broader `@uses(...)` capabilities are defined in
//! `contracts/capability/runtime-capabilities.v1.yaml` and projected to JSON as
//! `runtime-capabilities.projection.json` next to Tauri packaging hints when **`vox compile`** runs
//! `vox_tauri_codegen::emit_tauri_packaging_hints` with the repository contracts root discovered from the manifest path.

use vox_compiler::shell_projection::ShellProjectionModule;

/// Resolve the runtime npm package name to import from based on the build target string.
///
/// - `Some("rn")` → `@vox/runtime-rn` (React Native + Expo)
/// - `Some("web")` / `None` / anything else → `@vox/runtime` (Tauri desktop)
///
/// Keeping the resolution here makes `emit_mobile_setup` itself fully target-agnostic;
/// it only decides which adapter package to import, never how the API behaves.
fn runtime_package_for_target(target: Option<&str>) -> &'static str {
    match target {
        Some("rn") | Some("react-native") | Some("expo") => "@vox/runtime-rn",
        _ => "@vox/runtime",
    }
}

/// Emit a `mobile.ts` file containing mobile setup helpers for any mobile
/// primitives declared in the module. Returns `None` when no mobile
/// primitives are present so the caller can skip creating the file.
pub fn emit_mobile_setup(shell: &ShellProjectionModule) -> Option<String> {
    emit_mobile_setup_for_target(shell, None)
}

/// Target-aware variant of [`emit_mobile_setup`]. The `target` string drives only the
/// `import { voxRuntime } from "<package>"` line — every emitted method call is
/// shaped against the [`@vox/runtime-types::VoxRuntime`] contract.
pub fn emit_mobile_setup_for_target(
    shell: &ShellProjectionModule,
    target: Option<&str>,
) -> Option<String> {
    let has_back = shell.back_button.is_some();
    let has_deep = shell.deep_link.is_some();
    let has_push = shell.push.is_some();

    if !has_back && !has_deep && !has_push {
        return None;
    }

    let runtime_pkg = runtime_package_for_target(target);

    let mut imports: Vec<String> = vec!["import * as endpoints from './vox-client';".to_string()];
    imports.push(format!(
        "import {{ voxRuntime }} from '{runtime_pkg}';"
    ));

    let header = concat!(
        "// AUTO-GENERATED by Vox mobile_emit. Target-agnostic: every call goes through\n",
        "// the `@vox/runtime` adapter contract so the same source runs on desktop (Tauri)\n",
        "// and mobile (React Native + Expo) without per-platform branches.\n",
        "//\n",
        "// Capability-driven Android/iOS manifest hints share SSOT:\n",
        "// contracts/capability/runtime-capabilities.v1.yaml → runtime-capabilities.projection.json\n",
        "// (emitted beside Tauri packaging hints on `vox compile` when contracts root is found).\n",
        "//\n",
    );
    let mut parts: Vec<String> = vec![format!("{header}{}", imports.join("\n"))];

    if let Some(back) = &shell.back_button {
        let on_press = &back.on_press;
        if !on_press.is_empty() {
            // The fallback is part of the runtime contract: when the handler returns
            // false, `voxRuntime.onBackButton` falls back to the platform default
            // (exit on Tauri, system back on Android). A user-supplied fallback is
            // invoked BEFORE returning false so it always runs regardless of target.
            let fallback_call = back
                .fallback
                .as_ref()
                .map(|f| format!("await endpoints.{f}(); return true;"))
                .unwrap_or_else(|| "return false;".into());
            parts.push(format!(
                "let __backHandlerUnsubscribe: (() => void) | undefined;
export function installBackButtonHandler() {{
  if (__backHandlerUnsubscribe) return;
  __backHandlerUnsubscribe = voxRuntime.onBackButton(async () => {{
    const handled = await endpoints.{on_press}();
    if (handled) return true;
    {fallback_call}
  }});
}}
export function uninstallBackButtonHandler() {{
  __backHandlerUnsubscribe?.();
  __backHandlerUnsubscribe = undefined;
}}"
            ));
        }
    }

    if let Some(dl) = &shell.deep_link {
        let on_link = &dl.on_link;
        parts.push(format!(
            "import {{ useEffect }} from 'react';

export function useDeepLinkRouting(navigate: (opts: {{ to: string }}) => void) {{
  useEffect(() => {{
    const unsubscribe = voxRuntime.onDeepLink(async (url) => {{
      const target = await endpoints.{on_link}(url);
      if (target) {{
        navigate({{ to: target }});
        return target;
      }}
      return null;
    }});
    return () => {{ unsubscribe(); }};
  }}, [navigate]);
}}"
        ));
    }

    if let Some(push) = &shell.push {
        let on_reg = push.on_register.as_deref().unwrap_or("");
        let on_notif = push.on_notification.as_deref().unwrap_or("");
        let on_action = push.on_action.as_deref().unwrap_or("");

        // Build the handlers object literal, including only the fields the source
        // declared. An undeclared callback is simply omitted; the adapter's
        // `installPushNotifications` accepts a partial `PushHandlers`.
        let mut handler_entries: Vec<String> = Vec::new();
        if !on_reg.is_empty() {
            handler_entries.push(format!(
                "    onRegister: async (token) => {{ await endpoints.{on_reg}(token); }}"
            ));
        }
        if !on_notif.is_empty() {
            handler_entries.push(format!(
                "    onNotification: async (payload) => {{ await endpoints.{on_notif}(payload); }}"
            ));
        }
        if !on_action.is_empty() {
            handler_entries.push(format!(
                "    onAction: async (payload) => {{ await endpoints.{on_action}(payload); }}"
            ));
        }
        let handlers_obj = if handler_entries.is_empty() {
            "  {}".to_string()
        } else {
            format!("  {{\n{}\n  }}", handler_entries.join(",\n"))
        };

        parts.push(format!(
            "export async function installPushNotifications() {{
  await voxRuntime.installPushNotifications(\n{handlers_obj}\n  );
}}"
        ));
    }

    Some(parts.join("\n\n"))
}
