//! Web app bootstrap emission (the web analog of RN's `App.tsx` / Expo Router).
//!
//! The web target historically stopped at component + `routes.manifest` artifacts
//! and left the runnable bootstrap (mount + router) to a hand-written `main.tsx`.
//! This module emits `vox-app.tsx` — a dependency-free router that generalizes the
//! hand-written client router — so the `.vox` is the single source of truth.
//!
//! Stage 1 of [`docs/src/architecture/web-bootstrap-emission-migration-2026.md`].
//! Deliberately NO external router dependency (matches the app's hand-rolled
//! minimal router: "the flat route shape doesn't justify a 30 KB router"). When
//! a route manifest is present we emit the history-API router over `voxRoutes`;
//! otherwise we emit a flat single-component mount (the web analog of RN's flat
//! `App.tsx`).

/// Stable output filename for the emitted web app root.
pub const VOX_APP_FILENAME: &str = "vox-app.tsx";

/// Emit `vox-app.tsx`. When `has_route_manifest` is true the app renders the
/// dependency-free history-API router over the emitted `./routes.manifest`;
/// otherwise it flat-mounts `root_component` (which must be an emitted component).
pub fn emit_web_app(has_route_manifest: bool, root_component: Option<&str>) -> String {
    if has_route_manifest {
        emit_router_app()
    } else if let Some(root) = root_component {
        emit_flat_app(root)
    } else {
        // No routes and no components — nothing to mount. Emit a harmless stub so
        // `entry.tsx` always has a `<VoxApp/>` to import.
        emit_empty_app()
    }
}

/// History-API router (no external dep). Generalizes the hand-written client
/// router: exact-path match with index fallback, intra-app `<a>` interception
/// (push history instead of full navigation), and a 404 for unknown paths.
fn emit_router_app() -> String {
    r##"// AUTO-GENERATED by Vox — web app root (dependency-free history-API router).
// Do not edit; regenerate with `vox build`. Renders the emitted routes manifest.
import React, { useEffect, useState } from "react";
import { voxRoutes, type VoxRoute } from "./routes.manifest";

function findRoute(path: string): VoxRoute | undefined {
  const exact = voxRoutes.find((r) => r.path === path);
  if (exact) return exact;
  return voxRoutes.find((r) => r.index);
}

export function VoxApp(): React.ReactElement {
  const [path, setPath] = useState<string>(
    typeof window !== "undefined" ? window.location.pathname : "/",
  );

  useEffect(() => {
    const onPop = () => setPath(window.location.pathname);
    window.addEventListener("popstate", onPop);

    const onClick = (e: MouseEvent) => {
      // Only intercept plain left-clicks on intra-app links.
      if (e.button !== 0 || e.metaKey || e.ctrlKey || e.shiftKey || e.altKey) return;
      const a = (e.target as HTMLElement).closest?.("a");
      if (!a) return;
      const href = a.getAttribute("href");
      if (!href || href.startsWith("http") || href.startsWith("//") || href.startsWith("#")) return;
      e.preventDefault();
      window.history.pushState(null, "", href);
      setPath(href);
    };
    document.addEventListener("click", onClick);

    return () => {
      window.removeEventListener("popstate", onPop);
      document.removeEventListener("click", onClick);
    };
  }, []);

  const route = findRoute(path);
  if (!route) {
    return (
      <div className="mh-root">
        <h1>404</h1>
        <p>
          No route for <code>{path}</code>.
        </p>
        <a href="/">Go home</a>
      </div>
    );
  }
  const Component = route.component;
  return <Component />;
}
"##
    .to_string()
}

/// Flat single-component mount — the web analog of RN's route-less `App.tsx`.
fn emit_flat_app(root_component: &str) -> String {
    format!(
        "// AUTO-GENERATED by Vox — web app root (flat mount; no routes declared).\n\
         // Do not edit; regenerate with `vox build`.\n\
         import React from \"react\";\n\
         import {{ {root} }} from \"./{root}\";\n\
         \n\
         export function VoxApp(): React.ReactElement {{\n\
         \x20 return <{root} />;\n\
         }}\n",
        root = root_component
    )
}

/// No routes and no components: a placeholder so `entry.tsx` still resolves.
fn emit_empty_app() -> String {
    "// AUTO-GENERATED by Vox — web app root (no components emitted).\n\
     import React from \"react\";\n\
     \n\
     export function VoxApp(): React.ReactElement {\n\
     \x20 return <div>No Vox components to render.</div>;\n\
     }\n"
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn router_app_imports_manifest_and_exports_voxapp() {
        let out = emit_web_app(true, None);
        assert!(out.contains("import { voxRoutes, type VoxRoute } from \"./routes.manifest\""));
        assert!(out.contains("export function VoxApp()"));
        assert!(out.contains("window.history.pushState"));
        // Dependency-free: must NOT pull in an external router.
        assert!(!out.contains("react-router"));
        assert!(!out.contains("@tanstack/router"));
    }

    #[test]
    fn flat_app_mounts_root_component() {
        let out = emit_web_app(false, Some("Home"));
        assert!(out.contains("import { Home } from \"./Home\""));
        assert!(out.contains("return <Home />"));
        assert!(!out.contains("routes.manifest"));
    }

    #[test]
    fn empty_app_is_self_contained() {
        let out = emit_web_app(false, None);
        assert!(out.contains("export function VoxApp()"));
        assert!(!out.contains("./routes.manifest"));
    }
}
