//! Web app bootstrap emission (the web analog of RN's `App.tsx` / Expo Router).
//!
//! The web target historically stopped at component + `routes.manifest` artifacts
//! and left the runnable bootstrap (mount + router) to a hand-written `main.tsx`.
//! This module emits `vox-app.tsx` — a dependency-free router that generalizes the
//! hand-written client router — so the `.vox` is the single source of truth.
//!
//! Stage 1 of [`docs/src/architecture/web-bootstrap-emission-migration-2026.md`].
//! Deliberately NO external router dependency (matches the app's hand-rolled
//! minimal router: "the flat route shape doesn't justify a 30 KB router"). When
//! a route manifest is present we emit the history-API router over `voxRoutes`;
//! otherwise we emit a flat single-component mount (the web analog of RN's flat
//! `App.tsx`).

/// Stable output filename for the emitted web app root.
pub const VOX_APP_FILENAME: &str = "vox-app.tsx";

/// Stable output filename for the emitted browser runtime-global install.
pub const RUNTIME_INSTALL_FILENAME: &str = "runtime-install.ts";

/// Stable output filename for the emitted web entry point.
pub const ENTRY_FILENAME: &str = "entry.tsx";

/// Stable output filename for the default web app hooks.
pub const APP_HOOKS_FILENAME: &str = "app-hooks.tsx";

/// Stable output filename for the generic error boundary.
pub const ERROR_BOUNDARY_FILENAME: &str = "vox-error-boundary.tsx";

/// Stable output filename for the generic service-worker register helper.
pub const SW_REGISTER_FILENAME: &str = "vox-sw-register.ts";

/// Emit a generic React error boundary — catches render errors anywhere below,
/// logs them, and shows a minimal recoverable fallback. The default app-hooks
/// wraps `<VoxApp/>` in it, so every Vox web app gets crash isolation for free.
pub fn emit_error_boundary() -> String {
    r##"// AUTO-GENERATED by Vox — generic React error boundary. Do not edit.
import React from "react";

interface Props {
  children?: React.ReactNode;
}
interface State {
  hasError: boolean;
}

export class ErrorBoundary extends React.Component<Props, State> {
  // The members this component uses, re-declared so it type-checks under
  // minimal React typings too; the real React.Component provides them at runtime.
  declare props: Props;
  declare setState: (partial: Partial<State>) => void;
  state: State = { hasError: false };

  static getDerivedStateFromError(): State {
    return { hasError: true };
  }

  componentDidCatch(error: Error, info: { componentStack?: string }): void {
    console.error("[vox] uncaught render error:", error, info?.componentStack);
  }

  render(): React.ReactNode {
    if (this.state.hasError) {
      return (
        <div role="alert" style={{ padding: "2rem", textAlign: "center" }}>
          <h2>Something went wrong.</h2>
          <p>The app hit an unexpected error. Reload to continue.</p>
          <button
            onClick={() => {
              this.setState({ hasError: false });
              window.location.reload();
            }}
          >
            Reload
          </button>
        </div>
      );
    }
    return this.props.children;
  }
}
"##
    .to_string()
}

/// Emit a generic service-worker registration helper (PWA support). No-ops when
/// the runtime lacks `serviceWorker`; logs (not throws) on failure so apps that
/// don't ship a `/sw.js` degrade gracefully. The default app-hooks calls it.
pub fn emit_sw_register() -> String {
    r##"// AUTO-GENERATED by Vox — service-worker registration (PWA). Do not edit.
export async function registerServiceWorker(swPath: string = "/sw.js"): Promise<void> {
  if (typeof navigator !== "undefined" && "serviceWorker" in navigator) {
    try {
      await navigator.serviceWorker.register(swPath);
    } catch (err) {
      console.error("[vox] service worker registration failed:", err);
    }
  }
}
"##
    .to_string()
}

/// Emit the DEFAULT (no-op) `app-hooks.tsx` next to `entry.tsx`. Every build gets
/// it, so the emitted `entry.tsx`'s `./app-hooks` import always resolves (e.g.
/// fixtures with no app glue). An app that needs a React error boundary or PWA
/// service worker overrides this file in a post-build step (the mental-tracker's
/// `postbuild-fixup.mjs` re-exports its real `src/app-hooks.tsx`).
pub fn emit_app_hooks_default() -> String {
    r##"// AUTO-GENERATED by Vox — default web app hooks. Wires the generic error
// boundary + PWA service-worker registration so a fresh Vox web app needs no
// hand-written glue. Apps wanting custom behavior override this file in a
// post-build step. entry.tsx imports `{ wrapApp, onBoot }` from here.
import React from "react";
import { ErrorBoundary } from "./vox-error-boundary";
import { registerServiceWorker } from "./vox-sw-register";

export function wrapApp(app: React.ReactElement): React.ReactElement {
  return <ErrorBoundary>{app}</ErrorBoundary>;
}

export function onBoot(): void {
  void registerServiceWorker();
}
"##
    .to_string()
}

/// Emit `entry.tsx` — the web mount point (the web analog of RN's `App.tsx`
/// bootstrap). Installs runtime globals (side-effect import), then mounts
/// `<VoxApp/>` to `#root`. App-specific glue (error boundary, service worker)
/// is delegated to an **app-owned** `src/app-hooks.ts` exporting
/// `wrapApp(app)` + `onBoot()`, so the emitted entry stays generic while the
/// app keeps ownership of React-error-boundary / PWA concerns.
///
/// Stage 3 of the web-bootstrap migration. Assumes the emit dir (`dist/`) and
/// the app `src/` are siblings — the same convention the hand-written
/// `main.tsx` already uses (`import … from "../dist/routes.manifest"`).
pub fn emit_web_entry() -> String {
    r##"// AUTO-GENERATED by Vox — web entry point. Do not edit; regenerate with `vox build`.
// Mounts <VoxApp/> to #root. App-specific glue lives in the app-owned
// `src/app-hooks.ts` ({ wrapApp, onBoot }).
import "./runtime-install";
import React from "react";
import ReactDOM from "react-dom/client";
import { VoxApp } from "./vox-app";
import { wrapApp, onBoot } from "./app-hooks";

onBoot();

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>{wrapApp(<VoxApp />)}</React.StrictMode>,
);
"##
    .to_string()
}

/// Emit `runtime-install.ts` — generic browser shims installed on `globalThis`
/// so emitted web code's bare `Speech`/`std`/`mobile`/`str`/`len` references
/// resolve at runtime (Web Speech API, `crypto.subtle`, `Date.now`, etc.).
/// Side-effect module: `entry.tsx` imports it for its globals.
///
/// Stage 2 of the web-bootstrap migration. Generalizes the hand-written
/// `runtime.ts`; preserves the `__VOX_TEST_TRANSCRIPT__` synchronous test hook
/// the e2e suite injects. Generic to any Vox web app (no app-specific logic).
pub fn emit_runtime_install() -> String {
    r##"// AUTO-GENERATED by Vox — browser runtime-global shims (web target).
// Do not edit; regenerate with `vox build`. Side-effect module: importing it
// installs `str`/`len`/`Speech`/`std`/`mobile` on globalThis so emitted code's
// bare references resolve in the browser.

declare global {
  // eslint-disable-next-line no-var
  var str: (x: unknown) => string;
  // eslint-disable-next-line no-var
  var len: (x: unknown) => number;
  // eslint-disable-next-line no-var
  var Speech: { transcribe_microphone: () => SpeechResult | Promise<SpeechResult> };
  // eslint-disable-next-line no-var
  var std: {
    time: { now_ms: () => number };
    crypto: { uuid: () => string; hash_secure: (s: string) => Promise<string> };
    json: { parse: (s: string) => unknown };
    regex: { compile: (p: string) => { _tag: "Ok"; _p0: RegExp } | { _tag: "Error"; _p0: string } };
  };
  // eslint-disable-next-line no-var
  var mobile: { transcribe_microphone: () => SpeechResult | Promise<SpeechResult> };
}

type SpeechResult = { _tag: "Ok"; _p0: string } | { _tag: "Error"; _p0: string };

(globalThis as unknown as { str: typeof globalThis.str }).str = (x: unknown): string => String(x);
(globalThis as unknown as { len: typeof globalThis.len }).len = (x: unknown): number => {
  if (Array.isArray(x)) return x.length;
  if (typeof x === "string") return x.length;
  if (x && typeof x === "object" && "length" in x) return (x as { length: number }).length;
  return 0;
};

// Synchronous SpeechResult when __VOX_TEST_TRANSCRIPT__ is set (e2e injection),
// else the Web Speech API / prompt fallback.
function transcribeMicrophone(): SpeechResult | Promise<SpeechResult> {
  const testTranscript = (globalThis as unknown as { __VOX_TEST_TRANSCRIPT__?: string })
    .__VOX_TEST_TRANSCRIPT__;
  if (typeof testTranscript === "string") {
    return { _tag: "Ok", _p0: testTranscript };
  }
  const SR =
    (window as unknown as { SpeechRecognition?: unknown; webkitSpeechRecognition?: unknown })
      .SpeechRecognition ||
    (window as unknown as { SpeechRecognition?: unknown; webkitSpeechRecognition?: unknown })
      .webkitSpeechRecognition;
  if (typeof SR === "function") {
    return new Promise<SpeechResult>((resolve) => {
      const r = new (SR as new () => {
        continuous: boolean;
        interimResults: boolean;
        lang: string;
        start(): void;
        onresult: (e: { results: ArrayLike<ArrayLike<{ transcript: string }>> }) => void;
        onerror: (e: { error: string }) => void;
      })();
      r.continuous = false;
      r.interimResults = false;
      r.lang = "en-US";
      r.onresult = (e) => {
        const transcript = e.results[0]?.[0]?.transcript ?? "";
        resolve({ _tag: "Ok", _p0: transcript });
      };
      r.onerror = (e) => resolve({ _tag: "Error", _p0: e.error });
      try {
        r.start();
      } catch (e) {
        resolve({ _tag: "Error", _p0: String(e) });
      }
    });
  }
  const text = window.prompt("Voice input (no STT engine available — type instead):");
  if (text) return { _tag: "Ok", _p0: text };
  return { _tag: "Error", _p0: "cancelled" };
}

const speechShim = { transcribe_microphone: transcribeMicrophone };
(globalThis as unknown as { Speech: typeof globalThis.Speech }).Speech = speechShim;
(globalThis as unknown as { mobile: typeof globalThis.mobile }).mobile = speechShim;

(globalThis as unknown as { std: typeof globalThis.std }).std = {
  time: { now_ms: () => Date.now() },
  crypto: {
    uuid: () =>
      typeof crypto !== "undefined" && "randomUUID" in crypto
        ? crypto.randomUUID()
        : `vox-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`,
    hash_secure: async (s: string): Promise<string> => {
      const buf = new TextEncoder().encode(s);
      const digest = await crypto.subtle.digest("SHA-256", buf);
      return Array.from(new Uint8Array(digest))
        .map((b) => b.toString(16).padStart(2, "0"))
        .join("");
    },
  },
  json: { parse: (s: string) => JSON.parse(s) },
  regex: {
    compile: (p: string) => {
      try {
        return { _tag: "Ok" as const, _p0: new RegExp(p) };
      } catch (e) {
        return { _tag: "Error" as const, _p0: String(e) };
      }
    },
  },
};

export {};
"##
    .to_string()
}

/// Emit `vox-app.tsx`. When `has_route_manifest` is true the app renders the
/// dependency-free history-API router over the emitted `./routes.manifest`;
/// otherwise it flat-mounts `root_component` (which must be an emitted component).
pub fn emit_web_app(has_route_manifest: bool, root_component: Option<&str>) -> String {
    if has_route_manifest {
        emit_router_app()
    } else if let Some(root) = root_component {
        emit_flat_app(root)
    } else {
        // No routes and no components — nothing to mount. Emit a harmless stub so
        // `entry.tsx` always has a `<VoxApp/>` to import.
        emit_empty_app()
    }
}

/// History-API router (no external dep). Generalizes the hand-written client
/// router: exact-path match with index fallback, intra-app `<a>` interception
/// (push history instead of full navigation), and a 404 for unknown paths.
fn emit_router_app() -> String {
    r##"// AUTO-GENERATED by Vox — web app root (dependency-free history-API router).
// Do not edit; regenerate with `vox build`. Renders the emitted routes manifest.
import React, { useEffect, useState } from "react";
import { voxRoutes, type VoxRoute } from "./routes.manifest";

function findRoute(path: string): VoxRoute | undefined {
  const exact = voxRoutes.find((r) => r.path === path);
  if (exact) return exact;
  return voxRoutes.find((r) => r.index);
}

export function VoxApp(): React.ReactElement {
  const [path, setPath] = useState<string>(
    typeof window !== "undefined" ? window.location.pathname : "/",
  );

  useEffect(() => {
    const onPop = () => setPath(window.location.pathname);
    window.addEventListener("popstate", onPop);

    const onClick = (e: MouseEvent) => {
      // Only intercept plain left-clicks on intra-app links.
      if (e.button !== 0 || e.metaKey || e.ctrlKey || e.shiftKey || e.altKey) return;
      const a = (e.target as HTMLElement).closest?.("a");
      if (!a) return;
      const href = a.getAttribute("href");
      if (!href || href.startsWith("http") || href.startsWith("//") || href.startsWith("#")) return;
      e.preventDefault();
      window.history.pushState(null, "", href);
      setPath(href);
    };
    document.addEventListener("click", onClick);

    return () => {
      window.removeEventListener("popstate", onPop);
      document.removeEventListener("click", onClick);
    };
  }, []);

  const route = findRoute(path);
  if (!route) {
    return (
      <div className="mh-root">
        <h1>404</h1>
        <p>
          No route for <code>{path}</code>.
        </p>
        <a href="/">Go home</a>
      </div>
    );
  }
  const Component = route.component;
  return <Component />;
}
"##
    .to_string()
}

/// Flat single-component mount — the web analog of RN's route-less `App.tsx`.
fn emit_flat_app(root_component: &str) -> String {
    format!(
        "// AUTO-GENERATED by Vox — web app root (flat mount; no routes declared).\n\
         // Do not edit; regenerate with `vox build`.\n\
         import React from \"react\";\n\
         import {{ {root} }} from \"./{root}\";\n\
         \n\
         export function VoxApp(): React.ReactElement {{\n\
         \x20 return <{root} />;\n\
         }}\n",
        root = root_component
    )
}

/// No routes and no components: a placeholder so `entry.tsx` still resolves.
fn emit_empty_app() -> String {
    "// AUTO-GENERATED by Vox — web app root (no components emitted).\n\
     import React from \"react\";\n\
     \n\
     export function VoxApp(): React.ReactElement {\n\
     \x20 return <div>No Vox components to render.</div>;\n\
     }\n"
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn router_app_imports_manifest_and_exports_voxapp() {
        let out = emit_web_app(true, None);
        assert!(out.contains("import { voxRoutes, type VoxRoute } from \"./routes.manifest\""));
        assert!(out.contains("export function VoxApp()"));
        assert!(out.contains("window.history.pushState"));
        // Dependency-free: must NOT pull in an external router.
        assert!(!out.contains("react-router"));
        assert!(!out.contains("@tanstack/router"));
    }

    #[test]
    fn flat_app_mounts_root_component() {
        let out = emit_web_app(false, Some("Home"));
        assert!(out.contains("import { Home } from \"./Home\""));
        assert!(out.contains("return <Home />"));
        assert!(!out.contains("routes.manifest"));
    }

    #[test]
    fn empty_app_is_self_contained() {
        let out = emit_web_app(false, None);
        assert!(out.contains("export function VoxApp()"));
        assert!(!out.contains("./routes.manifest"));
    }

    #[test]
    fn runtime_install_provides_globals_and_test_hook() {
        let out = emit_runtime_install();
        for g in ["str", "len", "Speech", "std", "mobile"] {
            assert!(out.contains(g), "missing global: {g}");
        }
        // The e2e suite injects this synchronous transcript hook.
        assert!(out.contains("__VOX_TEST_TRANSCRIPT__"));
        // Side-effect module.
        assert!(out.contains("export {};"));
    }

    #[test]
    fn entry_mounts_voxapp_and_delegates_to_app_hooks() {
        let out = emit_web_entry();
        assert!(out.contains("import \"./runtime-install\""));
        assert!(out.contains("import { VoxApp } from \"./vox-app\""));
        assert!(out.contains("import { wrapApp, onBoot } from \"./app-hooks\""));
        assert!(out.contains("document.getElementById(\"root\")"));
        assert!(out.contains("wrapApp(<VoxApp />)"));
        assert!(out.contains("onBoot()"));
    }

    #[test]
    fn default_app_hooks_wire_error_boundary_and_sw() {
        let out = emit_app_hooks_default();
        assert!(out.contains("import { ErrorBoundary } from \"./vox-error-boundary\""));
        assert!(out.contains("import { registerServiceWorker } from \"./vox-sw-register\""));
        assert!(out.contains("<ErrorBoundary>{app}</ErrorBoundary>"));
        assert!(out.contains("registerServiceWorker()"));
    }

    #[test]
    fn error_boundary_is_a_generic_class_component() {
        let out = emit_error_boundary();
        assert!(out.contains("export class ErrorBoundary extends React.Component"));
        assert!(out.contains("getDerivedStateFromError"));
        assert!(out.contains("componentDidCatch"));
        // Generic: no app-specific crash-log / IndexedDB coupling.
        assert!(!out.contains("indexedDB"));
        assert!(!out.contains("loadCrashes"));
    }

    #[test]
    fn sw_register_is_graceful() {
        let out = emit_sw_register();
        assert!(out.contains("export async function registerServiceWorker"));
        assert!(out.contains("\"serviceWorker\" in navigator"));
        // Logs, never throws.
        assert!(out.contains("console.error"));
    }
}
