use anyhow::{Context, Result};
use std::fs;
use std::path::Path;
use vox_doc_pipeline::pipeline::anchors::readme_anchor;

pub fn run(repo_root: &Path) -> Result<()> {
    let readme_path = repo_root.join("README.md");
    let content = fs::read_to_string(&readme_path)
        .with_context(|| format!("Failed to read {}", readme_path.display()))?;

    let table_content = readme_anchor(&content, "tier_table").context(
        "Could not find ANCHOR: tier_table / ANCHOR_END: tier_table markers in README.md",
    )?;

    let output_content = format!(
        "# What's Shipped Today\n\nThis file is auto-generated by `vox ci capability-snapshot` from the README.md.\n\n## Domain Matrix\n\n{}\n",
        table_content
    );

    let docs_dir = repo_root.join("docs/src/reference");
    fs::create_dir_all(&docs_dir).ok();

    let output_path = docs_dir.join("shipped-v0.4.md");
    fs::write(&output_path, output_content)
        .with_context(|| format!("Failed to write {}", output_path.display()))?;

    println!("capability-snapshot OK (wrote {})", output_path.display());
    Ok(())
}
