//! Generate GUI settings surfaces from vox_config::config_registry::CONFIG_KEYS.
//!
//! `vox ci config-gui-codegen` renders a `generatedSettingsIndex.ts` so the GUI
//! settings search index is a VIEW over the registry SSOT (no hand-maintained
//! drift). `--check` is the drift gate: fail if the on-disk file differs.

use std::path::Path;

use vox_config::config_key::{ConfigKey, Group};
use vox_config::config_registry::CONFIG_KEYS;
use vox_config::operator_registry::ConfigClass;

/// Output path for the generated TS module, relative to repo-root current_dir.
const OUT_REL_PATH: &str = "crates/vox-gui/ui/src/config/generatedSettingsIndex.ts";

/// True if this knob is operator-facing and should appear in the GUI.
pub fn is_surfaced(k: &ConfigKey) -> bool {
    k.gui.is_some() || k.class == ConfigClass::UserPreference
}

/// The GUI section id for a knob (explicit gui section, else derived from group).
pub fn section_of(k: &ConfigKey) -> String {
    if let Some(g) = k.gui {
        return g.section.to_string();
    }
    match k.group {
        Group::Tuning => "tuning",
        Group::Mesh => "mesh",
        Group::Runtime => "runtime",
        Group::ModelsAndEndpoints => "models",
        Group::Orchestrator => "orchestrator",
        Group::Storage => "storage",
        Group::Security => "security",
        Group::Telemetry => "telemetry",
        Group::Training => "training",
        Group::General => "general",
    }
    .to_string()
}

/// Derive a stable kebab id from the FULL key: lowercase, _ -> -.
///
/// Deliberately does NOT strip the `VOX_` prefix (unlike `keywords_of`), because
/// `CONFIG_KEYS` contains current/legacy pairs that share the same tail once that
/// prefix is dropped — e.g. `VOX_OPENAI_BASE_URL` (env-homed) and the legacy
/// `OPENAI_BASE_URL` (vox.toml-homed) both reduce to `openai-base-url`. Since
/// `ConfigKey::key` is documented as "the unique id" of the registry, deriving the
/// GUI id from the full key makes id uniqueness follow automatically from key
/// uniqueness instead of depending on prefix bookkeeping — see
/// `ids_are_unique_across_surfaced_keys` below.
pub fn id_of(key: &str) -> String {
    key.to_lowercase().replace('_', "-")
}

/// Search keywords from the key tokens (lowercased, VOX dropped).
pub fn keywords_of(key: &str) -> Vec<String> {
    key.strip_prefix("VOX_")
        .unwrap_or(key)
        .to_lowercase()
        .split('_')
        .filter(|s| !s.is_empty())
        .map(|s| s.to_string())
        .collect()
}

/// Render the generated TS search-index module from surfaced keys (sorted by section,id).
pub fn render_generated_index_ts(keys: &[ConfigKey]) -> String {
    let mut rows: Vec<(String, String, String, String, Vec<String>)> = keys
        .iter()
        .filter(|k| is_surfaced(k))
        .map(|k| {
            (
                id_of(k.key),
                section_of(k),
                k.label.to_string(),
                k.hint.to_string(),
                keywords_of(k.key),
            )
        })
        .collect();
    rows.sort_by(|a, b| (&a.1, &a.0).cmp(&(&b.1, &b.0)));
    let mut body = String::new();
    for (id, section, label, hint, kw) in rows {
        let kw_ts = kw
            .iter()
            .map(|k| format!("{k:?}"))
            .collect::<Vec<_>>()
            .join(", ");
        body.push_str(&format!(
            "  {{ id: {id:?}, section: {section:?}, label: {label:?}, hint: {hint:?}, keywords: [{kw_ts}] }},\n"
        ));
    }
    format!(
        "// @generated by `vox ci config-gui-codegen` from CONFIG_KEYS — DO NOT EDIT.\n\
         import type {{ SettingEntry }} from '../components/surfaces/Settings/settingsIndex';\n\
         export const GENERATED_SETTINGS_INDEX: SettingEntry[] = [\n{body}];\n"
    )
}

/// Map ConfigKind to the GUI kind string.
fn kind_str(k: vox_config::config_key::ConfigKind) -> &'static str {
    use vox_config::config_key::ConfigKind;
    match k {
        ConfigKind::Bool => "bool",
        ConfigKind::Int => "int",
        ConfigKind::Float => "float",
        ConfigKind::String => "string",
        ConfigKind::Path => "path",
        ConfigKind::Url => "string", // GUI treats URL as a string input
        ConfigKind::Enum => "enum",
    }
}

/// Map DefaultValue to a display string.
fn default_str(d: vox_config::config_key::DefaultValue) -> String {
    use vox_config::config_key::DefaultValue;
    match d {
        DefaultValue::Literal(s) => s.to_string(),
        DefaultValue::Computed(desc) => format!("<{desc}>"),
    }
}

/// Render the generated Rust FIELDS file from surfaced keys (sorted by section, id).
pub fn render_generated_fields_rs(keys: &[ConfigKey]) -> String {
    let mut rows: Vec<(String, String, String, String, String, Vec<String>, String)> = keys
        .iter()
        .filter(|k| is_surfaced(k))
        .map(|k| {
            let opts: Vec<String> = k
                .gui
                .map(|g| g.options.iter().map(|s| format!("{s:?}")).collect())
                .unwrap_or_default();
            (
                k.key.to_string(),
                k.label.to_string(),
                k.hint.to_string(),
                section_of(k),
                kind_str(k.kind).to_string(),
                opts,
                default_str(k.default),
            )
        })
        .collect();
    rows.sort_by(|a, b| (&a.3, &a.0).cmp(&(&b.3, &b.0)));

    let mut body = String::new();
    for (key, label, hint, section, kind, opts, default) in &rows {
        let opts_rs = if opts.is_empty() {
            "&[]".to_string()
        } else {
            format!("&[{}]", opts.join(", "))
        };
        body.push_str(&format!(
            "    GeneratedField {{ key: {key:?}, label: {label:?}, hint: {hint:?}, \
             section: {section:?}, kind: {kind:?}, options: {opts_rs}, default: {default:?} }},\n"
        ));
    }

    format!(
        "// @generated by `vox ci config-gui-codegen --fields` from CONFIG_KEYS — DO NOT EDIT.\n\
         // Regenerate with: vox ci config-gui-codegen --fields\n\
         //\n\
         // GeneratedField is defined in the parent module (crates/vox-gui/src/config/mod.rs).\n\
         // This file is included via: include!(\"generated_fields.rs\"); inside mod.rs.\n\
         \n\
         &[\n{body}]\n"
    )
}

/// Relative path for the generated Rust FIELDS file.
const FIELDS_REL_PATH: &str = "crates/vox-gui/src/config/generated_fields.rs";

/// Run the Rust FIELDS generator. `check=true` is the drift gate.
pub fn run_fields(check: bool) -> anyhow::Result<()> {
    let root = std::env::current_dir()?;
    let rendered = render_generated_fields_rs(CONFIG_KEYS);
    let path = root.join(FIELDS_REL_PATH);

    if check {
        let on_disk = std::fs::read_to_string(&path).map_err(|e| {
            anyhow::anyhow!(
                "config-gui-codegen --fields --check: cannot read {FIELDS_REL_PATH}: {e}. \
                 Run `vox ci config-gui-codegen --fields` to generate it."
            )
        })?;
        if on_disk != rendered {
            anyhow::bail!(
                "config-gui-codegen --fields drift: {FIELDS_REL_PATH} is stale. \
                 Regenerate with `vox ci config-gui-codegen --fields` and commit."
            );
        }
        println!("config-gui-codegen --fields OK: {FIELDS_REL_PATH} matches CONFIG_KEYS.");
        return Ok(());
    }

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&path, &rendered)?;
    let rows = rendered.matches("GeneratedField {").count();
    println!("config-gui-codegen --fields: wrote {rows} field(s) to {FIELDS_REL_PATH}");
    Ok(())
}

/// Run the generator. `check=true` is the drift gate (compare, do not write).
pub fn run(check: bool) -> anyhow::Result<()> {
    let root = std::env::current_dir()?;
    let rendered = render_generated_index_ts(CONFIG_KEYS);
    let path: &Path = &root.join(OUT_REL_PATH);

    if check {
        let on_disk = std::fs::read_to_string(path).map_err(|e| {
            anyhow::anyhow!(
                "config-gui-codegen --check: cannot read {OUT_REL_PATH}: {e}. \
                 Run `vox ci config-gui-codegen` to generate it."
            )
        })?;
        if on_disk != rendered {
            anyhow::bail!(
                "config-gui-codegen drift: {OUT_REL_PATH} is stale. \
                 Regenerate with `vox ci config-gui-codegen` and commit."
            );
        }
        println!("config-gui-codegen OK: {OUT_REL_PATH} matches CONFIG_KEYS.");
        return Ok(());
    }

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, &rendered)?;
    let rows = rendered.matches("  { id:").count();
    println!("config-gui-codegen: wrote {rows} entry(ies) to {OUT_REL_PATH}");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use vox_config::config_registry::CONFIG_KEYS;
    #[test]
    fn id_and_keywords_derive_from_key() {
        // id_of keeps the VOX_ prefix (see doc comment) so ids stay 1:1 with keys;
        // keywords_of still drops it since search keywords don't need uniqueness.
        assert_eq!(id_of("VOX_SEARCH_BM25_K1"), "vox-search-bm25-k1");
        assert_eq!(
            keywords_of("VOX_SEARCH_BM25_K1"),
            vec!["search", "bm25", "k1"]
        );
    }
    #[test]
    fn id_of_disambiguates_current_vs_legacy_pair() {
        // Regression test for the VOX_OPENAI_BASE_URL / OPENAI_BASE_URL collision:
        // both keys reduce to "openai-base-url" once the VOX_ prefix is stripped,
        // so id_of must NOT strip it.
        assert_eq!(id_of("VOX_OPENAI_BASE_URL"), "vox-openai-base-url");
        assert_eq!(id_of("OPENAI_BASE_URL"), "openai-base-url");
        assert_ne!(id_of("VOX_OPENAI_BASE_URL"), id_of("OPENAI_BASE_URL"));
    }
    #[test]
    fn ids_are_unique_across_surfaced_keys() {
        // The regression guard: any current CONFIG_KEYS collision (or any future
        // one — e.g. a new legacy alias for an existing VOX_-prefixed key) must
        // produce distinct GUI-search ids. This is what would have caught the
        // VOX_OPENAI_BASE_URL / OPENAI_BASE_URL collision before it shipped.
        let mut seen: std::collections::HashMap<String, &str> = std::collections::HashMap::new();
        for k in CONFIG_KEYS.iter().filter(|k| is_surfaced(k)) {
            let id = id_of(k.key);
            if let Some(prev_key) = seen.insert(id.clone(), k.key) {
                panic!(
                    "duplicate GUI-search id {id:?} derived from both {prev_key:?} and {:?}",
                    k.key
                );
            }
        }
    }
    #[test]
    fn renders_surfaced_keys_with_header() {
        let ts = render_generated_index_ts(CONFIG_KEYS);
        assert!(ts.contains("@generated"));
        assert!(ts.contains("GENERATED_SETTINGS_INDEX"));
        // at least one UserPreference SEARCH row surfaces:
        assert!(ts.contains("search-"));
    }
    #[test]
    fn render_fields_rs_has_header_and_surfaced_keys() {
        let rs = render_generated_fields_rs(CONFIG_KEYS);
        assert!(rs.contains("@generated"));
        assert!(rs.contains("GeneratedField {"));
        // at least one surfaced key should appear
        assert!(rs.len() > 200, "generated output suspiciously short");
    }
    #[test]
    fn generated_fields_keys_equal_surfaced_config_keys() {
        let rendered = render_generated_fields_rs(CONFIG_KEYS);
        let surfaced: std::collections::BTreeSet<&str> = CONFIG_KEYS
            .iter()
            .filter(|k| is_surfaced(k))
            .map(|k| k.key)
            .collect();
        // Every surfaced key should appear in the rendered output
        for key in &surfaced {
            assert!(
                rendered.contains(key),
                "surfaced key {key} missing from generated_fields"
            );
        }
    }
    #[test]
    fn ts_index_and_rust_fields_cover_identical_surfaced_keys() {
        // Both generators must emit exactly the same set of CONFIG_KEYS rows.
        // Drift between them is impossible as long as both call is_surfaced() on
        // the same slice — this test pins that invariant.
        let surfaced: Vec<&str> = CONFIG_KEYS
            .iter()
            .filter(|k| is_surfaced(k))
            .map(|k| k.key)
            .collect();
        let ts = render_generated_index_ts(CONFIG_KEYS);
        let rs = render_generated_fields_rs(CONFIG_KEYS);
        for key in &surfaced {
            let id = id_of(key);
            // TS format: `id: "wasm-skill-fuel"` (kebab id, not raw env key)
            assert!(
                ts.contains(&format!("id: {id:?}")),
                "key {key} (id={id}) missing from generated TS index"
            );
            // Rust FIELDS format: `key: "VOX_WASM_SKILL_FUEL"` (raw env key)
            assert!(
                rs.contains(key),
                "key {key} missing from generated Rust FIELDS"
            );
        }
        // Both surfaces must reference the same count of distinct keys.
        let ts_count = ts.matches("id: \"").count();
        let rs_count = rs.matches("GeneratedField {").count();
        assert_eq!(
            ts_count, rs_count,
            "TS index has {ts_count} entries but Rust FIELDS has {rs_count} — surfaces diverged"
        );
    }
}
