//! `vox ci plugin-surface-sync [--write]`
//!
//! Single source of truth for the **plugin extension-point surface**. The traits in
//! `crates/vox-plugin-api/src/extensions/*.rs` (each a `#[sabi_trait]` with a
//! `*_REVISION` constant) are the SSOT; this command extracts them into
//! `contracts/plugin/extension-points.v1.yaml` and, in verify mode (the default), fails
//! when the committed file drifts from the traits.
//!
//! It also runs two parity invariants:
//! - **sdk-abi-parity**: every extension module must have a matching `as_<module>()`
//!   accessor on the `VoxPlugin` trait in `abi.rs`, and vice versa — so a new extension
//!   point can't be added without wiring its accessor (or an accessor left dangling after
//!   a trait is removed).
//! - **manifest parity**: for every code/composite `Plugin.toml`, each
//!   `provides.extension-points` entry must name a real extension point from the SSOT (no
//!   misspelled/removed points), and the `abi-version` literal must equal the host's
//!   `VOX_PLUGIN_ABI_VERSION` (no stale per-manifest ABI literals).

use anyhow::{Context, Result, anyhow, bail};
use regex::Regex;
use serde::Serialize;
use std::path::Path;

const GENERATED_HEADER: &str = "\
# @generated by `vox ci plugin-surface-sync --write`
# Source of truth: crates/vox-plugin-api/src/extensions/*.rs (+ the VoxPlugin accessors
# in crates/vox-plugin-api/src/abi.rs). Do NOT hand-edit — regenerate instead.
";

const REL_OUTPUT: &str = "contracts/plugin/extension-points.v1.yaml";
const REL_EXTENSIONS: &str = "crates/vox-plugin-api/src/extensions";
const REL_ABI: &str = "crates/vox-plugin-api/src/abi.rs";

#[derive(Serialize)]
struct Surface {
    schema_version: u32,
    /// Mirrors `vox_plugin_api::VOX_PLUGIN_ABI_VERSION` at generation time.
    abi_version: u32,
    extension_points: Vec<ExtPoint>,
}

#[derive(Serialize)]
struct ExtPoint {
    /// PascalCase trait name (matches the `Plugin.toml` `provides.extension-points` vocab).
    name: String,
    /// snake_case module file stem.
    module: String,
    /// The trait's `*_REVISION` constant.
    revision: u32,
    /// The `VoxPlugin` accessor that surfaces this extension (`as_<module>`).
    accessor: String,
    /// Sorted method names declared on the trait (includes the defaulted `revision`).
    methods: Vec<String>,
}

/// Parse every extension module and the VoxPlugin accessor set, cross-check parity, and
/// return the canonical surface.
fn extract_surface(repo_root: &Path) -> Result<Surface> {
    let trait_re = Regex::new(r"(?m)^pub trait\s+(\w+)").expect("trait regex");
    let rev_re =
        Regex::new(r"(?m)^pub const\s+\w+_REVISION:\s*u32\s*=\s*(\d+)\s*;").expect("rev regex");
    let fn_re = Regex::new(r"(?m)^\s*fn\s+(\w+)\s*[(<]").expect("fn regex");

    let ext_dir = repo_root.join(REL_EXTENSIONS);
    let mut files: Vec<std::path::PathBuf> = std::fs::read_dir(&ext_dir)
        .with_context(|| format!("read_dir {}", ext_dir.display()))?
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| {
            p.extension().and_then(|x| x.to_str()) == Some("rs")
                && p.file_stem().and_then(|s| s.to_str()) != Some("mod")
        })
        .collect();
    files.sort();

    let mut points: Vec<ExtPoint> = Vec::new();
    for path in &files {
        let module = path
            .file_stem()
            .and_then(|s| s.to_str())
            .ok_or_else(|| anyhow!("bad file stem: {}", path.display()))?
            .to_string();
        let src =
            std::fs::read_to_string(path).with_context(|| format!("read {}", path.display()))?;
        let name = trait_re
            .captures(&src)
            .and_then(|c| c.get(1))
            .map(|m| m.as_str().to_string())
            .ok_or_else(|| anyhow!("{}: no `pub trait` found", path.display()))?;
        let revision: u32 = rev_re
            .captures(&src)
            .and_then(|c| c.get(1))
            .ok_or_else(|| anyhow!("{}: no `*_REVISION: u32 = N;` constant", path.display()))?
            .as_str()
            .parse()
            .with_context(|| format!("{}: REVISION not a u32", path.display()))?;
        let mut methods: Vec<String> = fn_re
            .captures_iter(&src)
            .filter_map(|c| c.get(1).map(|m| m.as_str().to_string()))
            .collect();
        methods.sort();
        methods.dedup();
        points.push(ExtPoint {
            accessor: format!("as_{module}"),
            name,
            module,
            revision,
            methods,
        });
    }
    points.sort_by(|a, b| a.name.cmp(&b.name));

    check_accessor_parity(repo_root, &points)?;

    Ok(Surface {
        schema_version: 1,
        abi_version: vox_plugin_api::VOX_PLUGIN_ABI_VERSION,
        extension_points: points,
    })
}

/// sdk-abi-parity: the set of `as_<module>` accessors on `VoxPlugin` must exactly equal the
/// set of extension modules. Catches an extension added without an accessor (unreachable by
/// the host) or an accessor left behind after a trait was removed.
fn check_accessor_parity(repo_root: &Path, points: &[ExtPoint]) -> Result<()> {
    let abi_src = std::fs::read_to_string(repo_root.join(REL_ABI))
        .with_context(|| format!("read {REL_ABI}"))?;
    let acc_re = Regex::new(r"(?m)fn\s+as_(\w+)\s*\(").expect("accessor regex");
    let mut accessors: Vec<String> = acc_re
        .captures_iter(&abi_src)
        .filter_map(|c| c.get(1).map(|m| m.as_str().to_string()))
        .collect();
    accessors.sort();
    accessors.dedup();

    let mut modules: Vec<String> = points.iter().map(|p| p.module.clone()).collect();
    modules.sort();

    let missing_accessor: Vec<&String> =
        modules.iter().filter(|m| !accessors.contains(m)).collect();
    let dangling_accessor: Vec<&String> =
        accessors.iter().filter(|a| !modules.contains(a)).collect();

    if !missing_accessor.is_empty() || !dangling_accessor.is_empty() {
        let mut msg =
            String::from("sdk-abi-parity: VoxPlugin accessors vs extension modules mismatch.\n");
        if !missing_accessor.is_empty() {
            msg.push_str(&format!(
                "  extension modules with no `as_<module>()` accessor in abi.rs: {missing_accessor:?}\n"
            ));
        }
        if !dangling_accessor.is_empty() {
            msg.push_str(&format!(
                "  `as_*` accessors with no matching extension module: {dangling_accessor:?}\n"
            ));
        }
        bail!(msg);
    }
    Ok(())
}

/// Per-manifest SSOT checks against the canonical surface, run over every code/composite
/// `Plugin.toml`:
/// - **provides parity**: each `provides.extension-points` entry must name a real extension
///   point — catches typos and references to renamed/removed extension points.
/// - **abi-version parity**: the manifest's `abi-version` literal must equal the host's
///   `VOX_PLUGIN_ABI_VERSION` (carried on the surface). A stale literal would otherwise only
///   surface at load time, per platform.
fn check_manifests(repo_root: &Path, surface: &Surface) -> Result<()> {
    let valid: std::collections::BTreeSet<&str> = surface
        .extension_points
        .iter()
        .map(|p| p.name.as_str())
        .collect();
    let crates_root = repo_root.join("crates");
    if !crates_root.is_dir() {
        return Ok(());
    }
    let mut violations: Vec<String> = Vec::new();
    for entry in walkdir::WalkDir::new(&crates_root)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| e.file_name() == "Plugin.toml")
    {
        let path = entry.path();
        if path.components().any(|c| c.as_os_str() == "tests") {
            continue;
        }
        let raw =
            std::fs::read_to_string(path).with_context(|| format!("read {}", path.display()))?;
        let Ok(val) = raw.parse::<toml::Value>() else {
            continue; // malformed manifests are surfaced by other gates
        };
        let Some(payload) = val.get("plugin").and_then(|p| p.get("payload")) else {
            continue;
        };
        // code → payload.{abi-version,provides} ; composite → payload.code.{abi-version,provides}
        let code = payload.get("code").unwrap_or(payload);

        // abi-version parity (code/composite carry it; skill payloads omit it).
        if let Some(abi) = code.get("abi-version").and_then(|v| v.as_integer())
            && abi != i64::from(surface.abi_version)
        {
            violations.push(format!(
                "{}: abi-version = {abi} but host VOX_PLUGIN_ABI_VERSION = {}",
                path.display(),
                surface.abi_version
            ));
        }

        // provides parity.
        if let Some(eps) = code
            .get("provides")
            .and_then(|p| p.get("extension-points"))
            .and_then(|e| e.as_array())
        {
            for ep in eps {
                if let Some(name) = ep.as_str()
                    && !valid.contains(name)
                {
                    violations.push(format!(
                        "{}: unknown extension point {name:?}",
                        path.display()
                    ));
                }
            }
        }

        // artifact parity: every key is a canonical target triple, and every filename
        // follows the cdylib naming rule derived from the crate directory name.
        let crate_name = path
            .parent()
            .and_then(|p| p.file_name())
            .and_then(|s| s.to_str());
        if let (Some(crate_name), Some(artifacts)) =
            (crate_name, code.get("artifacts").and_then(|a| a.as_table()))
        {
            for (triple, fname) in artifacts {
                if !vox_plugin_types::PLUGIN_TARGET_TRIPLES.contains(&triple.as_str()) {
                    violations.push(format!(
                        "{}: artifact key {triple:?} is not a known target triple",
                        path.display()
                    ));
                    continue;
                }
                let expected = vox_plugin_types::plugin_artifact_filename(crate_name, triple);
                if expected.as_deref() != fname.as_str() {
                    violations.push(format!(
                        "{}: artifact[{triple}] = {:?} but expected {:?}",
                        path.display(),
                        fname.as_str().unwrap_or_default(),
                        expected.unwrap_or_default()
                    ));
                }
            }
        }
    }
    if !violations.is_empty() {
        let valid_list: Vec<&str> = valid.iter().copied().collect();
        bail!(
            "plugin manifest validation failed:\n  {}\n  valid extension points: {valid_list:?}",
            violations.join("\n  ")
        );
    }
    Ok(())
}

/// manifest↔impl parity: a code/composite plugin's `provides.extension-points` must exactly
/// equal the extension accessors it actually overrides in its `impl VoxPlugin` — so a
/// manifest can't claim a capability the binary doesn't surface (declared-not-implemented),
/// nor silently surface one it doesn't advertise (implemented-not-declared).
fn check_impl_parity(repo_root: &Path, surface: &Surface) -> Result<()> {
    // as_<module> accessor → extension-point name; and the set of known modules.
    let acc_to_name: std::collections::BTreeMap<&str, &str> = surface
        .extension_points
        .iter()
        .map(|p| (p.accessor.as_str(), p.name.as_str()))
        .collect();
    let modules: std::collections::BTreeSet<&str> = surface
        .extension_points
        .iter()
        .map(|p| p.module.as_str())
        .collect();
    let as_re = Regex::new(r"(?m)fn\s+as_(\w+)\s*\(").expect("as_ regex");

    let crates_root = repo_root.join("crates");
    if !crates_root.is_dir() {
        return Ok(());
    }
    let mut violations: Vec<String> = Vec::new();
    for entry in walkdir::WalkDir::new(&crates_root)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| e.file_name() == "Plugin.toml")
    {
        let path = entry.path();
        if path.components().any(|c| c.as_os_str() == "tests") {
            continue;
        }
        let raw =
            std::fs::read_to_string(path).with_context(|| format!("read {}", path.display()))?;
        let Ok(val) = raw.parse::<toml::Value>() else {
            continue;
        };
        let Some(payload) = val.get("plugin").and_then(|p| p.get("payload")) else {
            continue;
        };
        let code = payload.get("code").unwrap_or(payload);
        let Some(provides) = code
            .get("provides")
            .and_then(|p| p.get("extension-points"))
            .and_then(|e| e.as_array())
        else {
            continue; // skill payloads (no code provides) are out of scope
        };
        let declared: std::collections::BTreeSet<String> = provides
            .iter()
            .filter_map(|v| v.as_str().map(str::to_string))
            .collect();

        // Scan the crate's own src/ for overridden `as_<known-module>` accessors. (The
        // trait defaults live in vox-plugin-api, not here, so any such fn is an override.)
        let Some(crate_dir) = path.parent() else {
            continue;
        };
        let mut implemented: std::collections::BTreeSet<String> = Default::default();
        for f in walkdir::WalkDir::new(crate_dir.join("src"))
            .into_iter()
            .filter_map(|e| e.ok())
            .filter(|e| e.path().extension().and_then(|x| x.to_str()) == Some("rs"))
        {
            let src = std::fs::read_to_string(f.path()).unwrap_or_default();
            for cap in as_re.captures_iter(&src) {
                let module = cap.get(1).map(|m| m.as_str()).unwrap_or_default();
                if modules.contains(module)
                    && let Some(name) = acc_to_name.get(format!("as_{module}").as_str())
                {
                    implemented.insert((*name).to_string());
                }
            }
        }

        if declared != implemented {
            let missing: Vec<&String> = declared.difference(&implemented).collect();
            let extra: Vec<&String> = implemented.difference(&declared).collect();
            let mut m = format!("{}: provides vs impl mismatch", path.display());
            if !missing.is_empty() {
                m.push_str(&format!(" — declared but not implemented: {missing:?}"));
            }
            if !extra.is_empty() {
                m.push_str(&format!(" — implemented but not declared: {extra:?}"));
            }
            violations.push(m);
        }
    }
    if !violations.is_empty() {
        bail!(
            "plugin manifest↔impl parity failed:\n  {}",
            violations.join("\n  ")
        );
    }
    Ok(())
}

fn render(surface: &Surface) -> Result<String> {
    let body = serde_yaml::to_string(surface).context("serialize surface to yaml")?;
    Ok(format!("{GENERATED_HEADER}{body}"))
}

/// Run the gate. `write` regenerates the committed file; otherwise verify it matches.
pub fn run(repo_root: &Path, write: bool) -> Result<()> {
    let surface = extract_surface(repo_root)?;
    check_manifests(repo_root, &surface)?;
    check_impl_parity(repo_root, &surface)?;
    let rendered = render(&surface)?;
    let out_path = repo_root.join(REL_OUTPUT);

    if write {
        if let Some(parent) = out_path.parent() {
            std::fs::create_dir_all(parent)
                .with_context(|| format!("create {}", parent.display()))?;
        }
        std::fs::write(&out_path, &rendered)
            .with_context(|| format!("write {}", out_path.display()))?;
        println!(
            "plugin-surface-sync: wrote {REL_OUTPUT} ({} extension point(s))",
            surface.extension_points.len()
        );
        return Ok(());
    }

    let on_disk = std::fs::read_to_string(&out_path).unwrap_or_default();
    // Compare LF-normalized so Windows checkouts don't trip the gate.
    if normalize(&on_disk) != normalize(&rendered) {
        bail!(
            "{REL_OUTPUT} is stale (or missing); run `vox ci plugin-surface-sync --write` from the repo root"
        );
    }
    println!(
        "plugin-surface-sync OK ({} extension point(s); accessor + manifest provides/abi-version/artifact + impl parity clean)",
        surface.extension_points.len()
    );
    Ok(())
}

fn normalize(s: &str) -> String {
    s.replace("\r\n", "\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn repo_root() -> std::path::PathBuf {
        std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .ancestors()
            .nth(2)
            .expect("repo root")
            .to_path_buf()
    }

    #[test]
    fn surface_extracts_all_modules_with_matching_accessors() {
        let surface = extract_surface(&repo_root()).expect("extract");
        // Every module ↔ as_<module> accessor pairing held (else extract_surface errors).
        assert!(
            surface.extension_points.len() >= 12,
            "expected the 12 shipped extension points, got {}",
            surface.extension_points.len()
        );
        let hw = surface
            .extension_points
            .iter()
            .find(|p| p.module == "hardware_probe")
            .expect("hardware_probe present");
        assert_eq!(hw.name, "HardwareProbe");
        assert_eq!(hw.accessor, "as_hardware_probe");
        assert!(hw.methods.contains(&"probe_summary_json".to_string()));
    }

    #[test]
    fn committed_surface_is_in_sync() {
        // The verify path must pass against the committed YAML (keeps CI honest locally).
        run(&repo_root(), false).expect("committed extension-points.v1.yaml is in sync");
    }
}
