//! `routes { … }` declaration → Expo Router file-system route tree.
//!
//! Expo Router uses file-system routing: every file under `app/` corresponds to
//! a route, with `[param]` directory/file names for path parameters and a
//! mandatory `_layout.tsx` at the root (and at any nested level that wants
//! shared layout). See <https://docs.expo.dev/router/introduction>.
//!
//! Vox routes lower as follows:
//!
//!   `"/"`              → `app/index.tsx`
//!   `"/about"`         → `app/about.tsx`
//!   `"/detail/:id"`    → `app/detail/[id].tsx`
//!   `"/u/:user/p/:id"` → `app/u/[user]/p/[id].tsx`
//!
//! Each route file is a one-liner: `export { Component as default } from "<rel>";`
//! where `<rel>` is computed relative to the route file's depth so it always
//! lands at the corresponding component's `.tsx` at the project root.
//!
//! Single source of truth: this consumes the same `ast::decl::RoutesDecl` HIR
//! field (`hir.client_routes`) that the web target's `route_manifest.rs` reads,
//! so adding a route at the Vox source level updates both lowerings.

use vox_compiler::ast::decl::ui::{RouteEntry, RoutesDecl};

/// Emit every `app/`-prefixed route file plus the mandatory root `_layout.tsx`.
///
/// Returns an empty Vec when there are no routes — the caller should fall back
/// to emitting a flat `App.tsx` in that case.
pub fn emit_expo_router_files(routes: &[RoutesDecl]) -> Vec<(String, String)> {
    if routes.is_empty() || routes.iter().all(|r| r.entries.is_empty()) {
        return Vec::new();
    }
    let mut files: Vec<(String, String)> = Vec::new();
    files.push(("app/_layout.tsx".to_string(), root_layout()));
    for routes_decl in routes {
        for entry in &routes_decl.entries {
            collect_route_files(entry, &mut files);
        }
    }
    if let Some(routes_decl) = routes.first() {
        if let Some(name) = &routes_decl.not_found_component {
            files.push(("app/+not-found.tsx".to_string(), route_file(name, 1)));
        }
    }
    files
}

fn collect_route_files(entry: &RouteEntry, out: &mut Vec<(String, String)>) {
    let fs_path = expo_router_fs_path(&entry.path);
    let depth = fs_path.matches('/').count() + 1; // 1 = escape `app/`, +1 per nested dir
    let file_path = format!("app/{fs_path}.tsx");
    out.push((file_path, route_file(&entry.component_name, depth)));
    for child in &entry.children {
        collect_route_files(child, out);
    }
}

/// Convert a Vox route path to its Expo Router file-system equivalent.
fn expo_router_fs_path(vox_path: &str) -> String {
    if vox_path == "/" {
        return "index".to_string();
    }
    vox_path
        .trim_start_matches('/')
        .split('/')
        .map(|seg| {
            if let Some(param) = seg.strip_prefix(':') {
                format!("[{param}]")
            } else if seg == "*" {
                "[...rest]".to_string()
            } else {
                seg.to_string()
            }
        })
        .collect::<Vec<_>>()
        .join("/")
}

fn root_layout() -> String {
    r#"// AUTO-GENERATED by Vox @routes (RN target). Expo Router root layout.
import React from "react";
import { Stack } from "expo-router";
import { SafeAreaProvider } from "react-native-safe-area-context";
import { StatusBar } from "expo-status-bar";

export default function RootLayout(): React.ReactElement {
  return (
    <SafeAreaProvider>
      <StatusBar style="auto" />
      <Stack />
    </SafeAreaProvider>
  );
}
"#
    .to_string()
}

fn route_file(component_name: &str, depth: usize) -> String {
    let rel = "../".repeat(depth);
    format!(
        "// AUTO-GENERATED by Vox @routes (RN target).\n\
         export {{ {component_name} as default }} from \"{rel}{component_name}\";\n"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn root_route_lowers_to_index_tsx() {
        assert_eq!(expo_router_fs_path("/"), "index");
    }

    #[test]
    fn single_segment_route_lowers_unchanged() {
        assert_eq!(expo_router_fs_path("/about"), "about");
    }

    #[test]
    fn parameter_segment_lowers_to_bracket_notation() {
        assert_eq!(expo_router_fs_path("/detail/:id"), "detail/[id]");
    }

    #[test]
    fn nested_parameters_lower_correctly() {
        assert_eq!(
            expo_router_fs_path("/users/:user/posts/:post"),
            "users/[user]/posts/[post]"
        );
    }

    #[test]
    fn wildcard_segment_lowers_to_catchall() {
        assert_eq!(expo_router_fs_path("/files/*"), "files/[...rest]");
    }

    #[test]
    fn route_file_uses_correct_relative_import_depth() {
        assert!(route_file("Home", 1).contains("from \"../Home\""));
        assert!(route_file("Detail", 2).contains("from \"../../Detail\""));
        assert!(route_file("Inner", 3).contains("from \"../../../Inner\""));
    }
}
