use vox_hir::{HirHttpMethod, HirModule, HirRoute, HirType};

use crate::emit_expr::emit_stmt;

/// Default values for generated server code. Override via env: VOX_PORT, VOX_DB_PATH.
pub(crate) mod defaults {
    pub const PORT: u16 = 3000;
    pub const DB_PATH: &str = "app.db";
    /// Default seconds when parse_duration fails (suffix: s, m, h)
    pub const DURATION_S: u64 = 60;
    pub const DURATION_M: u64 = 5;
    pub const DURATION_H: u64 = 1;
    pub const DURATION_FALLBACK_S: u64 = 60;
}

use vox_db::schema_digest::{SchemaDigest, TableInfo, CollectionInfo, IndexInfo, FieldInfo, IndexKind};


pub fn emit_main(module: &HirModule, package_name: &str) -> String {
    let mut out = String::new();
    out.push_str("// Generated by Vox Compiler\n");
    out.push_str("#![allow(unused)]\n");

    let has_tables = !module.tables.is_empty() || !module.collections.is_empty() || !module.vector_indexes.is_empty();

    // Collect which routing methods are actually used
    let mut needs_get = false;
    let mut needs_post = false;
    let mut needs_put = false;
    let mut needs_delete = false;
    for route in &module.routes {
        match route.method {
            HirHttpMethod::Get => needs_get = true,
            HirHttpMethod::Post => needs_post = true,
            HirHttpMethod::Put => needs_put = true,
            HirHttpMethod::Delete => needs_delete = true,
        }
    }
    // Server functions always use post
    if !module.server_fns.is_empty() {
        needs_post = true;
    }

    let mut routing_methods = Vec::new();
    if needs_get {
        routing_methods.push("get");
    }
    if needs_post {
        routing_methods.push("post");
    }
    if needs_put {
        routing_methods.push("put");
    }
    if needs_delete {
        routing_methods.push("delete");
    }

    out.push_str("use warp::{Filter, Rejection, Reply};\n");
    out.push_str("use std::net::SocketAddr;\n");
    out.push_str("use std::sync::Arc;\n");
    out.push_str("use rust_embed::RustEmbed;\n");
    out.push_str("use metrics_exporter_prometheus::PrometheusBuilder;\n");
    if has_tables {
        out.push_str("#[allow(dead_code)]\n");
        out.push_str("enum AppDbGuard {\n");
        out.push_str("    Local(turso::Database),\n");
        out.push_str("    Remote(turso::sync::Database),\n");
        out.push_str("}\n");
        out.push_str("struct AppDb {\n");
        out.push_str("    pub _guard: AppDbGuard,\n");
        out.push_str("    pub conn: turso::Connection,\n");
        out.push_str("    pub subs: std::sync::Arc<vox_runtime::SubscriptionManager>,\n");
        out.push_str("}\n\n");
    }

    // Use the library crate by name (avoids `mod lib;` warning)
    let crate_name = package_name.replace('-', "_");
    out.push_str(&format!("use {}::*;\n\n", crate_name));

    // Embedded static assets
    out.push_str("#[derive(RustEmbed)]\n");
    out.push_str("#[folder = \"public/\"]\n");
    out.push_str("struct Assets;\n\n");

    // Fallback handler for embedded assets (warp)
    out.push_str("async fn serve_embedded(path: String) -> Result<impl Reply, Rejection> {\n");
    out.push_str("    let path = path.trim_start_matches('/');\n");
    out.push_str("    let path = if path.is_empty() { \"index.html\" } else { path };\n");
    out.push_str("    match Assets::get(path) {\n");
    out.push_str("        Some(file) => {\n");
    out.push_str("            let mime = mime_guess::from_path(path).first_or_octet_stream();\n");
    out.push_str("            Ok(warp::reply::with_status(warp::reply::with_header(file.data.to_vec(), \"content-type\", mime.as_ref()), warp::http::StatusCode::OK))\n");
    out.push_str("        }\n");
    out.push_str("        None => {\n");
    out.push_str("            match Assets::get(\"index.html\") {\n");
    out.push_str("                Some(file) => Ok(warp::reply::with_status(warp::reply::with_header(file.data.to_vec(), \"content-type\", \"text/html\"), warp::http::StatusCode::OK)),\n");
    out.push_str("                None => Ok(warp::reply::with_status(warp::reply::with_header(\"Not Found\".as_bytes().to_vec(), \"content-type\", \"text/plain\"), warp::http::StatusCode::NOT_FOUND)),\n");
    out.push_str("            }\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str("#[tokio::main]\n");
    out.push_str("async fn main() {\n");
    out.push_str("    tracing_subscriber::fmt::init();\n    let prometheus_handle = PrometheusBuilder::new().install_recorder().expect(\"failed to install Prometheus recorder\");\n    let auth_config = Arc::new(vox_runtime::AuthConfig::from_env());\n");
    out.push_str("    let rate_limiter = Arc::new(vox_runtime::RateLimiter::from_env());\n");

    // Database setup
    if has_tables {
        out.push_str(&emit_db_setup(module));
    }

    // Scheduled function interval loops
    if !module.scheduled.is_empty() {
        out.push_str("    use std::time::Duration;\n");
        for sched in &module.scheduled {
            let fn_name = &sched.func.name;
            let interval_str = &sched.interval;
            // Parse interval string like "5m", "10s", "1h" into seconds
            out.push_str(&format!(
                "    tokio::spawn(async move {{\n\
                     let dur = parse_duration(\"{interval_str}\");\n\
                     let mut interval = tokio::time::interval(dur);\n\
                     loop {{\n\
                         interval.tick().await;\n\
                         {fn_name}().await;\n\
                     }}\n\
                 }});\n",
            ));
        }
        // Emit the parse_duration helper before routes
    }

    let has_routes = !module.routes.is_empty()
        || !module.server_fns.is_empty()
        || !module.queries.is_empty()
        || !module.mutations.is_empty()
        || !module.actions.is_empty();

    // Setup routes (warp)
    if has_routes {
        if has_tables {
            out.push_str("    let db_filter = warp::any().map(move || db.clone());\n");
        }
        out.push_str("    let auth_filter = warp::any().map(move || auth_config.clone());\n");
        out.push_str("    let limiter_filter = warp::any().map(move || rate_limiter.clone());\n");
        fn path_filter_str(path: &str) -> String {
            let path_req = path.trim_start_matches('/');
            let path_segs: Vec<&str> = path_req.split('/').filter(|s| !s.is_empty()).collect();
            if path_segs.is_empty() {
                "warp::path::end()".into()
            } else {
                path_segs
                    .iter()
                    .map(|s| format!("warp::path(\"{}\")", s))
                    .reduce(|a, b| format!("{}.and({})", a, b))
                    .unwrap_or_else(|| "warp::path::end()".into())
            }
        }
        let mut route_parts = Vec::new();
        for route in &module.routes {
            let method = match route.method {
                HirHttpMethod::Get => "warp::get()",
                HirHttpMethod::Post => "warp::post()",
                HirHttpMethod::Put => "warp::put()",
                HirHttpMethod::Delete => "warp::delete()",
            };
            let handler = route_handler_name(&route.path, &route.method);
            let pf = path_filter_str(&route.path);
            // GET typically has no body; provide Null without parsing
            let body_filter = match route.method {
                HirHttpMethod::Get => "warp::any().map(|| serde_json::Value::Null)",
                _ => "warp::body::json()",
            };
            let r = if has_tables {
                format!(
                    "{}.and({}).and({}).and(warp::header::optional::<String>(\"x-api-key\")).and(warp::header::optional::<String>(\"authorization\")).and(warp::header::optional::<String>(\"x-request-id\")).and(auth_filter.clone()).and(limiter_filter.clone()).and(db_filter.clone()).and_then({})",
                    pf, method, body_filter, handler
                )
            } else {
                format!(
                    "{}.and({}).and({}).and(warp::header::optional::<String>(\"x-api-key\")).and(warp::header::optional::<String>(\"authorization\")).and(warp::header::optional::<String>(\"x-request-id\")).and(auth_filter.clone()).and(limiter_filter.clone()).and_then({})",
                    pf, method, body_filter, handler
                )
            };
            route_parts.push(r);
        }

        struct EndpointRef<'a> {
            name: &'a str,
            _params: &'a [vox_hir::HirParam],
            _body: &'a [vox_hir::HirStmt],
            _is_deprecated: bool,
            route_path: String,
        }
        let mut endpoints: Vec<EndpointRef> = Vec::new();
        for sf in &module.server_fns {
            endpoints.push(EndpointRef {
                name: &sf.name,
                _params: &sf.params,
                _body: &sf.body,
                _is_deprecated: sf.is_deprecated,
                route_path: sf.route_path.clone(),
            });
        }
        for q in &module.queries {
            endpoints.push(EndpointRef {
                name: &q.func.name,
                _params: &q.func.params,
                _body: &q.func.body,
                _is_deprecated: q.func.is_deprecated,
                route_path: format!("/api/query/{}", q.func.name),
            });
        }
        for m in &module.mutations {
            endpoints.push(EndpointRef {
                name: &m.func.name,
                _params: &m.func.params,
                _body: &m.func.body,
                _is_deprecated: m.func.is_deprecated,
                route_path: format!("/api/mutation/{}", m.func.name),
            });
        }
        for a in &module.actions {
            endpoints.push(EndpointRef {
                name: &a.func.name,
                _params: &a.func.params,
                _body: &a.func.body,
                _is_deprecated: a.func.is_deprecated,
                route_path: format!("/api/action/{}", a.func.name),
            });
        }

        for ep in &endpoints {
            let pf = path_filter_str(&ep.route_path);
            let r = if has_tables {
                format!(
                    "{}.and(warp::post()).and(warp::body::json()).and(warp::header::optional::<String>(\"x-api-key\")).and(warp::header::optional::<String>(\"authorization\")).and(warp::header::optional::<String>(\"x-request-id\")).and(auth_filter.clone()).and(limiter_filter.clone()).and(db_filter.clone()).and_then(handle_sf_{})",
                    pf, ep.name
                )
            } else {
                format!(
                    "{}.and(warp::post()).and(warp::body::json()).and(warp::header::optional::<String>(\"x-api-key\")).and(warp::header::optional::<String>(\"authorization\")).and(warp::header::optional::<String>(\"x-request-id\")).and(auth_filter.clone()).and(limiter_filter.clone()).and_then(handle_sf_{})",
                    pf, ep.name
                )
            };
            route_parts.push(r);
        }

        let health_route = "warp::path(\"health\").and(warp::get()).map(|| { metrics::gauge!(\"vox_health_check_status\", \"service\" => \"api\").set(1.0); warp::reply::json(&serde_json::json!({ \"status\": \"ok\", \"version\": env!(\"CARGO_PKG_VERSION\") })) })";
        let metrics_route = "{ let h = prometheus_handle.clone(); warp::path(\"metrics\").and(warp::get()).map(move || warp::reply::with_status(h.render(), warp::http::StatusCode::OK)) }";
        let subscribe_route = if has_tables {
            "warp::path!(\"api\" / \"subscribe\")\n                .and(warp::get())\n                .and(db_filter.clone())\n                .map(|db: std::sync::Arc<AppDb>| {\n                    let mut rx = db.subs.subscribe(\"*\");\n                    let event_stream = async_stream::stream! {\n                        while let Ok(_) = rx.recv().await {\n                            yield Ok::<_, warp::Error>(warp::sse::Event::default().data(\"ping\"));\n                        }\n                    };\n                    warp::sse::reply(warp::sse::keep_alive().stream(event_stream))\n                }).boxed()"
        } else {
            "warp::any().and_then(|| async { Err(warp::reject::not_found()) }).boxed()"
        };

        let routes_chain = {
            let base_routes = format!("({}).or({}).or({})", health_route, metrics_route, subscribe_route);
            if route_parts.is_empty() {
                format!("{}.boxed()", base_routes)
            } else {
                let user_chain = route_parts
                    .iter()
                    .map(|r| format!("({}).boxed()", r))
                    .reduce(|a, b| format!("{}.or({})", a, b))
                    .unwrap();
                format!("({}).or({})", base_routes, user_chain)
            }
        };
        out.push_str(&format!("    let api_routes = {};\n", routes_chain));
        out.push_str("    let fallback = warp::get().and(warp::path::tail()).and_then(|tail: warp::path::Tail| async move { serve_embedded(tail.as_str().to_string()).await });\n");
        out.push_str("    let app = api_routes.or(fallback).with(warp::reply::with::header(\"access-control-allow-origin\", \"*\"));\n");

        out.push_str(&format!(
            "    const DEFAULT_PORT: u16 = {};\n",
            defaults::PORT
        ));
        out.push_str("    let port: u16 = std::env::var(\"VOX_PORT\").ok().and_then(|s| s.parse().ok()).unwrap_or(DEFAULT_PORT);\n");
        out.push_str("    let addr = SocketAddr::from(([127, 0, 0, 1], port));\n");
        out.push_str("    println!(\"Listening on {}\", addr);\n");
        out.push_str("    let listener = tokio::net::TcpListener::bind(addr).await.expect(\"Failed to bind address\");\n");
        out.push_str("    warp::serve(app).run_incoming(listener.incoming()).await;\n");
    } else {
        out.push_str("    println!(\"No routes defined. Exiting.\");\n");
    }
    out.push_str("}\n\n");

    // Generate route handlers
    for route in &module.routes {
        out.push_str(&emit_route_handler(route, has_tables));
    }

    struct EndpointRefGen<'a> {
        name: &'a str,
        params: &'a [vox_hir::HirParam],
        body: &'a [vox_hir::HirStmt],
        is_deprecated: bool,
        is_mutation: bool,
        route_path: String,
        return_type: Option<&'a vox_hir::HirType>,
    }
    let mut endpoints_gen: Vec<EndpointRefGen> = Vec::new();
    for sf in &module.server_fns {
        endpoints_gen.push(EndpointRefGen {
            name: &sf.name,
            params: &sf.params,
            body: &sf.body,
            is_deprecated: sf.is_deprecated,
            is_mutation: false,
            route_path: sf.route_path.clone(),
            return_type: sf.return_type.as_ref(),
        });
    }
    for q in &module.queries {
        endpoints_gen.push(EndpointRefGen {
            name: &q.func.name,
            params: &q.func.params,
            body: &q.func.body,
            is_deprecated: q.func.is_deprecated,
            is_mutation: false,
            route_path: format!("/api/query/{}", q.func.name),
            return_type: q.func.return_type.as_ref(),
        });
    }
    for m in &module.mutations {
        endpoints_gen.push(EndpointRefGen {
            name: &m.func.name,
            params: &m.func.params,
            body: &m.func.body,
            is_deprecated: m.func.is_deprecated,
            is_mutation: true,
            route_path: format!("/api/mutation/{}", m.func.name),
            return_type: m.func.return_type.as_ref(),
        });
    }
    for a in &module.actions {
        endpoints_gen.push(EndpointRefGen {
            name: &a.func.name,
            params: &a.func.params,
            body: &a.func.body,
            is_deprecated: a.func.is_deprecated,
            is_mutation: false,
            route_path: format!("/api/action/{}", a.func.name),
            return_type: a.func.return_type.as_ref(),
        });
    }
    for ep in endpoints_gen {
        let is_stream =
            matches!(ep.return_type, Some(vox_hir::HirType::Generic(n, _)) if n == "Stream");
        if is_stream {
            out.push_str(&emit_sse_handler(
                ep.name,
                ep.params,
                ep.body,
                ep.is_deprecated,
                ep.is_mutation,
                &ep.route_path,
                has_tables,
            ));
        } else {
            out.push_str(&emit_server_fn_handler(
                ep.name,
                ep.params,
                ep.body,
                ep.is_deprecated,
                ep.is_mutation,
                &ep.route_path,
                has_tables,
            ));
        }
    }

    // Emit parse_duration helper if scheduled functions exist
    if !module.scheduled.is_empty() {
        out.push_str(&format!(
            "fn parse_duration(s: &str) -> Duration {{\n\
                let s = s.trim();\n\
                if let Some(num) = s.strip_suffix('s') {{\n\
                    Duration::from_secs(num.parse::<u64>().unwrap_or({}))\n\
                }} else if let Some(num) = s.strip_suffix('m') {{\n\
                    Duration::from_secs(num.parse::<u64>().unwrap_or({}) * 60)\n\
                }} else if let Some(num) = s.strip_suffix('h') {{\n\
                    Duration::from_secs(num.parse::<u64>().unwrap_or({}) * 3600)\n\
                }} else {{\n\
                    Duration::from_secs({})\n\
                }}\n\
            }}\n\n",
            defaults::DURATION_S,
            defaults::DURATION_M,
            defaults::DURATION_H,
            defaults::DURATION_FALLBACK_S
        ));

        // Emit async scheduled fn stubs that call the lib function
        for sched in &module.scheduled {
            if sched.func.is_deprecated {
                out.push_str("#[deprecated]\n");
            }
            out.push_str(&format!("async fn {}() {{\n", sched.func.name));
            for stmt in &sched.func.body {
                out.push_str(&emit_stmt(stmt, 1, false, false));
            }
            out.push_str("}\n\n");
        }
    }

    out
}

pub fn route_handler_name(path: &str, method: &HirHttpMethod) -> String {
    let clean_path = path.replace('/', "_").replace(['{', '}'], "");
    let m = match method {
        HirHttpMethod::Get => "get",
        HirHttpMethod::Post => "post",
        HirHttpMethod::Put => "put",
        HirHttpMethod::Delete => "delete",
    };
    format!("handle_{}{}", m, clean_path)
}

pub fn emit_route_handler(route: &HirRoute, has_tables: bool) -> String {
    let handler_name = route_handler_name(&route.path, &route.method);
    let mut out = String::new();
    if route.is_deprecated {
        out.push_str("#[deprecated]\n");
    }
    out.push_str(&format!("async fn {handler_name}("));
    if has_tables {
        out.push_str(
            "request: serde_json::Value, api_key: Option<String>, auth_header: Option<String>, request_id: Option<String>, auth_config: Arc<vox_runtime::AuthConfig>, rate_limiter: Arc<vox_runtime::RateLimiter>, db: std::sync::Arc<AppDb>",
        );
    } else {
        out.push_str("request: serde_json::Value, api_key: Option<String>, auth_header: Option<String>, request_id: Option<String>, auth_config: Arc<vox_runtime::AuthConfig>, rate_limiter: Arc<vox_runtime::RateLimiter>");
    }
    out.push_str(") -> Result<impl Reply, Rejection> {\n");
    out.push_str(&format!("    let ctx = vox_runtime::RequestContext::with_request_id(\"{}\", request_id.as_deref());\n", route.path));
    out.push_str("    if !vox_runtime::authorize_request(api_key.as_deref(), auth_header.as_deref(), &auth_config) {\n");
    out.push_str("        return Ok(warp::reply::with_status(warp::reply::json(&serde_json::json!({\"error\":\"unauthorized\",\"request_id\":ctx.request_id})), warp::http::StatusCode::UNAUTHORIZED));\n");
    out.push_str("    }\n");
    out.push_str("    if !rate_limiter.allow(&ctx.request_id) {\n");
    out.push_str("        return Ok(warp::reply::with_status(warp::reply::json(&serde_json::json!({\"error\":\"rate_limited\",\"request_id\":ctx.request_id})), warp::http::StatusCode::TOO_MANY_REQUESTS));\n");
    out.push_str("    }\n");
    out.push_str(
        "    tracing::info!(request_id=%ctx.request_id, route=%ctx.route, \"request_start\");\n",
    );
    if has_tables {
        out.push_str("    let conn = &db.conn;\n");
    }
    let mut has_return = false;
    for stmt in &route.body {
        let emitted = crate::emit_expr::emit_stmt_warp(stmt, 1, true, false);
        if emitted.contains("return Ok(warp::reply::json") {
            has_return = true;
        }
        out.push_str(&emitted);
    }
    if !has_return {
        out.push_str("    Ok(warp::reply::json(&serde_json::Value::Null))\n");
    }
    out.push_str("    tracing::info!(request_id=%ctx.request_id, route=%ctx.route, elapsed_ms=ctx.elapsed_ms(), \"request_end\");\n");
    out.push_str("}\n\n");
    out
}

/// Generate a warp handler for a function exposed as an API endpoint.
pub fn emit_server_fn_handler(
    name: &str,
    params: &[vox_hir::HirParam],
    body: &[vox_hir::HirStmt],
    is_deprecated: bool,
    is_mutation: bool,
    route_path: &str,
    has_tables: bool,
) -> String {
    let mut out = String::new();
    if is_deprecated {
        out.push_str("#[deprecated]\n");
    }
    out.push_str(&format!("async fn handle_sf_{}(", name));
    if has_tables {
        out.push_str(
            "request: serde_json::Value, api_key: Option<String>, auth_header: Option<String>, request_id: Option<String>, auth_config: Arc<vox_runtime::AuthConfig>, rate_limiter: Arc<vox_runtime::RateLimiter>, db: std::sync::Arc<AppDb>",
        );
    } else {
        out.push_str("request: serde_json::Value, api_key: Option<String>, auth_header: Option<String>, request_id: Option<String>, auth_config: Arc<vox_runtime::AuthConfig>, rate_limiter: Arc<vox_runtime::RateLimiter>");
    }
    out.push_str(") -> Result<impl Reply, Rejection> {\n");
    out.push_str(&format!("    let ctx = vox_runtime::RequestContext::with_request_id(\"{}\", request_id.as_deref());\n", route_path));
    out.push_str("    if !vox_runtime::authorize_request(api_key.as_deref(), auth_header.as_deref(), &auth_config) {\n");
    out.push_str("        return Ok(warp::reply::with_status(warp::reply::json(&serde_json::json!({\"error\":\"unauthorized\",\"request_id\":ctx.request_id})), warp::http::StatusCode::UNAUTHORIZED));\n");
    out.push_str("    }\n");
    out.push_str("    if !rate_limiter.allow(&ctx.request_id) {\n");
    out.push_str("        return Ok(warp::reply::with_status(warp::reply::json(&serde_json::json!({\"error\":\"rate_limited\",\"request_id\":ctx.request_id})), warp::http::StatusCode::TOO_MANY_REQUESTS));\n");
    out.push_str("    }\n");
    out.push_str(
        "    tracing::info!(request_id=%ctx.request_id, route=%ctx.route, \"request_start\");\n",
    );
    if has_tables {
        out.push_str("    let conn = &db.conn;\n");
    }

    // Extract params from request JSON
    for param in params {
        out.push_str(&format!(
            "    let {} = request[\"{}\"].clone();\n",
            param.name, param.name
        ));
    }

    let mut has_return = false;
    for stmt in body {
        let mut emitted = crate::emit_expr::emit_stmt_warp(stmt, 1, true, false);
        if emitted.contains("return Ok(warp::reply::json") {
            has_return = true;
            if is_mutation && has_tables {
                emitted = emitted.replace("return Ok(warp::reply::json", "db.subs.notify_all();\n        return Ok(warp::reply::json");
            }
        }
        out.push_str(&emitted);
    }
    if !has_return {
        if is_mutation && has_tables {
            out.push_str("    db.subs.notify_all();\n");
        }
        out.push_str("    Ok(warp::reply::json(&serde_json::Value::Null))\n");
    }
    out.push_str("    tracing::info!(request_id=%ctx.request_id, route=%ctx.route, elapsed_ms=ctx.elapsed_ms(), \"request_end\");\n");
    out.push_str("}\n\n");
    out
}

/// Generate a warp SSE handler for a `@server fn` returning `Stream[T]`.
///
/// Each `emit value` statement in the body maps to a SSE data event.
pub fn emit_sse_handler(
    name: &str,
    params: &[vox_hir::HirParam],
    body: &[vox_hir::HirStmt],
    is_deprecated: bool,
    _is_mutation: bool,
    route_path: &str,
    has_tables: bool,
) -> String {
    let mut out = String::new();
    if is_deprecated {
        out.push_str("#[deprecated]\n");
    }
    out.push_str(&format!("async fn handle_sf_{}(", name));
    if has_tables {
        out.push_str(
            "request: serde_json::Value, api_key: Option<String>, auth_header: Option<String>, request_id: Option<String>, auth_config: Arc<vox_runtime::AuthConfig>, rate_limiter: Arc<vox_runtime::RateLimiter>, db: std::sync::Arc<AppDb>",
        );
    } else {
        out.push_str("request: serde_json::Value, api_key: Option<String>, auth_header: Option<String>, request_id: Option<String>, auth_config: Arc<vox_runtime::AuthConfig>, rate_limiter: Arc<vox_runtime::RateLimiter>");
    }
    out.push_str(") -> Result<impl Reply, Rejection> {\n");
    out.push_str(&format!("    let ctx = vox_runtime::RequestContext::with_request_id(\"{}\", request_id.as_deref());\n", route_path));
    out.push_str("    if !vox_runtime::authorize_request(api_key.as_deref(), auth_header.as_deref(), &auth_config) {\n");
    out.push_str("        return Ok(warp::reply::with_status(warp::reply::json(&serde_json::json!({\"error\":\"unauthorized\",\"request_id\":ctx.request_id})), warp::http::StatusCode::UNAUTHORIZED).into_response());\n");
    out.push_str("    }\n");
    out.push_str("    if !rate_limiter.allow(&ctx.request_id) {\n");
    out.push_str("        return Ok(warp::reply::with_status(warp::reply::json(&serde_json::json!({\"error\":\"rate_limited\",\"request_id\":ctx.request_id})), warp::http::StatusCode::TOO_MANY_REQUESTS).into_response());\n");
    out.push_str("    }\n");
    out.push_str(
        "    tracing::info!(request_id=%ctx.request_id, route=%ctx.route, \"sse_stream_start\");\n",
    );
    if has_tables {
        out.push_str("    let conn = &db.conn;\n");
    }
    for param in params {
        out.push_str(&format!(
            "    let {} = request[\"{}\"].clone();\n",
            param.name, param.name
        ));
    }
    // Channel-based SSE: body emit statements push to the sender; receiver drives the SSE stream.
    out.push_str("    let (mut _emit_tx, mut _emit_rx) = tokio::sync::mpsc::unbounded_channel::<serde_json::Value>();\n");
    out.push_str("    tokio::spawn(async move {\n");
    for stmt in body {
        out.push_str(&crate::emit_expr::emit_stmt(stmt, 2, false, false));
    }
    out.push_str("    });\n");
    out.push_str("    let event_stream = async_stream::stream! {\n");
    out.push_str("        while let Some(val) = _emit_rx.recv().await {\n");
    out.push_str("            let data = serde_json::to_string(&val).unwrap_or_default();\n");
    out.push_str(
        "            yield Ok::<_, warp::Error>(warp::sse::Event::default().data(data));\n",
    );
    out.push_str("        }\n");
    out.push_str("    };\n");
    out.push_str(
        "    Ok(warp::sse::reply(warp::sse::keep_alive().stream(event_stream)).into_response())\n",
    );
    out.push_str("}\n\n");
    out
}

/// Uses Turso: local file (default) or remote when VOX_TURSO_URL and VOX_TURSO_TOKEN are set.
pub fn emit_db_setup(module: &HirModule) -> String {
    let mut out = String::new();
    out.push_str("    // ── Database setup (Turso: local or remote) ──\n");
    out.push_str("    let db = ");
    out.push_str("if let (Ok(url), Ok(token)) = (std::env::var(\"VOX_TURSO_URL\"), std::env::var(\"VOX_TURSO_TOKEN\")) {\n");
    out.push_str("        let database = turso::sync::Builder::new_remote(&url)\n");
    out.push_str("            .with_remote_url(url.clone())\n");
    out.push_str("            .with_auth_token(token)\n");
    out.push_str("            .build()\n");
    out.push_str("            .await\n");
    out.push_str("            .expect(\"Failed to open remote Turso database\");\n");
    out.push_str(
        "        let conn = database.connect().await.expect(\"Failed to connect to remote\");\n",
    );
    out.push_str("        let subs = std::sync::Arc::new(vox_runtime::SubscriptionManager::new());\n");
    out.push_str("        Arc::new(AppDb { _guard: AppDbGuard::Remote(database), conn, subs })\n");
    out.push_str("    } else {\n");
    out.push_str(&format!(
        "        const DEFAULT_DB_PATH: &str = \"{}\";\n",
        defaults::DB_PATH
    ));
    out.push_str(
        "        let db_path = std::env::var(\"VOX_DB_PATH\").unwrap_or_else(|_| DEFAULT_DB_PATH.to_string());\n",
    );
    out.push_str(
        "        let database = turso::Builder::new_local(&db_path).build().await.expect(\"Failed to open Turso database\");\n",
    );
    out.push_str("        let conn = database.connect().expect(\"Failed to connect\");\n");
    out.push_str("        let subs = std::sync::Arc::new(vox_runtime::SubscriptionManager::new());\n");
    out.push_str("        Arc::new(AppDb { _guard: AppDbGuard::Local(database), conn, subs })\n");
    out.push_str("    };\n");

    // Generate SchemaDigest JSON and embed it for runtime migration
    let digest = crate::emit_main::generate_hir_digest(module);
    let digest_json = serde_json::to_string(&digest).unwrap_or_else(|_| "{}".to_string());

    out.push_str(&format!("    let digest_json = r#\"{}\"#;\n", digest_json));
    out.push_str("    let digest: vox_db::SchemaDigest = serde_json::from_str(digest_json).expect(\"parse embedded schema digest\");\n");
    out.push_str("    db.sync_schema(&digest).await.expect(\"auto-migrate database schema\");\n\n");

    out
}

pub fn generate_hir_digest(module: &HirModule) -> SchemaDigest {
    let mut tables = Vec::new();
    let mut collections = Vec::new();
    let mut indexes = Vec::new();

    for t in &module.tables {
        tables.push(TableInfo {
            name: t.name.clone(),
            fields: t.fields.iter().map(|f| {
                let mut type_str = hir_type_to_string(&f.type_ann);
                if let Some(vidx) = module.vector_indexes.iter().find(|v| v.table_name == t.name && v.column == f.name) {
                    type_str = format!("FLOAT32({})", vidx.dimensions);
                }
                FieldInfo {
                    name: f.name.clone(),
                    type_str,
                    is_optional: is_optional_hir_type(&f.type_ann),
                    references_table: detect_hir_table_reference(&f.type_ann, &module.tables),
                }
            }).collect(),
            description: t.description.clone(),
            example_insert: String::new(), // Placeholder, not needed for sync
            example_query: String::new(),
            is_public: t.is_pub,
            auth_provider: None,
            sample_data: Vec::new(),
        });
    }

    for c in &module.collections {
        collections.push(CollectionInfo {
            name: c.name.clone(),
            fields: c.fields.iter().map(|f| FieldInfo {
                name: f.name.clone(),
                type_str: hir_type_to_string(&f.type_ann),
                is_optional: is_optional_hir_type(&f.type_ann),
                references_table: detect_hir_table_reference(&f.type_ann, &module.tables),
            }).collect(),
            description: c.description.clone(),
            is_public: true,
            sample_data: Vec::new(),
        });
    }

    for idx in &module.indexes {
        indexes.push(IndexInfo {
            table_name: idx.table_name.clone(),
            index_name: idx.index_name.clone(),
            kind: IndexKind::Standard,
            columns: idx.columns.clone(),
            dimensions: None,
            filter_fields: Vec::new(),
        });
    }

    for vidx in &module.vector_indexes {
        indexes.push(IndexInfo {
            table_name: vidx.table_name.clone(),
            index_name: vidx.index_name.clone(),
            kind: IndexKind::Vector,
            columns: vec![vidx.column.clone()],
            dimensions: Some(vidx.dimensions),
            filter_fields: vidx.filter_fields.clone(),
        });
    }

    SchemaDigest {
        tables,
        collections,
        relationships: Vec::new(),
        indexes,
        queries: Vec::new(),
        mutations: Vec::new(),
        actions: Vec::new(),
        summary: String::new(),
    }
}

fn hir_type_to_string(ty: &HirType) -> String {
    match ty {
        HirType::Named(n) => n.clone(),
        HirType::Generic(n, args) => {
            let arg_strs: Vec<String> = args.iter().map(hir_type_to_string).collect();
            format!("{}[{}]", n, arg_strs.join(", "))
        }
        HirType::Function(params, ret) => {
            let p_strs: Vec<String> = params.iter().map(hir_type_to_string).collect();
            format!("fn({}) -> {}", p_strs.join(", "), hir_type_to_string(ret))
        }
        HirType::Tuple(els) => {
            let e_strs: Vec<String> = els.iter().map(hir_type_to_string).collect();
            format!("({})", e_strs.join(", "))
        }
        HirType::Union(variants) => {
            let v_strs: Vec<String> = variants.iter().map(hir_type_to_string).collect();
            v_strs.join(" | ")
        }
        HirType::Map(k, v) => format!("map[{}, {}]", hir_type_to_string(k), hir_type_to_string(v)),
        HirType::Set(v) => format!("set[{}]", hir_type_to_string(v)),
        HirType::Boxed(v) => format!("boxed {}", hir_type_to_string(v)),
        HirType::Intersection(a, b) => {
            format!("{} & {}", hir_type_to_string(a), hir_type_to_string(b))
        }
        HirType::Unit => "()".to_string(),
    }
}

fn is_optional_hir_type(ty: &HirType) -> bool {
    matches!(ty, HirType::Generic(n, _) if n == "Option")
}

fn detect_hir_table_reference(ty: &HirType, tables: &[vox_hir::HirTable]) -> Option<String> {
    match ty {
        HirType::Generic(n, args) if n == "Id" => {
            if let Some(HirType::Named(table)) = args.first() {
                if tables.iter().any(|t| t.name == *table) {
                    return Some(table.clone());
                }
            }
            None
        }
        HirType::Generic(n, args) if n == "Option" || n == "List" || n == "list" => {
            args.first().and_then(|inner| detect_hir_table_reference(inner, tables))
        }
        _ => None,
    }
}

/// Generate the MCP (Model Context Protocol) JSON-RPC server binary.
/// Communicates over stdio: reads JSON-RPC requests from stdin, writes responses to stdout.
pub fn emit_mcp_server(module: &HirModule, package_name: &str) -> String {
    let crate_name = package_name.replace('-', "_");
    let mut out = String::new();

    out.push_str("// MCP Server — Generated by Vox Compiler\n");
    out.push_str("// Implements the Model Context Protocol (JSON-RPC 2.0 over stdio)\n\n");
    out.push_str("use serde_json::{json, Value};\n");
    out.push_str("use std::io::{self, BufRead, Write};\n");
    out.push_str(&format!("use {}::*;\n\n", crate_name));

    // Tool dispatch function
    out.push_str("fn dispatch_tool(name: &str, args: &Value) -> Result<Value, String> {\n");
    out.push_str("    match name {\n");
    for tool in &module.mcp_tools {
        let fn_name = &tool.func.name;
        out.push_str(&format!("        \"{}\" => {{\n", fn_name));
        // Extract args
        for param in &tool.func.params {
            let p = &param.name;
            out.push_str(&format!(
                "            let {p} = args.get(\"{p}\").cloned().unwrap_or(Value::Null);\n"
            ));
        }
        // Call function
        let arg_list: Vec<String> = tool
            .func
            .params
            .iter()
            .map(|p| {
                let name = &p.name;
                match p.type_ann.as_ref() {
                    Some(HirType::Named(t)) if t == "String" || t == "str" => {
                        format!("{name}.as_str().unwrap_or_default().to_string()")
                    }
                    Some(HirType::Named(t)) if t == "i64" || t == "int" => {
                        format!("{name}.as_i64().unwrap_or(0)")
                    }
                    Some(HirType::Named(t)) if t == "f64" || t == "float" => {
                        format!("{name}.as_f64().unwrap_or(0.0)")
                    }
                    Some(HirType::Named(t)) if t == "bool" => {
                        format!("{name}.as_bool().unwrap_or(false)")
                    }
                    _ => name.to_string(),
                }
            })
            .collect();
        out.push_str(&format!(
            "            let result = {}({});\n",
            fn_name,
            arg_list.join(", ")
        ));
        out.push_str("            Ok(serde_json::to_value(result).unwrap_or(Value::Null))\n");
        out.push_str("        }\n");
    }
    // ── @skill fn dispatch ─────────────────────────────────────────────────
    for skill in &module.skills {
        let fn_name = &skill.func.name;
        out.push_str(&format!("        \"{}\" => {{\n", fn_name));
        for param in &skill.func.params {
            let p = &param.name;
            out.push_str(&format!(
                "            let {p} = args.get(\"{p}\").cloned().unwrap_or(Value::Null);\n"
            ));
        }
        let arg_list: Vec<String> = skill.func.params.iter().map(|p| p.name.clone()).collect();
        out.push_str(&format!(
            "            let result = {}({});\n",
            fn_name,
            arg_list.join(", ")
        ));
        out.push_str("            Ok(serde_json::to_value(result).unwrap_or(Value::Null))\n");
        out.push_str("        }\n");
    }

    // ── @agent_def fn dispatch (prefixed agent_) ───────────────────────────
    for agent in &module.agents {
        let tool_name = format!("agent_{}", agent.func.name.to_lowercase());
        out.push_str(&format!("        \"{}\" => {{\n", tool_name));
        out.push_str("            let query = args.get(\"query\").and_then(|v| v.as_str()).unwrap_or(\"\").to_string();\n");
        out.push_str(&format!(
            "            Ok(serde_json::json!({{\"agent\": \"{}\", \"query\": query, \"status\": \"queued\"}}))\n",
            agent.func.name
        ));
        out.push_str("        }\n");
    }

    out.push_str("        _ => Err(format!(\"Unknown tool: {}\", name)),\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    // Build tool list JSON — includes @mcp.tool + @skill + @agent_def
    out.push_str("fn tool_list() -> Value {\n");
    out.push_str("    let mut tools: Vec<Value> = Vec::new();\n");

    // @mcp.tool entries
    for tool in &module.mcp_tools {
        let props: String = tool
            .func
            .params
            .iter()
            .map(|param| {
                let json_type = match param.type_ann.as_ref() {
                    Some(HirType::Named(t)) if t == "String" || t == "str" => "string",
                    Some(HirType::Named(t)) if t == "i64" || t == "int" => "integer",
                    Some(HirType::Named(t)) if t == "f64" || t == "float" => "number",
                    Some(HirType::Named(t)) if t == "bool" => "boolean",
                    _ => "string",
                };
                format!("(\"{}\", \"{}\")", param.name, json_type)
            })
            .collect::<Vec<_>>()
            .join(", ");
        let required: String = tool
            .func
            .params
            .iter()
            .map(|p| format!("\"{}\"", p.name))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!(
            "    tools.push(serde_json::json!({{\"name\":\"{name}\",\"description\":\"{desc}\",\"inputSchema\":{{\"type\":\"object\",\"properties\":{{ {props_code} }},\"required\":[{required}]}}}});\n",
            name = tool.func.name,
            desc = tool.description.replace('"', "\\\""),
            props_code = tool.func.params.iter().map(|param| {
                let json_type = match param.type_ann.as_ref() {
                    Some(HirType::Named(t)) if t == "String" || t == "str" => "string",
                    Some(HirType::Named(t)) if t == "i64" || t == "int" => "integer",
                    Some(HirType::Named(t)) if t == "f64" || t == "float" => "number",
                    Some(HirType::Named(t)) if t == "bool" => "boolean",
                    _ => "string",
                };
                format!("\"{}\":{{\"type\":\"{}\"}}", param.name, json_type)
            }).collect::<Vec<_>>().join(","),
            required = required,
        ));
        let _ = props; // suppress unused
    }

    // @skill fn entries
    for skill in &module.skills {
        let fn_name = &skill.func.name;
        let props = skill
            .func
            .params
            .iter()
            .map(|param| {
                let json_type = match param.type_ann.as_ref() {
                    Some(HirType::Named(t)) if t == "String" || t == "str" => "string",
                    Some(HirType::Named(t)) if t == "i64" || t == "int" => "integer",
                    Some(HirType::Named(t)) if t == "f64" || t == "float" => "number",
                    Some(HirType::Named(t)) if t == "bool" => "boolean",
                    _ => "string",
                };
                format!("\"{}\":{{\"type\":\"{}\"}}", param.name, json_type)
            })
            .collect::<Vec<_>>()
            .join(",");
        let required: String = skill
            .func
            .params
            .iter()
            .map(|p| format!("\"{}\"", p.name))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!(
            "    tools.push(serde_json::json!({{\"name\":\"{fn_name}\",\"description\":\"Skill: {fn_name}\",\"inputSchema\":{{\"type\":\"object\",\"properties\":{{ {props} }},\"required\":[{required}]}}}}));\n",
            fn_name = fn_name,
            props = props,
            required = required,
        ));
    }

    // @agent_def fn entries (tool name: agent_<name>)
    for agent in &module.agents {
        let tool_name = format!("agent_{}", agent.func.name.to_lowercase());
        out.push_str(&format!(
            "    tools.push(serde_json::json!({{\"name\":\"{tool_name}\",\"description\":\"Agent: {agent_name}\",\"inputSchema\":{{\"type\":\"object\",\"properties\":{{\"query\":{{\"type\":\"string\"}}}},\"required\":[\"query\"]}}}}));\n",
            tool_name = tool_name,
            agent_name = agent.func.name,
        ));
    }

    out.push_str("    serde_json::json!({\"tools\": tools})\n");
    out.push_str("}\n\n");

    // Main loop — JSON-RPC over stdio
    out.push_str("fn main() {\n");
    out.push_str("    let stdin = io::stdin();\n");
    out.push_str("    let mut stdout = io::stdout();\n");
    out.push_str("    for line in stdin.lock().lines() {\n");
    out.push_str("        let line = match line {\n");
    out.push_str("            Ok(l) => l,\n");
    out.push_str("            Err(_) => break,\n");
    out.push_str("        };\n");
    out.push_str("        if line.trim().is_empty() { continue; }\n");
    out.push_str("        let request: Value = match serde_json::from_str(&line) {\n");
    out.push_str("            Ok(v) => v,\n");
    out.push_str("            Err(e) => {\n");
    out.push_str("                let err = json!({\n");
    out.push_str("                    \"jsonrpc\": \"2.0\",\n");
    out.push_str("                    \"error\": { \"code\": -32700, \"message\": format!(\"Parse error: {e}\") },\n");
    out.push_str("                    \"id\": null\n");
    out.push_str("                });\n");
    out.push_str("                writeln!(stdout, \"{}\", err).ok();\n");
    out.push_str("                stdout.flush().ok();\n");
    out.push_str("                continue;\n");
    out.push_str("            }\n");
    out.push_str("        };\n");
    out.push_str("        let id = request.get(\"id\").cloned().unwrap_or(Value::Null);\n");
    out.push_str(
        "        let method = request.get(\"method\").and_then(|m| m.as_str()).unwrap_or(\"\");\n",
    );
    out.push_str("        let params = request.get(\"params\").cloned().unwrap_or(json!({}));\n\n");

    out.push_str("        let response = match method {\n");
    out.push_str("            \"initialize\" => {\n");
    out.push_str("                let pv = params.get(\"protocolVersion\").and_then(|v| v.as_str()).unwrap_or(\"2024-11-05\");\n");
    out.push_str("                json!({\n");
    out.push_str("                \"jsonrpc\": \"2.0\",\n");
    out.push_str("                \"id\": id,\n");
    out.push_str("                \"result\": {\n");
    out.push_str("                    \"protocolVersion\": pv,\n");
    out.push_str("                    \"capabilities\": { \"tools\": {} },\n");
    out.push_str(&format!(
        "                    \"serverInfo\": {{ \"name\": \"{}\", \"version\": \"0.1.0\" }}\n",
        package_name
    ));
    out.push_str("                }\n");
    out.push_str("            })\n");
    out.push_str("            },\n");
    out.push_str("            \"tools/list\" => {\n");
    out.push_str("                let tools = tool_list();\n");
    out.push_str("                json!({\n");
    out.push_str("                    \"jsonrpc\": \"2.0\",\n");
    out.push_str("                    \"id\": id,\n");
    out.push_str("                    \"result\": tools\n");
    out.push_str("                })\n");
    out.push_str("            }\n");
    out.push_str("            \"tools/call\" => {\n");
    out.push_str("                let tool_name = params.get(\"name\").and_then(|n| n.as_str()).unwrap_or(\"\");\n");
    out.push_str("                let tool_args = params.get(\"arguments\").cloned().unwrap_or(json!({}));\n");
    out.push_str("                match dispatch_tool(tool_name, &tool_args) {\n");
    out.push_str("                    Ok(result) => json!({\n");
    out.push_str("                        \"jsonrpc\": \"2.0\",\n");
    out.push_str("                        \"id\": id,\n");
    out.push_str("                        \"result\": {\n");
    out.push_str("                            \"content\": [{ \"type\": \"text\", \"text\": serde_json::to_string(&result).unwrap_or_default() }]\n");
    out.push_str("                        }\n");
    out.push_str("                    }),\n");
    out.push_str("                    Err(e) => json!({\n");
    out.push_str("                        \"jsonrpc\": \"2.0\",\n");
    out.push_str("                        \"id\": id,\n");
    out.push_str("                        \"result\": {\n");
    out.push_str("                            \"isError\": true,\n");
    out.push_str(
        "                            \"content\": [{ \"type\": \"text\", \"text\": e }]\n",
    );
    out.push_str("                        }\n");
    out.push_str("                    }),\n");
    out.push_str("                }\n");
    out.push_str("            }\n");
    out.push_str(
        "            \"notifications/initialized\" | \"notifications/cancelled\" => continue,\n",
    );
    out.push_str("            _ => json!({\n");
    out.push_str("                \"jsonrpc\": \"2.0\",\n");
    out.push_str("                \"id\": id,\n");
    out.push_str("                \"error\": { \"code\": -32601, \"message\": format!(\"Method not found: {}\", method) }\n");
    out.push_str("            }),\n");
    out.push_str("        };\n\n");

    out.push_str("        writeln!(stdout, \"{}\", response).ok();\n");
    out.push_str("        stdout.flush().ok();\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    out
}
