//! Generate GUI settings surfaces from vox_config::config_registry::CONFIG_KEYS.
//!
//! `vox ci config-gui-codegen` renders a `generatedSettingsIndex.ts` so the GUI
//! settings search index is a VIEW over the registry SSOT (no hand-maintained
//! drift). `--check` is the drift gate: fail if the on-disk file differs.

use std::path::Path;

use vox_config::config_key::{ConfigKey, Group};
use vox_config::config_registry::CONFIG_KEYS;
use vox_config::operator_registry::ConfigClass;

/// Output path for the generated TS module, relative to repo-root current_dir.
const OUT_REL_PATH: &str = "crates/vox-gui/ui/src/config/generatedSettingsIndex.ts";

/// True if this knob is operator-facing and should appear in the GUI.
pub fn is_surfaced(k: &ConfigKey) -> bool {
    k.gui.is_some() || k.class == ConfigClass::UserPreference
}

/// The GUI section id for a knob (explicit gui section, else derived from group).
pub fn section_of(k: &ConfigKey) -> String {
    if let Some(g) = k.gui {
        return g.section.to_string();
    }
    match k.group {
        Group::Tuning => "tuning",
        Group::Mesh => "mesh",
        Group::Runtime => "runtime",
        Group::ModelsAndEndpoints => "models",
        Group::Orchestrator => "orchestrator",
        Group::Storage => "storage",
        Group::Security => "security",
        Group::Telemetry => "telemetry",
        Group::Training => "training",
        Group::General => "general",
    }
    .to_string()
}

/// Derive a stable kebab id from the key: strip VOX_ prefix, lowercase, _ -> -.
pub fn id_of(key: &str) -> String {
    key.strip_prefix("VOX_")
        .unwrap_or(key)
        .to_lowercase()
        .replace('_', "-")
}

/// Search keywords from the key tokens (lowercased, VOX dropped).
pub fn keywords_of(key: &str) -> Vec<String> {
    key.strip_prefix("VOX_")
        .unwrap_or(key)
        .to_lowercase()
        .split('_')
        .filter(|s| !s.is_empty())
        .map(|s| s.to_string())
        .collect()
}

/// Render the generated TS search-index module from surfaced keys (sorted by section,id).
pub fn render_generated_index_ts(keys: &[ConfigKey]) -> String {
    let mut rows: Vec<(String, String, String, String, Vec<String>)> = keys
        .iter()
        .filter(|k| is_surfaced(k))
        .map(|k| {
            (
                id_of(k.key),
                section_of(k),
                k.label.to_string(),
                k.hint.to_string(),
                keywords_of(k.key),
            )
        })
        .collect();
    rows.sort_by(|a, b| (&a.1, &a.0).cmp(&(&b.1, &b.0)));
    let mut body = String::new();
    for (id, section, label, hint, kw) in rows {
        let kw_ts = kw
            .iter()
            .map(|k| format!("{k:?}"))
            .collect::<Vec<_>>()
            .join(", ");
        body.push_str(&format!(
            "  {{ id: {id:?}, section: {section:?}, label: {label:?}, hint: {hint:?}, keywords: [{kw_ts}] }},\n"
        ));
    }
    format!(
        "// @generated by `vox ci config-gui-codegen` from CONFIG_KEYS — DO NOT EDIT.\n\
         import type {{ SettingEntry }} from '../components/surfaces/Settings/settingsIndex';\n\
         export const GENERATED_SETTINGS_INDEX: SettingEntry[] = [\n{body}];\n"
    )
}

/// Run the generator. `check=true` is the drift gate (compare, do not write).
pub fn run(check: bool) -> anyhow::Result<()> {
    let root = std::env::current_dir()?;
    let rendered = render_generated_index_ts(CONFIG_KEYS);
    let path: &Path = &root.join(OUT_REL_PATH);

    if check {
        let on_disk = std::fs::read_to_string(path).map_err(|e| {
            anyhow::anyhow!(
                "config-gui-codegen --check: cannot read {OUT_REL_PATH}: {e}. \
                 Run `vox ci config-gui-codegen` to generate it."
            )
        })?;
        if on_disk != rendered {
            anyhow::bail!(
                "config-gui-codegen drift: {OUT_REL_PATH} is stale. \
                 Regenerate with `vox ci config-gui-codegen` and commit."
            );
        }
        println!("config-gui-codegen OK: {OUT_REL_PATH} matches CONFIG_KEYS.");
        return Ok(());
    }

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, &rendered)?;
    let rows = rendered.matches("  { id:").count();
    println!("config-gui-codegen: wrote {rows} entry(ies) to {OUT_REL_PATH}");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use vox_config::config_registry::CONFIG_KEYS;
    #[test]
    fn id_and_keywords_derive_from_key() {
        assert_eq!(id_of("VOX_SEARCH_BM25_K1"), "search-bm25-k1");
        assert_eq!(
            keywords_of("VOX_SEARCH_BM25_K1"),
            vec!["search", "bm25", "k1"]
        );
    }
    #[test]
    fn renders_surfaced_keys_with_header() {
        let ts = render_generated_index_ts(CONFIG_KEYS);
        assert!(ts.contains("@generated"));
        assert!(ts.contains("GENERATED_SETTINGS_INDEX"));
        // at least one UserPreference SEARCH row surfaces:
        assert!(ts.contains("search-"));
    }
}
