use anyhow::{Context, Result};
use std::fs;
use std::path::{Path, PathBuf};

/// Resolve the git hooks directory for `root`, working in both ordinary clones and
/// **worktrees** (where `.git` is a file pointing at `…/.git/worktrees/<name>`, so the old
/// `root.join(".git/hooks")` + `is_dir()` check silently skipped — exactly where Claude
/// agents run). `git rev-parse --git-path hooks` returns the correct hooks dir for either
/// layout and also honors `core.hooksPath`. Falls back to `<root>/.git/hooks` if git is
/// unavailable.
fn resolve_hooks_dir(root: &Path) -> Option<PathBuf> {
    // Route through vox_git so the concurrency policy is honored (arch-check
    // forbids raw `Command::new("git")`). This is a read-only query.
    let rel = vox_git::read_only(root, &["rev-parse", "--git-path", "hooks"]).ok()?;
    let rel = rel.trim();
    if rel.is_empty() {
        return None;
    }
    let p = Path::new(rel);
    Some(if p.is_absolute() {
        p.to_path_buf()
    } else {
        root.join(p)
    })
}

const PRE_COMMIT_HOOK: &str = r#"#!/usr/bin/env bash
# File: .git/hooks/pre-commit
# Automatically generated by `vox ci install-hooks`

echo "🦶 Running VoxCI line-endings check..."

# Prefer a prebuilt vox binary so a trivial CRLF check does NOT trigger a full
# `cargo run -p vox-cli` rebuild on every commit. On this 100+-crate workspace
# that rebuild dominated commit latency (1-2 min/commit). Freshness is irrelevant
# for a line-endings check, so skip the staleness guard on this fast path. Fall
# back to `cargo run` only when no prebuilt binary is present.
VOX_BIN=""
for cand in \
  "./target/debug/vox" "./target/debug/vox.exe" \
  "./target/release/vox" "./target/release/vox.exe" \
  "$HOME/.vox/bin/vox" "$HOME/.vox/bin/vox.exe"; do
  if [ -x "$cand" ]; then VOX_BIN="$cand"; break; fi
done

if [ -n "$VOX_BIN" ]; then
  VOX_SKIP_FRESHNESS_CHECK=1 "$VOX_BIN" ci line-endings --autofix
else
  cargo run -q -p vox-cli -- ci line-endings --autofix
fi

if [ $? -ne 0 ]; then
    echo "❌ Commit aborted: CRLF line-endings detected. Run the formatter or fix them in your IDE, then git add again."
    exit 1
fi

echo "✅ Line endings OK."
exit 0
"#;

const PRE_PUSH_HOOK: &str = r#"#!/usr/bin/env bash
# File: .git/hooks/pre-push
# Generated by `vox ci install-hooks`. Do not edit; regenerate via the command.
# Body delegates to `vox ci pre-push` per AGENTS.md VoxScript-First Glue Code.
#
# Windows binary-lock resilience (os error 5 on relink):
#  1. `cargo build` relinks target/debug/vox(.exe). If a stale/parallel vox
#     process holds it, the relink is denied. We copy the (still readable) vox
#     to a reaper sidecar, run `ci free-binary --apply` to kill ONLY stale vox
#     procs holding THIS worktree's target, then retry the build once.
#  2. We run the gates from a SIDECAR COPY (vox-prepush) so this push never
#     itself locks the canonical vox.exe for the next push.
set -u
EXE=""
case "$(uname -s 2>/dev/null)" in MINGW*|MSYS*|CYGWIN*) EXE=".exe";; esac
VOX="./target/debug/vox${EXE}"

reap() {
  # Copy is allowed even while the target is locked (read share); the copy then
  # kills the stale lockers. A stable ~/.vox/bin/vox is preferred if present.
  local reaper="./target/debug/vox-reaper${EXE}"
  if [ -x "$HOME/.vox/bin/vox${EXE}" ]; then
    "$HOME/.vox/bin/vox${EXE}" ci free-binary --target ./target --apply || true
  elif [ -f "$VOX" ]; then
    cp -f "$VOX" "$reaper" 2>/dev/null && "$reaper" ci free-binary --target ./target --apply || true
  fi
}

if ! cargo build -q -p vox-cli; then
  echo "pre-push: build failed (possible vox.exe lock) — reaping stale vox procs and retrying"
  reap
  cargo build -q -p vox-cli || { echo "pre-push: build still failing after reap"; exit 1; }
fi

# Run gates from a sidecar copy so the canonical vox.exe stays free to relink.
SIDE="./target/debug/vox-prepush${EXE}"
cp -f "$VOX" "$SIDE" 2>/dev/null || SIDE="$VOX"
exec "$SIDE" ci pre-push
"#;

pub fn run(root: &Path) -> Result<()> {
    // Resolve the hooks dir via git so worktrees (where `.git` is a file) install correctly.
    let hooks_dir = match resolve_hooks_dir(root) {
        Some(d) => d,
        None => {
            // Just print a warning, no need to fail the CI step if someone isn't in a git clone.
            println!(
                "Skipping hook installation: {} is not inside a git repository",
                root.display()
            );
            return Ok(());
        }
    };

    if !hooks_dir.exists() {
        fs::create_dir_all(&hooks_dir)
            .with_context(|| format!("create {}", hooks_dir.display()))?;
    }

    let pre_commit_path = hooks_dir.join("pre-commit");

    fs::write(&pre_commit_path, PRE_COMMIT_HOOK)
        .with_context(|| format!("write {}", pre_commit_path.display()))?;

    // Make the hook executable on Unix systems
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        if let Ok(mut perms) = fs::metadata(&pre_commit_path).map(|m| m.permissions()) {
            perms.set_mode(0o755);
            let _ = fs::set_permissions(&pre_commit_path, perms);
        }
    }

    println!(
        "✅ Installed Git pre-commit line-endings hook to {}",
        pre_commit_path.display()
    );

    let pre_push_path = hooks_dir.join("pre-push");
    fs::write(&pre_push_path, PRE_PUSH_HOOK)
        .with_context(|| format!("write {}", pre_push_path.display()))?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        if let Ok(mut perms) = fs::metadata(&pre_push_path).map(|m| m.permissions()) {
            perms.set_mode(0o755);
            let _ = fs::set_permissions(&pre_push_path, perms);
        }
    }

    println!(
        "✅ Installed Git pre-push hook to {}",
        pre_push_path.display()
    );

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::PRE_PUSH_HOOK;

    #[test]
    fn pre_push_hook_is_lock_resilient() {
        // The hook must build from source (not cargo run which also tries to relink
        // while already running), reap stale lockers via a copy, and run gates from
        // a sidecar copy so consecutive pushes don't lock each other.
        assert!(PRE_PUSH_HOOK.contains("cargo build -q -p vox-cli"),
            "hook must use cargo build (not cargo run) to get the fresh binary path");
        assert!(PRE_PUSH_HOOK.contains("ci free-binary"),
            "hook must call free-binary to reap stale lockers");
        assert!(PRE_PUSH_HOOK.contains("--apply"),
            "hook must pass --apply to actually kill stale procs");
        assert!(PRE_PUSH_HOOK.contains("vox-prepush"),
            "hook must run gates from a sidecar copy (vox-prepush)");
        assert!(PRE_PUSH_HOOK.contains("ci pre-push"),
            "hook must invoke ci pre-push subcommand");
        // Must NOT use the old self-locking form.
        assert!(!PRE_PUSH_HOOK.contains("cargo run -q -p vox-cli -- ci pre-push"),
            "hook must NOT use 'cargo run' to invoke pre-push (causes self-lock)");
    }
}
