//! `vox ci plugin-surface-sync [--write]`
//!
//! Single source of truth for the **plugin extension-point surface**. The traits in
//! `crates/vox-plugin-api/src/extensions/*.rs` (each a `#[sabi_trait]` with a
//! `*_REVISION` constant) are the SSOT; this command extracts them into
//! `contracts/plugin/extension-points.v1.yaml` and, in verify mode (the default), fails
//! when the committed file drifts from the traits.
//!
//! It also runs the **sdk-abi-parity** invariant: every extension module must have a
//! matching `as_<module>()` accessor on the `VoxPlugin` trait in `abi.rs`, and vice
//! versa — so a new extension point can't be added without wiring its accessor (or an
//! accessor left dangling after a trait is removed).

use anyhow::{Context, Result, anyhow, bail};
use regex::Regex;
use serde::Serialize;
use std::path::Path;

const GENERATED_HEADER: &str = "\
# @generated by `vox ci plugin-surface-sync --write`
# Source of truth: crates/vox-plugin-api/src/extensions/*.rs (+ the VoxPlugin accessors
# in crates/vox-plugin-api/src/abi.rs). Do NOT hand-edit — regenerate instead.
";

const REL_OUTPUT: &str = "contracts/plugin/extension-points.v1.yaml";
const REL_EXTENSIONS: &str = "crates/vox-plugin-api/src/extensions";
const REL_ABI: &str = "crates/vox-plugin-api/src/abi.rs";

#[derive(Serialize)]
struct Surface {
    schema_version: u32,
    /// Mirrors `vox_plugin_api::VOX_PLUGIN_ABI_VERSION` at generation time.
    abi_version: u32,
    extension_points: Vec<ExtPoint>,
}

#[derive(Serialize)]
struct ExtPoint {
    /// PascalCase trait name (matches the `Plugin.toml` `provides.extension-points` vocab).
    name: String,
    /// snake_case module file stem.
    module: String,
    /// The trait's `*_REVISION` constant.
    revision: u32,
    /// The `VoxPlugin` accessor that surfaces this extension (`as_<module>`).
    accessor: String,
    /// Sorted method names declared on the trait (includes the defaulted `revision`).
    methods: Vec<String>,
}

/// Parse every extension module and the VoxPlugin accessor set, cross-check parity, and
/// return the canonical surface.
fn extract_surface(repo_root: &Path) -> Result<Surface> {
    let trait_re = Regex::new(r"(?m)^pub trait\s+(\w+)").expect("trait regex");
    let rev_re =
        Regex::new(r"(?m)^pub const\s+\w+_REVISION:\s*u32\s*=\s*(\d+)\s*;").expect("rev regex");
    let fn_re = Regex::new(r"(?m)^\s*fn\s+(\w+)\s*[(<]").expect("fn regex");

    let ext_dir = repo_root.join(REL_EXTENSIONS);
    let mut files: Vec<std::path::PathBuf> = std::fs::read_dir(&ext_dir)
        .with_context(|| format!("read_dir {}", ext_dir.display()))?
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| {
            p.extension().and_then(|x| x.to_str()) == Some("rs")
                && p.file_stem().and_then(|s| s.to_str()) != Some("mod")
        })
        .collect();
    files.sort();

    let mut points: Vec<ExtPoint> = Vec::new();
    for path in &files {
        let module = path
            .file_stem()
            .and_then(|s| s.to_str())
            .ok_or_else(|| anyhow!("bad file stem: {}", path.display()))?
            .to_string();
        let src =
            std::fs::read_to_string(path).with_context(|| format!("read {}", path.display()))?;
        let name = trait_re
            .captures(&src)
            .and_then(|c| c.get(1))
            .map(|m| m.as_str().to_string())
            .ok_or_else(|| anyhow!("{}: no `pub trait` found", path.display()))?;
        let revision: u32 = rev_re
            .captures(&src)
            .and_then(|c| c.get(1))
            .ok_or_else(|| anyhow!("{}: no `*_REVISION: u32 = N;` constant", path.display()))?
            .as_str()
            .parse()
            .with_context(|| format!("{}: REVISION not a u32", path.display()))?;
        let mut methods: Vec<String> = fn_re
            .captures_iter(&src)
            .filter_map(|c| c.get(1).map(|m| m.as_str().to_string()))
            .collect();
        methods.sort();
        methods.dedup();
        points.push(ExtPoint {
            accessor: format!("as_{module}"),
            name,
            module,
            revision,
            methods,
        });
    }
    points.sort_by(|a, b| a.name.cmp(&b.name));

    check_accessor_parity(repo_root, &points)?;

    Ok(Surface {
        schema_version: 1,
        abi_version: vox_plugin_api::VOX_PLUGIN_ABI_VERSION,
        extension_points: points,
    })
}

/// sdk-abi-parity: the set of `as_<module>` accessors on `VoxPlugin` must exactly equal the
/// set of extension modules. Catches an extension added without an accessor (unreachable by
/// the host) or an accessor left behind after a trait was removed.
fn check_accessor_parity(repo_root: &Path, points: &[ExtPoint]) -> Result<()> {
    let abi_src = std::fs::read_to_string(repo_root.join(REL_ABI))
        .with_context(|| format!("read {REL_ABI}"))?;
    let acc_re = Regex::new(r"(?m)fn\s+as_(\w+)\s*\(").expect("accessor regex");
    let mut accessors: Vec<String> = acc_re
        .captures_iter(&abi_src)
        .filter_map(|c| c.get(1).map(|m| m.as_str().to_string()))
        .collect();
    accessors.sort();
    accessors.dedup();

    let mut modules: Vec<String> = points.iter().map(|p| p.module.clone()).collect();
    modules.sort();

    let missing_accessor: Vec<&String> =
        modules.iter().filter(|m| !accessors.contains(m)).collect();
    let dangling_accessor: Vec<&String> =
        accessors.iter().filter(|a| !modules.contains(a)).collect();

    if !missing_accessor.is_empty() || !dangling_accessor.is_empty() {
        let mut msg =
            String::from("sdk-abi-parity: VoxPlugin accessors vs extension modules mismatch.\n");
        if !missing_accessor.is_empty() {
            msg.push_str(&format!(
                "  extension modules with no `as_<module>()` accessor in abi.rs: {missing_accessor:?}\n"
            ));
        }
        if !dangling_accessor.is_empty() {
            msg.push_str(&format!(
                "  `as_*` accessors with no matching extension module: {dangling_accessor:?}\n"
            ));
        }
        bail!(msg);
    }
    Ok(())
}

fn render(surface: &Surface) -> Result<String> {
    let body = serde_yaml::to_string(surface).context("serialize surface to yaml")?;
    Ok(format!("{GENERATED_HEADER}{body}"))
}

/// Run the gate. `write` regenerates the committed file; otherwise verify it matches.
pub fn run(repo_root: &Path, write: bool) -> Result<()> {
    let surface = extract_surface(repo_root)?;
    let rendered = render(&surface)?;
    let out_path = repo_root.join(REL_OUTPUT);

    if write {
        if let Some(parent) = out_path.parent() {
            std::fs::create_dir_all(parent)
                .with_context(|| format!("create {}", parent.display()))?;
        }
        std::fs::write(&out_path, &rendered)
            .with_context(|| format!("write {}", out_path.display()))?;
        println!(
            "plugin-surface-sync: wrote {REL_OUTPUT} ({} extension point(s))",
            surface.extension_points.len()
        );
        return Ok(());
    }

    let on_disk = std::fs::read_to_string(&out_path).unwrap_or_default();
    // Compare LF-normalized so Windows checkouts don't trip the gate.
    if normalize(&on_disk) != normalize(&rendered) {
        bail!(
            "{REL_OUTPUT} is stale (or missing); run `vox ci plugin-surface-sync --write` from the repo root"
        );
    }
    println!(
        "plugin-surface-sync OK ({} extension point(s); accessor parity clean)",
        surface.extension_points.len()
    );
    Ok(())
}

fn normalize(s: &str) -> String {
    s.replace("\r\n", "\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn repo_root() -> std::path::PathBuf {
        std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .ancestors()
            .nth(2)
            .expect("repo root")
            .to_path_buf()
    }

    #[test]
    fn surface_extracts_all_modules_with_matching_accessors() {
        let surface = extract_surface(&repo_root()).expect("extract");
        // Every module ↔ as_<module> accessor pairing held (else extract_surface errors).
        assert!(
            surface.extension_points.len() >= 12,
            "expected the 12 shipped extension points, got {}",
            surface.extension_points.len()
        );
        let hw = surface
            .extension_points
            .iter()
            .find(|p| p.module == "hardware_probe")
            .expect("hardware_probe present");
        assert_eq!(hw.name, "HardwareProbe");
        assert_eq!(hw.accessor, "as_hardware_probe");
        assert!(hw.methods.contains(&"probe_summary_json".to_string()));
    }

    #[test]
    fn committed_surface_is_in_sync() {
        // The verify path must pass against the committed YAML (keeps CI honest locally).
        run(&repo_root(), false).expect("committed extension-points.v1.yaml is in sync");
    }
}
