//! Bootstrap generator + drift gate for the unified policy registry.
//! Phase 1a wires the `code-audit-rule` domain; later plans add other domains.
//!
//! The `code-audit-rule` enumeration depends on the optional `vox-code-audit`
//! crate, exposed via the `completion-toestub` feature (which CI enables). When
//! that feature is off the generator/parity commands return an actionable error
//! rather than a partial catalog, mirroring `completion_quality::append_toestub_findings`.

use std::path::Path;

#[cfg(feature = "completion-toestub")]
use vox_config::{PolicyDomain, PolicyEntry, PolicySeverity, PolicySource, PolicySourceKind};

#[cfg(feature = "completion-toestub")]
fn map_severity(s: vox_code_audit::rules::Severity) -> PolicySeverity {
    use vox_code_audit::rules::Severity as S;
    match s {
        S::Info => PolicySeverity::Info,
        S::Warning => PolicySeverity::Warn,
        S::Error => PolicySeverity::Error,
        S::Critical => PolicySeverity::Critical,
    }
}

/// Derive a human group label from a `code-audit/<a>/<b>` id.
#[cfg(feature = "completion-toestub")]
fn group_for(id: &str) -> String {
    let body = id.strip_prefix("code-audit/").unwrap_or(id);
    let head = body.split('/').next().unwrap_or(body);
    let label = match head {
        "stub" => "Stubs (TOESTUB)",
        "victory-claim" => "Victory claims",
        "ai-laziness" => "AI-laziness",
        "secrets" | "crypto_ban" | "env_secret_shape" | "llm_provider_call" => "Security",
        "scaling" => "Scaling",
        _ => "General",
    };
    format!("Language rules / {label}")
}

/// Enumerate every live detector into a registry entry.
#[cfg(feature = "completion-toestub")]
pub fn code_audit_entries() -> Vec<PolicyEntry> {
    let mut out: Vec<PolicyEntry> = vox_code_audit::detectors::all_rules(None)
        .iter()
        .map(|rule| {
            let raw_id = rule.id();
            let id = format!("code-audit/{raw_id}");
            let sev = map_severity(rule.severity());
            let blocking = matches!(sev, PolicySeverity::Error | PolicySeverity::Critical);
            PolicyEntry {
                id: id.clone(),
                domain: PolicyDomain::CodeAuditRule,
                title: rule.name().to_string(),
                group: group_for(&id),
                description: rule.description().to_string(),
                severity: Some(sev),
                blocking,
                runs_on: vec!["pre-commit".into(), "pre-push".into(), "ci".into()],
                source: PolicySource {
                    kind: PolicySourceKind::Pattern,
                    reference: format!("contracts/code-audit/rules.v1.yaml#{raw_id}"),
                    detail: rule.minimal_repro().map(|s| s.to_string()),
                },
                docs: None,
                default_enabled: true,
                // Stub + security rules are policy-protected (cannot be disabled in Phase 2).
                // Real detector ids use `arch/stub` and `vox/llm/direct-provider-call`
                // (verified against `vox_code_audit::detectors::all_rules`), not the
                // `stub/` / `llm_provider_call` placeholders the plan assumed.
                protected: raw_id == "arch/stub" || raw_id == "vox/llm/direct-provider-call",
                origin: "builtin".to_string(),
            }
        })
        .collect();
    out.sort_by(|a, b| a.id.cmp(&b.id));
    out
}

/// Build the full registry document for the domains this plan covers.
#[cfg(feature = "completion-toestub")]
pub fn build_registry() -> vox_config::PolicyRegistry {
    vox_config::PolicyRegistry {
        schema_version: 1,
        policies: code_audit_entries(),
    }
}

/// `vox ci policy-registry [--write]`: regenerate the catalog.
#[cfg(feature = "completion-toestub")]
pub fn run_generate(repo_root: &Path, write: bool) -> Result<(), String> {
    let reg = build_registry();
    let header = "# GENERATED by `vox ci policy-registry --write`. Do not hand-edit builtin entries.\n# SSOT for the unified policy catalog.\n";
    let body = serde_yaml::to_string(&reg).map_err(|e| format!("serialize: {e}"))?;
    let yaml = format!("{header}{body}");
    let path = repo_root.join(vox_config::REGISTRY_REL_PATH);
    if write {
        std::fs::write(&path, &yaml).map_err(|e| format!("write {}: {e}", path.display()))?;
        println!("wrote {} ({} policies)", path.display(), reg.policies.len());
    } else {
        println!("{yaml}");
    }
    Ok(())
}

/// Without `completion-toestub`, the `vox-code-audit` detector registry is not
/// linked; generation returns an actionable error rather than a partial catalog.
#[cfg(not(feature = "completion-toestub"))]
pub fn run_generate(repo_root: &Path, write: bool) -> Result<(), String> {
    let _ = (repo_root, write);
    Err(
        "policy-registry generation requires the `completion-toestub` feature \
         (it links the vox-code-audit detector registry); re-run with \
         `--features completion-toestub`"
            .to_string(),
    )
}

/// Read the on-disk registry YAML and validate it against the committed JSON Schema.
#[cfg(feature = "completion-toestub")]
fn validate_registry_against_schema(repo_root: &Path) -> Result<(), String> {
    let yaml_path = repo_root.join(vox_config::REGISTRY_REL_PATH);
    let schema_path = repo_root.join("contracts/policy/policy-registry.v1.schema.json");

    let yaml_src = std::fs::read_to_string(&yaml_path)
        .map_err(|e| format!("read {}: {e}", yaml_path.display()))?;
    let instance: serde_json::Value = serde_yaml::from_str(&yaml_src)
        .map_err(|e| format!("parse {}: {e}", yaml_path.display()))?;

    let schema_src = std::fs::read_to_string(&schema_path)
        .map_err(|e| format!("read {}: {e}", schema_path.display()))?;
    let schema_val: serde_json::Value = serde_json::from_str(&schema_src)
        .map_err(|e| format!("parse {}: {e}", schema_path.display()))?;

    let validator = vox_jsonschema_util::compile_validator(&schema_val, schema_path.display())
        .map_err(|e| format!("compile policy-registry schema: {e}"))?;
    vox_jsonschema_util::validate(&instance, &validator, "policy-registry.v1.yaml")
        .map_err(|e| e.to_string())
}

/// `vox ci policy-registry-parity`: assert the committed registry matches the
/// live `code-audit` detector set exactly (no drift). This is the transfer/
/// completeness proof for the domains this plan covers.
#[cfg(feature = "completion-toestub")]
pub fn run_parity(repo_root: &Path) -> Result<(), String> {
    let on_disk = vox_config::load_policy_registry(repo_root).map_err(|e| e.to_string())?;
    let expected = build_registry();

    // Validate the on-disk YAML against the committed JSON Schema so the schema is
    // enforced rather than decorative. Reuses the `vox-jsonschema-util` facade that
    // every other contract-vs-schema gate uses (e.g. data-storage-guard).
    validate_registry_against_schema(repo_root)?;

    use std::collections::BTreeSet;
    let disk_code_audit: Vec<&str> = on_disk
        .policies
        .iter()
        .filter(|e| e.domain == PolicyDomain::CodeAuditRule)
        .map(|e| e.id.as_str())
        .collect();
    let disk_ids: BTreeSet<&str> = disk_code_audit.iter().copied().collect();
    let exp_ids: BTreeSet<&str> = expected.policies.iter().map(|e| e.id.as_str()).collect();

    // The set comparison below silently dedupes duplicate `id` rows, so a registry
    // with a duplicated entry could pass while carrying a stale clone. Assert the raw
    // Vec length matches the expected count before trusting the set diff.
    if disk_code_audit.len() != exp_ids.len() {
        return Err(format!(
            "policy registry duplicate or unexpected count (code-audit domain): on-disk has {} entry(ies) but {} unique id(s) expected (live detectors); run `vox ci policy-registry --write`",
            disk_code_audit.len(),
            exp_ids.len()
        ));
    }

    let missing: Vec<&str> = exp_ids.difference(&disk_ids).copied().collect();
    let extra: Vec<&str> = disk_ids.difference(&exp_ids).copied().collect();
    if !missing.is_empty() || !extra.is_empty() {
        return Err(format!(
            "policy registry drift (code-audit domain):\n  missing {} entry(ies): {:?}\n  stale {} entry(ies): {:?}\n  run `vox ci policy-registry --write`",
            missing.len(),
            missing,
            extra.len(),
            extra
        ));
    }
    println!(
        "policy-registry-parity OK: {} code-audit entries match live detectors",
        exp_ids.len()
    );
    Ok(())
}

/// Without `completion-toestub`, the detector registry is not linked; parity
/// returns an actionable error rather than passing on a partial catalog.
#[cfg(not(feature = "completion-toestub"))]
pub fn run_parity(repo_root: &Path) -> Result<(), String> {
    let _ = repo_root;
    Err(
        "policy-registry-parity requires the `completion-toestub` feature \
         (it links the vox-code-audit detector registry); re-run with \
         `--features completion-toestub`"
            .to_string(),
    )
}

#[cfg(all(test, feature = "completion-toestub"))]
mod tests {
    use super::*;

    #[test]
    fn generates_one_entry_per_detector() {
        let entries = code_audit_entries();
        // Live detector registry returns 51 rules (vox-code-audit detectors::all_rules).
        assert!(
            entries.len() >= 45,
            "expected the full detector set, got {}",
            entries.len()
        );
        // Real stub detector id is `arch/stub` (verified against
        // `vox_code_audit::detectors::stub::StubDetector::id`), not the
        // `stub/todo` placeholder the plan assumed.
        let stub = entries
            .iter()
            .find(|e| e.id == "code-audit/arch/stub")
            .expect("arch/stub detector should be present");
        assert_eq!(stub.domain, PolicyDomain::CodeAuditRule);
        assert_eq!(stub.source.kind, PolicySourceKind::Pattern);
        assert!(stub.id.starts_with("code-audit/"));
    }

    #[test]
    fn schema_rejects_malformed_registry() {
        // FIX 2 guard: the committed JSON Schema must actually reject a structurally
        // invalid registry (here: `schema_version` of the wrong type), proving the
        // schema is enforced rather than decorative.
        let schema_path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .ancestors()
            .nth(2)
            .expect("repo root")
            .join("contracts/policy/policy-registry.v1.schema.json");
        let schema_src = std::fs::read_to_string(&schema_path).expect("read schema");
        let schema_val: serde_json::Value =
            serde_json::from_str(&schema_src).expect("parse schema");
        let validator = vox_jsonschema_util::compile_validator(&schema_val, schema_path.display())
            .expect("compile schema");
        let bad = serde_json::json!({ "schema_version": "one", "policies": [] });
        assert!(
            vox_jsonschema_util::validate(&bad, &validator, "test").is_err(),
            "schema should reject a string schema_version"
        );
    }

    #[test]
    fn duplicate_count_mismatch_is_detected() {
        // FIX 3 guard: a duplicated `id` row inflates the Vec length past the unique
        // (set) count, which the parity gate must treat as a failure. This mirrors the
        // `disk_code_audit.len() != exp_ids.len()` assertion in `run_parity`.
        use std::collections::BTreeSet;
        let entries = code_audit_entries();
        let first = entries[0].id.clone();
        let mut disk: Vec<&str> = entries.iter().map(|e| e.id.as_str()).collect();
        disk.push(&first); // inject a duplicate
        let unique: BTreeSet<&str> = disk.iter().copied().collect();
        assert_ne!(
            disk.len(),
            unique.len(),
            "duplicate id must make the Vec length exceed the unique-id count"
        );
    }

    #[test]
    fn every_entry_has_required_fields() {
        for e in code_audit_entries() {
            assert!(!e.title.is_empty(), "{} missing title", e.id);
            assert!(!e.group.is_empty(), "{} missing group", e.id);
            assert!(!e.description.is_empty(), "{} missing description", e.id);
        }
    }
}
