use crate::activity::{generate_activity, generate_activity_runner};
use vox_ast::decl::{ActivityDecl, AgentDecl, MessageDecl};

pub fn generate_activities(activities: &[&ActivityDecl]) -> String {
    let mut content = String::new();
    content.push_str(&generate_activity_runner());
    content.push('\n');
    for activity in activities {
        content.push_str(&generate_activity(activity));
    }
    content
}

pub fn generate_agent(agent: &AgentDecl) -> String {
    let mut content = String::new();
    content.push_str(&format!("// Agent: {}\n\n", agent.name));

    // State interface
    content.push_str(&format!("export interface {}State {{\n", agent.name));
    for field in &agent.state_fields {
        let ts_type = crate::component::map_vox_type_to_ts(&field.type_ann);
        content.push_str(&format!("  {}: {};\n", field.name, ts_type));
    }
    content.push_str("}\n\n");

    // Class with handlers
    content.push_str(&format!("export class {} {{\n", agent.name));
    content.push_str(&format!("  private state: {}State;\n\n", agent.name));
    content.push_str(&format!(
        "  constructor(initialState: {}State) {{\n",
        agent.name
    ));
    content.push_str("    this.state = initialState;\n");
    content.push_str("  }\n\n");

    for handler in &agent.handlers {
        let params: Vec<String> = handler
            .params
            .iter()
            .map(|p| {
                let ty = p
                    .type_ann
                    .as_ref()
                    .map_or("any".to_string(), crate::component::map_vox_type_to_ts);
                format!("{}: {}", p.name, ty)
            })
            .collect();
        let ret_type = handler
            .return_type
            .as_ref()
            .map_or("void".to_string(), crate::component::map_vox_type_to_ts);
        content.push_str(&format!(
            "  async {}({}): Promise<{}> {{\n",
            handler.event_name,
            params.join(", "),
            ret_type
        ));
        if handler.is_traced {
            content.push_str(&format!(
                "    console.debug(`[VOX] {}.{}`, {{ traceId: (window as any).voxTraceId || 'vox-unknown' }});\n",
                agent.name, handler.event_name
            ));
        }
        for stmt in &handler.body {
            content.push_str(&format!("    {};\n", crate::jsx::emit_stmt(stmt, 2)));
        }
        content.push_str("  }\n\n");
    }
    content.push_str("}\n");
    content
}

pub fn generate_messages(messages: &[&MessageDecl]) -> String {
    let mut content = String::new();
    content.push_str("// Message types generated by Vox compiler\n\n");
    for msg in messages {
        content.push_str(&format!("export interface {} {{\n", msg.name));
        for field in &msg.fields {
            let ts_type = crate::component::map_vox_type_to_ts(&field.type_ann);
            content.push_str(&format!("  {}: {};\n", field.name, ts_type));
        }
        content.push_str("}\n\n");
    }
    content
}
