
pub fn generate_test_suite(
    tests: &[&vox_ast::decl::FnDecl],
    fixtures: &[&vox_ast::decl::FnDecl],
    mocks: &[&vox_ast::decl::MockDecl],
) -> String {
    let mut test_content = String::new();
    test_content.push_str("// Test suite generated by Vox compiler\n");
    let has_mocks = !mocks.is_empty();
    let import_list = if has_mocks {
        "import { describe, it, expect, beforeEach, vi } from \"vitest\";"
    } else if !fixtures.is_empty() {
        "import { describe, it, expect, beforeEach } from \"vitest\";"
    } else {
        "import { describe, it, expect } from \"vitest\";"
    };
    test_content.push_str(&format!("{import_list}\n\n"));

    for mock in mocks {
        test_content.push_str(&format!("vi.mock(\"{}\", () => ({{\n", mock.target));
        let keyword = if mock.func.is_async { "async function" } else { "function" };
        let params: Vec<String> = mock.func
            .params
            .iter()
            .map(|p| p.name.clone())
            .collect();
        test_content.push_str(&format!("  {}: {} ({}) => {{\n", mock.func.name, keyword, params.join(", ")));
        for stmt in &mock.func.body {
            test_content.push_str(&format!("    {};\n", crate::jsx::emit_stmt(stmt, 2)));
        }
        test_content.push_str("  }\n");
        test_content.push_str("}));\n\n");
    }

    test_content.push_str("describe(\"Vox Tests\", () => {\n");

    for fixture in fixtures {
        let keyword = if fixture.is_async { "async function" } else { "function" };
        let params: Vec<String> = fixture
            .params
            .iter()
            .map(|p| {
                let ty = p
                    .type_ann
                    .as_ref()
                    .map_or("any".to_string(), crate::component::map_vox_type_to_ts);
                format!("{}: {}", p.name, ty)
            })
            .collect();
        test_content.push_str(&format!(
            "  {} {}({}) {{\n",
            keyword, fixture.name, params.join(", ")
        ));
        for stmt in &fixture.body {
            test_content.push_str(&format!("    {};\n", crate::jsx::emit_stmt(stmt, 2)));
        }
        test_content.push_str("  }\n\n");
    }

    if !fixtures.is_empty() {
        test_content.push_str("  beforeEach(async () => {\n");
        for fixture in fixtures {
            if fixture.is_async {
                test_content.push_str(&format!("    await {}();\n", fixture.name));
            } else {
                test_content.push_str(&format!("    {}();\n", fixture.name));
            }
        }
        test_content.push_str("  });\n\n");
    }

    for test_fn in tests {
        let fn_name = &test_fn.name;
        let description = fn_name.replace('_', " ");
        if test_fn.is_async {
            test_content.push_str(&format!("  it(\"{}\", async () => {{\n", description));
        } else {
            test_content.push_str(&format!("  it(\"{}\", () => {{\n", description));
        }
        for stmt in &test_fn.body {
            test_content.push_str(&format!("    {};\n", emit_test_stmt(stmt)));
        }
        test_content.push_str("  });\n\n");
    }
    test_content.push_str("});\n");
    test_content
}

pub fn emit_test_stmt(stmt: &vox_ast::stmt::Stmt) -> String {
    use vox_ast::expr::Expr;
    use vox_ast::stmt::Stmt;
    match stmt {
        Stmt::Expr { expr, .. } => {
            if let Expr::Call { callee, args, .. } = expr {
                if let Expr::Ident { ref name, .. } = **callee {
                    if name == "assert" && !args.is_empty() {
                        let inner = crate::jsx::emit_expr(&args[0].value);
                        return format!("expect({}).toBeTruthy()", inner);
                    }
                    if name == "assert_eq" && args.len() >= 2 {
                        let a = crate::jsx::emit_expr(&args[0].value);
                        let b = crate::jsx::emit_expr(&args[1].value);
                        return format!("expect({}).toEqual({})", a, b);
                    }
                    if name == "assert_ne" && args.len() >= 2 {
                        let a = crate::jsx::emit_expr(&args[0].value);
                        let b = crate::jsx::emit_expr(&args[1].value);
                        return format!("expect({}).not.toEqual({})", a, b);
                    }
                    if name == "assert_match" && args.len() >= 2 {
                        let a = crate::jsx::emit_expr(&args[0].value);
                        let b = crate::jsx::emit_expr(&args[1].value);
                        return format!("expect({}).toMatchObject({})", a, b);
                    }
                }
            }
            crate::jsx::emit_expr(expr)
        }
        Stmt::Let { pattern, value, .. } => {
            let pat_str = match pattern {
                vox_ast::pattern::Pattern::Ident { name, .. } => name.clone(),
                _ => "/* destructure */".to_string(),
            };
            format!("const {} = {}", pat_str, crate::jsx::emit_expr(value))
        }
        other => crate::jsx::emit_stmt(other, 2),
    }
}
