//! `CONFIG_KEYS`: the general federated config registry. Seed it with the knobs
//! that already have constants + a clear home. Domains migrate their
//! `operator_registry` rows here over time (Phase 2A.3). The
//! `vox ci config-registry-parity` gate (Phase 2B) enforces env coverage.

use crate::config_key::{ConfigKey, ConfigKind, DefaultValue, Group, GuiSurface, Home, Status};
use crate::operator_registry::ConfigClass;

/// The general config registry. ADD a row here for every new operational knob.
pub const CONFIG_KEYS: &[ConfigKey] = &[
    ConfigKey {
        key: "VOX_WASM_SKILL_FUEL",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("1000000000"),
        bound: Some((1_000_000.0, 100_000_000_000.0)),
        group: Group::Runtime,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: Some(GuiSurface {
            section: "Runtime & Sandbox",
            options: &[],
        }),
        secret: false,
        status: Status::Active,
        label: "WASM skill fuel",
        hint: "Wasmtime instruction budget for skill execution.",
    },
    ConfigKey {
        key: "VOX_GAMIFY_ECONOMY_PATH",
        kind: ConfigKind::Path,
        default: DefaultValue::Computed("embedded gamify economy contract"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::NodeLocal,
        home: Home::Contract("contracts/gamify/economy.v1.yaml"),
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Gamify economy contract override",
        hint: "Path to an override economy.v1.yaml; defaults to the embedded contract.",
    },
    ConfigKey {
        key: "VOX_CIRCUIT_BREAKER_CONTRACT",
        kind: ConfigKind::Path,
        default: DefaultValue::Computed("embedded circuit-breaker contract"),
        bound: None,
        group: Group::Orchestrator,
        class: ConfigClass::NodeLocal,
        home: Home::Contract("contracts/orchestration/circuit-breaker.v1.yaml"),
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Circuit-breaker contract override",
        hint: "Path to an override circuit-breaker.v1.yaml; defaults to the embedded contract.",
    },
    // --- 2A.3 Wave 1: SEARCH (VOX_SEARCH_*) migrated from operator_registry ---
    ConfigKey {
        key: "VOX_SEARCH_BM25_K1",
        kind: ConfigKind::Float,
        default: DefaultValue::Literal("1.2"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Bm25 K1",
        hint: "BM25 ranking saturation parameter k1.",
    },
    ConfigKey {
        key: "VOX_SEARCH_BM25_B",
        kind: ConfigKind::Float,
        default: DefaultValue::Literal("0.75"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Bm25 B",
        hint: "BM25 ranking document length normalization parameter b.",
    },
    ConfigKey {
        key: "VOX_SEARCH_RRF_K",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("60"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Rrf K",
        hint: "Reciprocal Rank Fusion constant k.",
    },
    ConfigKey {
        key: "VOX_SEARCH_VERIFICATION_QUALITY_THRESHOLD",
        kind: ConfigKind::Float,
        default: DefaultValue::Literal("0.7"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Verification Quality Threshold",
        hint: "Min confidence for search hit verification.",
    },
    ConfigKey {
        key: "VOX_SEARCH_POLICY_VERSION",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("1"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Policy Version",
        hint: "Enforce a specific search policy version.",
    },
    ConfigKey {
        key: "VOX_SEARCH_MEMORY_VECTOR_WEIGHT",
        kind: ConfigKind::Float,
        default: DefaultValue::Literal("0.55"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Memory Vector Weight",
        hint: "Vector weight in hybrid search fusion.",
    },
    ConfigKey {
        key: "VOX_SEARCH_REPO_MAX_FILES",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("20000"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Repo Max Files",
        hint: "Max files to scan for repo inventory.",
    },
    ConfigKey {
        key: "VOX_SEARCH_REPO_SKIP_DIRS",
        kind: ConfigKind::String,
        default: DefaultValue::Literal(".git,target,node_modules"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Repo Skip Dirs",
        hint: "Comma-separated list of directories to skip in repo scan.",
    },
    ConfigKey {
        key: "VOX_SEARCH_TAVILY_ENABLED",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Tavily Enabled",
        hint: "Master switch for Tavily web search.",
    },
    ConfigKey {
        key: "VOX_SEARCH_TAVILY_DEPTH",
        kind: ConfigKind::String,
        default: DefaultValue::Literal("basic"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Tavily Depth",
        hint: "Tavily search depth (basic/advanced).",
    },
    ConfigKey {
        key: "VOX_SEARCH_TAVILY_MAX_RESULTS",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("5"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Tavily Max Results",
        hint: "Max results per Tavily search.",
    },
    ConfigKey {
        key: "VOX_SEARCH_TAVILY_ON_EMPTY",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("true"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Tavily On Empty",
        hint: "Auto-fire Tavily when local search is empty.",
    },
    ConfigKey {
        key: "VOX_SEARCH_TAVILY_ON_WEAK",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Tavily On Weak",
        hint: "Auto-fire Tavily when local evidence is weak.",
    },
    ConfigKey {
        key: "VOX_SEARCH_TAVILY_BUDGET",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("50"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Tavily Budget",
        hint: "Safety budget for Tavily credits per session.",
    },
    ConfigKey {
        key: "VOX_SEARCH_SEARXNG_URL",
        kind: ConfigKind::String,
        default: DefaultValue::Literal(""),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Searxng Url",
        hint: "SearXNG instance URL.",
    },
    ConfigKey {
        key: "VOX_SEARCH_SEARXNG_MAX_RESULTS",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("5"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Searxng Max Results",
        hint: "Max results from SearXNG.",
    },
    ConfigKey {
        key: "VOX_SEARCH_SEARXNG_MAX_SCRAPE",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("3"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Searxng Max Scrape",
        hint: "Max URLs to deep-scrape from SearXNG results.",
    },
    ConfigKey {
        key: "VOX_SEARCH_SEARXNG_ENGINES",
        kind: ConfigKind::String,
        default: DefaultValue::Literal(""),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Searxng Engines",
        hint: "Engines for SearXNG query.",
    },
    ConfigKey {
        key: "VOX_SEARCH_SEARXNG_LANGUAGE",
        kind: ConfigKind::String,
        default: DefaultValue::Literal(""),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Searxng Language",
        hint: "Language for SearXNG query.",
    },
    ConfigKey {
        key: "VOX_SEARCH_SCRAPER_TIMEOUT",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("5000"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Scraper Timeout",
        hint: "Timeout for web scraper in ms.",
    },
    ConfigKey {
        key: "VOX_SEARCH_SCRAPER_ROBOTS_RESPECT",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Scraper Robots Respect",
        hint: "Respect robots.txt in scraper.",
    },
    ConfigKey {
        key: "VOX_SEARCH_SCRAPER_MIN_DENSITY",
        kind: ConfigKind::Float,
        default: DefaultValue::Literal("0.15"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Scraper Min Density",
        hint: "Min text density for scraped content.",
    },
    ConfigKey {
        key: "VOX_SEARCH_MAX_HOPS",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("3"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Max Hops",
        hint: "Max iterative search hops.",
    },
    ConfigKey {
        key: "VOX_SEARCH_TANTIVY_ROOT",
        kind: ConfigKind::String,
        default: DefaultValue::Literal(""),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Tantivy Root",
        hint: "Root path for Tantivy indices.",
    },
    ConfigKey {
        key: "VOX_SEARCH_PREFER_RRF",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Prefer Rrf",
        hint: "Prefer RRF for search fusion.",
    },
    ConfigKey {
        key: "VOX_SEARCH_QDRANT_URL",
        kind: ConfigKind::String,
        default: DefaultValue::Literal(""),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Qdrant Url",
        hint: "Qdrant API base URL.",
    },
    ConfigKey {
        key: "VOX_SEARCH_QDRANT_COLLECTION",
        kind: ConfigKind::String,
        default: DefaultValue::Literal("vox_docs"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Qdrant Collection",
        hint: "Qdrant collection name.",
    },
    ConfigKey {
        key: "VOX_SEARCH_QDRANT_VECTOR_NAME",
        kind: ConfigKind::String,
        default: DefaultValue::Literal(""),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Qdrant Vector Name",
        hint: "Named vector in Qdrant collection.",
    },
    ConfigKey {
        key: "VOX_SEARCH_DDG_FALLBACK_DISABLED",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::Tuning,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Search Ddg Fallback Disabled",
        hint: "Disable DuckDuckGo fallback when SearXNG fails.",
    },
    // --- 2A.3 Wave 1: MESH (VOX_MESH_*) migrated from operator_registry ---
    ConfigKey {
        key: "VOX_MESH_DEVICE_CLASS",
        kind: ConfigKind::String,
        default: DefaultValue::Literal("workstation"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh Device Class",
        hint: "Device tier for mesh coordination (mobile, workstation, cluster).",
    },
    ConfigKey {
        key: "VOX_MESH_EXEC_LEASE_STORE_PATH",
        kind: ConfigKind::Path,
        default: DefaultValue::Literal(".vox/mesh_leases.db"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh Exec Lease Store Path",
        hint: "Path to the mesh execution lease store.",
    },
    ConfigKey {
        key: "VOX_MESH_CODEX_TELEMETRY",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh Codex Telemetry",
        hint: "Enable mesh telemetry recording to Codex (1/true to enable).",
    },
    ConfigKey {
        key: "VOX_MESH_A2A_MAX_MESSAGES",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("1000"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh A2A Max Messages",
        hint: "Max A2A messages retained in memory per peer.",
    },
    ConfigKey {
        key: "VOX_MESH_BOOTSTRAP_EXPIRES_UNIX_MS",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("0"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh Bootstrap Expires Unix Ms",
        hint: "Expiration timestamp for bootstrap tokens.",
    },
    ConfigKey {
        key: "VOX_MESH_SCOPE_ID",
        kind: ConfigKind::String,
        default: DefaultValue::Literal("global"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh Scope Id",
        hint: "Isolation scope ID for the mesh network.",
    },
    ConfigKey {
        key: "VOX_MESH_SERVER_STALE_PRUNE_MS",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("300000"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh Server Stale Prune Ms",
        hint: "Interval for pruning stale mesh servers.",
    },
    ConfigKey {
        key: "VOX_MESH_MAX_STALE_MS",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("600000"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh Max Stale Ms",
        hint: "Maximum staleness for mesh nodes in monitoring.",
    },
    ConfigKey {
        key: "VOX_MESH_EXEC_POLICY",
        kind: ConfigKind::String,
        default: DefaultValue::Literal("local_only"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh Exec Policy",
        hint: "Execution policy for mesh tasks (local_only, prefer_remote, remote_only).",
    },
    ConfigKey {
        key: "VOX_MESH_NODE_ID",
        kind: ConfigKind::String,
        default: DefaultValue::Literal("default_node"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh Node Id",
        hint: "Unique identifier for this mesh node.",
    },
    ConfigKey {
        key: "VOX_MESH_REPLAY_PERSIST",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh Replay Persist",
        hint: "Enable persistence for mesh message replay (1/true to enable).",
    },
    ConfigKey {
        key: "VOX_MESH_REPLAY_STATE_PATH",
        kind: ConfigKind::Path,
        default: DefaultValue::Literal(".vox/mesh_replay.bin"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh Replay State Path",
        hint: "Path to mesh replay state file.",
    },
    ConfigKey {
        key: "VOX_MESH_A2A_LEASE_MS",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("30000"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh A2A Lease Ms",
        hint: "Lease duration for A2A message locks.",
    },
    ConfigKey {
        key: "VOX_MESH_HTTP_MAX_BODY_BYTES",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("104857600"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh Http Max Body Bytes",
        hint: "Max body size for mesh HTTP transport.",
    },
    ConfigKey {
        key: "VOX_MESH_A2A_STORE_PATH",
        kind: ConfigKind::Path,
        default: DefaultValue::Literal(".vox/mesh_a2a.db"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh A2A Store Path",
        hint: "Path to the A2A message store.",
    },
    ConfigKey {
        key: "VOX_MESH_DISPATCH_STORE_PATH",
        kind: ConfigKind::Path,
        default: DefaultValue::Literal(".vox/mesh_dispatch.db"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh Dispatch Store Path",
        hint: "Path to the task dispatch store.",
    },
    ConfigKey {
        key: "VOX_MESH_RANK",
        kind: ConfigKind::Int,
        default: DefaultValue::Literal("0"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh Rank",
        hint: "Rank of this node in a distributed training mesh.",
    },
    ConfigKey {
        key: "VOX_MESH_TRAIN",
        kind: ConfigKind::Bool,
        default: DefaultValue::Literal("false"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::UserPreference,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh Train",
        hint: "Enable distributed mesh training (1/true to enable).",
    },
    ConfigKey {
        key: "VOX_MESH_REGISTRY_PATH",
        kind: ConfigKind::Path,
        default: DefaultValue::Literal(".vox/mesh_nodes.json"),
        bound: None,
        group: Group::Mesh,
        class: ConfigClass::NodeLocal,
        home: Home::Env,
        gui: None,
        secret: false,
        status: Status::Active,
        label: "Mesh Registry Path",
        hint: "Path to the mesh node registry file.",
    },
];

/// All registered keys (for the parity gate).
pub fn registered_keys() -> impl Iterator<Item = &'static str> {
    CONFIG_KEYS.iter().map(|k| k.key)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn wave1_search_mesh_rows_migrated() {
        let keys: std::collections::BTreeSet<&str> = CONFIG_KEYS.iter().map(|k| k.key).collect();
        assert!(keys.contains("VOX_SEARCH_BM25_K1"));
        assert!(keys.contains("VOX_SEARCH_TAVILY_ENABLED"));
        assert!(keys.contains("VOX_MESH_DEVICE_CLASS"));
        assert!(
            CONFIG_KEYS.len() >= 3 + 40,
            "expected ~48 SEARCH+MESH rows added"
        );
    }

    #[test]
    fn keys_are_unique() {
        let mut seen = std::collections::BTreeSet::new();
        for k in CONFIG_KEYS {
            assert!(seen.insert(k.key), "duplicate ConfigKey: {}", k.key);
        }
    }

    #[test]
    fn env_homed_keys_are_vox_prefixed() {
        for k in CONFIG_KEYS {
            if matches!(k.home, Home::Env) {
                assert!(
                    k.key.starts_with("VOX_"),
                    "env knob must be VOX_*: {}",
                    k.key
                );
            }
        }
    }
}
