use anyhow::{Context, Result};
use std::path::Path;
use vox_pm::VoxManifest;

/// Generate infrastructure-as-code (Terraform) and local orchestration (Docker Compose)
/// from the project's Vox.toml and compiled artifacts.
pub async fn run(output_dir: &Path) -> Result<()> {
    println!("🏗️  Generating infrastructure and orchestration manifests...");

    let (manifest, _) = VoxManifest::discover(Path::new(".")).context("Failed to find Vox.toml")?;

    // --- Create output directory ---
    if !output_dir.exists() {
        std::fs::create_dir_all(output_dir).context("Failed to create infrastructure output directory")?;
    }

    // --- Generate Docker Compose ---
    let compose_content = generate_docker_compose(&manifest);
    let compose_path = output_dir.join("docker-compose.yml");
    std::fs::write(&compose_path, compose_content).context("Failed to write docker-compose.yml")?;
    println!("   ✓ Generated: {}", compose_path.display());

    // --- Generate Terraform (Minimal AWS/GCP example) ---
    let terraform_content = generate_terraform(&manifest);
    let terraform_path = output_dir.join("main.tf");
    std::fs::write(&terraform_path, terraform_content).context("Failed to write main.tf")?;
    println!("   ✓ Generated: {}", terraform_path.display());

    println!("   ✓ Infrastructure manifests ready in '{}'.", output_dir.display());
    Ok(())
}

fn generate_docker_compose(manifest: &VoxManifest) -> String {
    let name = &manifest.package.name;
    format!(
        r#"version: '3.8'
services:
  {name}:
    build: .
    ports:
      - "3000:3000"
    environment:
      - VOX_ENV=production
      - VOX_PORT=3000
    restart: always

  db:
    image: ghcr.io/tursodatabase/libsql-server:latest
    ports:
      - "8080:8080"
    volumes:
      - ./data:/var/lib/libsql
    restart: always
"#
    )
}

fn generate_terraform(manifest: &VoxManifest) -> String {
    let name = &manifest.package.name;
    format!(
        r#"# Generated by Vox Compiler
terraform {{
  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }}
  }}
}}

provider "aws" {{
  region = "us-east-1"
}}

resource "aws_ecr_repository" "app" {{
  name                 = "{name}"
  image_tag_mutability = "MUTABLE"
}}

resource "aws_apprunner_service" "app" {{
  service_name = "{name}"

  source_configuration {{
    authentication_configuration {{
      access_role_arn = aws_iam_role.app_runner_role.arn
    }}
    image_repository {{
      image_identifier      = "${{aws_ecr_repository.app.repository_url}}:latest"
      image_repository_type = "ECR"
      image_configuration {{
        port = "3000"
      }}
    }}
  }}
}}

resource "aws_iam_role" "app_runner_role" {{
  name = "{name}-app-runner-role"

  assume_role_policy = jsonencode({{
    Version = "2012-10-17"
    Statement = [
      {{
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Principal = {{
          Service = "build.apprunner.amazonaws.com"
        }}
      }},
    ]
  }})
}}
"#
    )
}
