import StyleDictionary from 'style-dictionary';

const CSS_HEADER = '/* AUTO-GENERATED by style-dictionary. Do not edit. Run `pnpm tokens:build`. */\n';

/** kebab CSS var name: color.bg.base -> --color-bg-base */
const cssVarName = (path) => `--${path.join('-')}`;

// Custom format: CSS custom properties under an arbitrary selector.
StyleDictionary.registerFormat({
  name: 'css/vars-selector',
  format: ({ dictionary, options }) => {
    const lines = dictionary.allTokens.map((t) => `  ${cssVarName(t.path)}: ${t.value};`);
    return `${CSS_HEADER}${options.selector} {\n${lines.join('\n')}\n}\n`;
  },
});

// Custom format: typed TS object of resolved values (nested by path).
StyleDictionary.registerFormat({
  name: 'ts/nested',
  format: ({ dictionary }) => {
    const root = {};
    for (const t of dictionary.allTokens) {
      let node = root;
      t.path.forEach((seg, i) => {
        if (i === t.path.length - 1) node[seg] = t.value;
        else node = (node[seg] ??= {});
      });
    }
    return `// AUTO-GENERATED by style-dictionary. Do not edit. Run \`pnpm tokens:build\`.\nexport const tokens = ${JSON.stringify(root, null, 2)} as const;\n`;
  },
});

const dark = new StyleDictionary({
  source: ['tokens/primitive.json', 'tokens/semantic.json'],
  platforms: {
    css: { transformGroup: 'css', buildPath: 'src/styles/', files: [
      { destination: 'tokens.generated.css', format: 'css/vars-selector', options: { selector: ':root' } },
    ] },
    ts: { transformGroup: 'js', buildPath: 'src/styles/', files: [
      { destination: 'tokens.generated.ts', format: 'ts/nested' },
    ] },
  },
});

const contrast = new StyleDictionary({
  source: ['tokens/primitive.json', 'tokens/semantic.json', 'tokens/semantic.contrast.json'],
  platforms: {
    css: { transformGroup: 'css', buildPath: 'src/styles/', files: [
      { destination: 'tokens.contrast.generated.css', format: 'css/vars-selector', options: { selector: '[data-theme="high-contrast"]' } },
    ] },
  },
});

await dark.buildAllPlatforms();
await contrast.buildAllPlatforms();
console.log('tokens built: tokens.generated.css, tokens.contrast.generated.css, tokens.generated.ts');
