use crate::ast_mutator;
use serde::{Deserialize, Serialize};
use std::path::PathBuf;
#[cfg(feature = "database")]
use vox_db::VoxDb;

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct DpoPair {
    pub prompt: String,
    pub chosen: String,
    pub rejected: String,
    pub category: String,
    pub source: Option<String>,
}

#[derive(Debug, Clone)]
pub struct DpoConfig {
    pub input: PathBuf,
    pub output: PathBuf,
    pub limit: usize,
}

pub fn generate_dpo_from_extract(config: &DpoConfig) -> anyhow::Result<usize> {
    use std::fs::File;
    use std::io::{BufRead, BufReader, Write};

    let input_file = File::open(&config.input)?;
    let reader = BufReader::new(input_file);

    let mut out_file = File::create(&config.output)?;
    let mut count = 0;

    for line in reader.lines() {
        let line = line?;
        if line.trim().is_empty() {
            continue;
        }

        let value: serde_json::Value = serde_json::from_str(&line)?;
        let prompt = value
            .get("prompt")
            .and_then(|v| v.as_str())
            .unwrap_or("")
            .to_string();
        let chosen = value
            .get("response")
            .and_then(|v| v.as_str())
            .unwrap_or("")
            .to_string();
        let category = value
            .get("category")
            .and_then(|v| v.as_str())
            .unwrap_or("vox_source")
            .to_string();
        let source = value
            .get("source")
            .and_then(|v| v.as_str())
            .map(|s| s.to_string());

        if chosen.is_empty() {
            continue;
        }

        // Generate rejected sample by mutating 'chosen'
        // For Vox files, we use the ast_mutator if it's not a generic prompt
        let rejected =
            if chosen.contains("fn ") || chosen.contains("actor ") || chosen.contains("@") {
                // Try to parse and mutate
                if let Ok(result) = vox_compiler::pipeline::run_frontend_str(&chosen, "<dpo-gen>") {
                    let mutations = ast_mutator::generate_mutations(&chosen, &result.module);
                    if !mutations.is_empty() {
                        ast_mutator::apply_mutations(&chosen, mutations)
                    } else {
                        // Fallback: simple string manipulation
                        chosen.replace("fn ", "function ")
                    }
                } else {
                    chosen.replace("fn ", "function ")
                }
            } else {
                chosen.replace("let ", "var ")
            };

        if rejected == chosen {
            // Skip pairs where mutation failed to change anything
            continue;
        }

        let pair = DpoPair {
            prompt,
            chosen,
            rejected,
            category,
            source,
        };

        let json = serde_json::to_string(&pair)?;
        writeln!(out_file, "{}", json)?;
        count += 1;

        if config.limit > 0 && count >= config.limit {
            break;
        }
    }

    Ok(count)
}

/// Mine PR code-review findings into Rust-review DPO preference pairs (R.2).
///
/// Reads an `ExternalReviewReplayRow` JSONL file (written by `vox corpus review-export`)
/// and produces `DpoPair` JSONL where:
/// - `chosen`  = the suggested fix from the review finding.
/// - `rejected` = a structurally broken variant generated by regex mutation (Rust-aware).
///
/// Only rows whose `response` contains Rust code (detected by `fn ` or ` -> ` in a
/// code fence) are converted; pure prose findings are skipped.
pub fn review_findings_to_dpo(input: &std::path::Path, output: &std::path::Path) -> anyhow::Result<usize> {
    use std::fs::File;
    use std::io::{BufRead, BufReader, Write};

    let reader = BufReader::new(File::open(input)?);
    let mut out = File::create(output)?;
    let mut count = 0;

    for line in reader.lines() {
        let line = line?;
        if line.trim().is_empty() { continue; }
        let row: serde_json::Value = match serde_json::from_str(&line) {
            Ok(v) => v,
            Err(_) => continue,
        };

        let prompt = row.get("prompt").and_then(|v| v.as_str()).unwrap_or("").to_string();
        let chosen = row.get("response").and_then(|v| v.as_str()).unwrap_or("").to_string();
        let category = row.get("category").and_then(|v| v.as_str()).unwrap_or("rust_review").to_string();

        if chosen.is_empty() || prompt.is_empty() { continue; }
        // Only convert rows that plausibly contain Rust code
        if !chosen.contains("fn ") && !chosen.contains("-> ") && !chosen.contains("```rust") { continue; }

        // Mutation: prefer semantic (remove return type annotation) over syntactic (string sub)
        let rejected = if chosen.contains("-> ") {
            // Strip return type annotation from function signatures
            let r = regex_remove_return_type(&chosen);
            if r != chosen { r } else { chosen.replace("fn ", "pub fn _broken_") }
        } else if chosen.contains("fn ") {
            chosen.replace("fn ", "pub fn _broken_")
        } else {
            chosen.replace("unwrap()", "expect(\"broken\")")
        };

        if rejected == chosen { continue; }

        let pair = DpoPair {
            prompt,
            chosen,
            rejected,
            category: format!("rust_review_{}", category),
            source: Some("review_findings".to_string()),
        };
        writeln!(out, "{}", serde_json::to_string(&pair)?)?;
        count += 1;
    }

    Ok(count)
}

/// Regex-free return type removal: strips `-> Type` before `{` on fn signature lines.
fn regex_remove_return_type(src: &str) -> String {
    src.lines()
        .map(|line| {
            if line.trim_start().starts_with("fn ") || line.trim_start().starts_with("pub fn ") {
                // Remove `-> ...` before the `{`
                if let Some(arrow) = line.find("->") {
                    if let Some(brace) = line[arrow..].find('{') {
                        let before = &line[..arrow];
                        let after = &line[arrow + brace..];
                        return format!("{}{}", before.trim_end(), after);
                    }
                }
            }
            line.to_string()
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// Export DPO preference pairs from VoxDB (corrections vs original failures).
#[cfg(test)]
mod review_dpo_tests {
    use super::*;

    #[test]
    fn review_findings_to_dpo_mines_rust_rows() {
        let dir = tempfile::tempdir().unwrap();
        let input = dir.path().join("findings.jsonl");
        // A row with Rust code in the response
        std::fs::write(&input, "{\"prompt\":\"Fix the borrow checker error in\",\"response\":\"fn process(data: &[u8]) -> Vec<u8> { data.to_vec() }\",\"category\":\"correctness\",\"severity\":\"high\",\"correctness_state\":\"accepted\",\"sample_kind\":\"review_fix_pairs\",\"source_id\":\"r1\",\"repository_id\":\"vox/vox\",\"placement_kind\":\"inline\",\"pr_number\":42,\"file_path\":\"src/lib.rs\",\"line_start\":10}\n").unwrap();
        let output = dir.path().join("out.jsonl");
        let count = review_findings_to_dpo(&input, &output).unwrap();
        assert_eq!(count, 1, "should mine 1 Rust DPO pair");
        let content = std::fs::read_to_string(&output).unwrap();
        let pair: DpoPair = serde_json::from_str(content.trim()).unwrap();
        assert_eq!(pair.source.as_deref(), Some("review_findings"));
        assert_ne!(pair.chosen, pair.rejected, "chosen and rejected must differ");
        assert!(pair.category.starts_with("rust_review_"), "lane prefixed correctly");
    }

    #[test]
    fn review_findings_to_dpo_skips_prose_rows() {
        let dir = tempfile::tempdir().unwrap();
        let input = dir.path().join("findings.jsonl");
        std::fs::write(&input, "{\"prompt\":\"Add a doc comment\",\"response\":\"The function should have a doc comment explaining the purpose.\",\"category\":\"docs\",\"severity\":\"low\",\"correctness_state\":\"accepted\",\"sample_kind\":\"review_fix_pairs\",\"source_id\":\"r2\",\"repository_id\":\"vox/vox\",\"placement_kind\":\"inline\",\"pr_number\":43,\"file_path\":\"src/lib.rs\",\"line_start\":5}\n").unwrap();
        let output = dir.path().join("out.jsonl");
        let count = review_findings_to_dpo(&input, &output).unwrap();
        assert_eq!(count, 0, "pure prose row should be skipped");
    }

    #[test]
    fn regex_remove_return_type_strips_arrow() {
        let src = "pub fn compute(x: i32) -> i32 {\n    x * 2\n}";
        let result = regex_remove_return_type(src);
        assert!(!result.contains("-> i32"), "return type stripped");
        assert!(result.contains("{"), "brace preserved");
    }
}

/// Export DPO preference pairs from VoxDB (corrections vs original failures).
#[cfg(feature = "database")]
pub async fn export_dogfood_dpo(db: &VoxDb, limit: i64, output: &PathBuf) -> anyhow::Result<usize> {
    use std::fs::File;
    use std::io::Write;

    let pairs = db.get_training_data(limit).await?;
    let mut out_file = File::create(output)?;
    let mut count = 0;

    for pair in pairs {
        if let Some(preferred) = pair.correction.as_ref().filter(|c: &&String| !c.is_empty()) {
            let preferred_str: &str = preferred.as_str();
            let dpo = DpoPair {
                prompt: pair.prompt,
                chosen: preferred_str.to_string(),
                rejected: pair.response,
                category: "agents_dogfood_dpo".to_string(),
                source: Some("vox_db".to_string()),
            };
            let json = serde_json::to_string(&dpo)?;
            writeln!(out_file, "{}", json)?;
            count += 1;
        }
    }

    Ok(count)
}
