[package]
name = "vox-config-derive"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
workspace-hack = { version = "0.6", path = "../workspace-hack" }

[dev-dependencies]
trybuild = "1"
vox-config = { path = "../vox-config" }
