use crate::policy::SecretPolicy;
use crate::spec::ids::SecretId;
use crate::spec::types::*;

pub const SPECS_MISSING_CORE: &[SecretSpec] = &[
    SecretSpec {
        id: SecretId::OpenaiModel,
        canonical_env: "VOX_OPENAI_MODEL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::OpenaiBaseUrl,
        canonical_env: "VOX_OPENAI_BASE_URL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::GeminiModel,
        canonical_env: "VOX_GEMINI_MODEL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::PopuliApiKey,
        canonical_env: "POPULI_API_KEY",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxNewsSiteBaseUrl,
        canonical_env: "VOX_NEWS_SITE_BASE_URL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxNewsRssFeedPath,
        canonical_env: "VOX_NEWS_RSS_FEED_PATH",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxNewsPublishArmed,
        canonical_env: "VOX_NEWS_PUBLISH_ARMED",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxZenodoVerifyStagingChecksums,
        canonical_env: "VOX_ZENODO_VERIFY_STAGING_CHECKSUMS",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxZenodoRequireMetadataParity,
        canonical_env: "VOX_ZENODO_REQUIRE_METADATA_PARITY",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxMcpAgentFleet,
        canonical_env: "VOX_MCP_AGENT_FLEET",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxZenodoHttpMaxAttempts,
        canonical_env: "VOX_ZENODO_HTTP_MAX_ATTEMPTS",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxOpenReviewHttpMaxAttempts,
        canonical_env: "VOX_OPEN_REVIEW_HTTP_MAX_ATTEMPTS",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxScholarlyJobLockOwner,
        canonical_env: "VOX_SCHOLARLY_JOB_LOCK_OWNER",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxScientiaCrossrefMailto,
        canonical_env: "VOX_SCIENTIA_CROSSREF_MAILTO",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxScientiaResearchMeshConsumerPollEnabled,
        canonical_env: "VOX_SCIENTIA_RESEARCH_MESH_CONSUMER_POLL",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxScientiaResearchMeshConsumerPollIntervalMs,
        canonical_env: "VOX_SCIENTIA_RESEARCH_MESH_CONSUMER_POLL_INTERVAL_MS",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxScientiaResearchMeshIntakeWriterEnabled,
        canonical_env: "VOX_SCIENTIA_RESEARCH_MESH_INTAKE_WRITER",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxMeshBootstrapToken,
        canonical_env: "VOX_MESH_BOOTSTRAP_TOKEN",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "",
        scope_description: "",
    },
    SecretSpec {
        id: SecretId::VoxMeshBootstrapExpiresUnixMs,
        canonical_env: "VOX_MESH_BOOTSTRAP_EXPIRES_UNIX_MS",
        aliases: &[],
        deprecated_aliases: &[],
        backend_key: None,
        auth_registry: None,
        policy: SecretPolicy::optional_skip(),
        remediation: "",
        scope_description: "",
    },
];
