//! Phase 5 — emit a generated `main()` for binaries compiled from `.vox` files.
//!
//! The generated binary must:
//! 1. Initialize the DB.
//! 2. Register the process-global `HirModule` so workflow bodies can look up
//!    activity bodies via `current_hir_module()`. The HirModule is serialized
//!    to JSON at codegen time and embedded as a `const &str` in the generated
//!    binary (ADR-041 §6(b); HirModule already derives `Serialize` +
//!    `Deserialize`).
//! 3. Register every `@scheduled` function with the runtime scheduler and start it.
//! 4. (Deferred — ADR-041 §6(c), 2026-05-23) Boot an HTTP server for
//!    `@query` / `@mutation` / `@server` endpoints. Extracting a
//!    `vox-http-runtime::serve(db, hir) -> Handle` symbol turns out to
//!    require a route-emission refactor (per-route handler functions are
//!    code-generated by name today). The TODO is harmless because
//!    production codegen uses `emit_main` (in `http.rs`), which serves
//!    HTTP inline — this `emit_main_boot` path is durable-only. See
//!    `docs/src/architecture/http-runtime-extraction-2026.md`.
//! 5. Wait for `ctrl_c` and shut down gracefully.
//!
//! P9 (2026-05-24): the durable boot is now ALSO injected into the production
//! `emit_main` (http.rs) so a single generated binary gets BOTH durable
//! functions AND HTTP serving. `emit_main_boot` remains the durable-only
//! emitter used by snapshot tests; `emit_durable_boot_prelude` +
//! `emit_durable_boot_helpers` are the shared building blocks that both
//! paths compose.
//!
//! The duration-literal parser (`"1s"`, `"500ms"`, `"1m"`, `"1h"`, `"1d"`) is
//! emitted inline so the generated binary has no extra runtime dependency on
//! a parser helper. Bare integer strings parse as seconds for ergonomics.
//!
//! See `docs/superpowers/plans/2026-05-23-durable-functions-completion.md`
//! (Task 5.1) for the parent plan and `mod.rs` for the `emit_main_boot`
//! re-export consumers should use.

use vox_compiler::hir::{HirEndpointKind, HirModule};

/// Returns `true` iff `module` has at least one `@scheduled` function.
fn has_scheduled(module: &HirModule) -> bool {
    module.functions.iter().any(|f| f.schedule_interval.is_some())
}

/// Emit `main.rs`-eligible Rust source containing a `#[tokio::main] async fn main()`
/// plus a small `parse_duration_literal` helper.
///
/// The returned string is intentionally pre-formatted (not run through
/// `prettyplease`) — the snapshot test locks the exact shape, so reviewers
/// see emit-level changes directly rather than through a pretty-print pass.
pub fn emit_main_boot(module: &HirModule) -> String {
    let has_http_endpoints = module.endpoint_fns.iter().any(|e| {
        matches!(
            e.kind,
            HirEndpointKind::Query | HirEndpointKind::Mutation | HirEndpointKind::Server
        )
    });

    let mut out = String::new();
    out.push_str(MAIN_BOOT_HEADER);

    out.push_str(
        "#[tokio::main]\nasync fn main() -> anyhow::Result<()> {\n",
    );

    // Sections 1 (DB) + 2 (HIR register) + 3 (scheduler register/start)
    // are emitted by the shared prelude helper. `main()` returns
    // `anyhow::Result<()>` so we propagate via `?` (BootPropagation::Try).
    out.push_str(&emit_durable_boot_prelude(
        module,
        "db",
        /* include_db_connect = */ true,
        BootPropagation::Try,
    ));

    // 4. HTTP boot (deferred — see ADR-041 §6(c) design doc).
    if has_http_endpoints {
        out.push_str("    // 4. HTTP server boot.\n");
        out.push_str("    // DEFERRED (ADR-041 §6(c), 2026-05-23):\n");
        out.push_str("    // The workspace does not ship a `vox-http-runtime::serve(db, hir) -> Handle`\n");
        out.push_str("    // because per-route handlers are code-generated by name (not registered at\n");
        out.push_str("    // runtime) — see docs/src/architecture/http-runtime-extraction-2026.md for\n");
        out.push_str("    // the full constraints + two-phase extraction plan. Production codegen uses\n");
        out.push_str("    // `emit_main` (http.rs) which serves HTTP inline; this `emit_main_boot` path\n");
        out.push_str("    // is durable-only today.\n\n");
    } else {
        out.push_str("    // 4. No `@query` / `@mutation` / `@server` endpoints — HTTP server not booted.\n\n");
    }

    // 5. Shutdown.
    out.push_str("    // 5. Wait for shutdown signal, then gracefully stop background tasks.\n");
    out.push_str("    tokio::signal::ctrl_c().await?;\n");
    if has_scheduled(module) {
        out.push_str("    scheduled_handle.shutdown().await;\n");
    }
    out.push_str("    Ok(())\n");
    out.push_str("}\n\n");

    // (PARSE_DURATION_LITERAL helper retired 2026-05-24 — ADR-041 M-3/M-7.
    // The generated `main()` now calls `::vox_workflow_runtime::parse_duration_str`
    // directly so the codegen and runtime share one parser and bad literals
    // surface as a structured error rather than a silent 60s fallback.)
    out.push_str(&emit_durable_boot_helpers(module));

    out
}

/// Error-propagation style for the durable boot prelude's `.await` sites.
///
/// The prelude has to call several fallible async helpers (`VoxDb::connect`,
/// `scheduled::register`, `scheduled::start`). How the failure surfaces
/// depends on the enclosing `main()` signature:
///
/// - `Try` — emits `await?;`. Use when `main()` returns `anyhow::Result<()>`
///   (the durable-only `emit_main_boot` path). Errors propagate cleanly to
///   the process exit code.
/// - `Expect` — emits `await.expect("…vox durable boot…");`. Use when
///   `main()` returns `()` (the production `emit_main` path in `http.rs`
///   today). Errors panic at boot, which is the same observable behaviour
///   as `?` from a `Result`-returning `main()` since both abort the
///   process before any HTTP route is served. P10 will change `emit_main`
///   to return `Result` so the prelude can use `Try` everywhere.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BootPropagation {
    Try,
    Expect,
}

impl BootPropagation {
    /// Render the trailing fragment for a fallible `.await` call site,
    /// including any required `let _ = …` wrapper, but NOT the
    /// terminating newline.
    fn await_suffix(self, what: &str) -> String {
        match self {
            BootPropagation::Try => "await?".to_string(),
            BootPropagation::Expect => format!("await.expect(\"vox durable boot: {what}\")"),
        }
    }
}

/// Emit the durable-functions boot prelude as `main()`-body Rust source:
///
/// 1. (optional) Connect a fresh `Arc<vox_db::VoxDb>` bound to `db_var_name`.
///    Skip via `include_db_connect = false` when the caller already has a
///    `VoxDb` (or wants to provide its own) — the caller is responsible
///    for binding `db_var_name` to an `Arc<vox_db::VoxDb>` BEFORE this
///    output runs.
/// 2. `set_current_hir_module(load_hir_module_from_embedded())` — registers
///    the process-global HirModule for `current_hir_module()` lookups
///    (ADR-041 §6(b)). Pair with `emit_durable_boot_helpers` AFTER the
///    enclosing `fn main()` closes.
/// 3. Register every `@scheduled` function and start the scheduler. If
///    `module` has no `@scheduled` functions this section emits a single
///    comment and skips the `scheduled_handle` binding.
///
/// `propagation` selects how fallible `.await` sites report errors — see
/// [`BootPropagation`]. The durable-only `emit_main_boot` uses `Try`; the
/// production `emit_main` (http.rs) uses `Expect` until P10 migrates
/// `main()` to `Result<()>`.
///
/// P9 (2026-05-24): extracted from `emit_main_boot` so the production
/// `emit_main` (http.rs) can wire durable boot alongside HTTP serving
/// without duplicating the logic. See module docs.
pub fn emit_durable_boot_prelude(
    module: &HirModule,
    db_var_name: &str,
    include_db_connect: bool,
    propagation: BootPropagation,
) -> String {
    let scheduled_fns: Vec<(&str, &str)> = module
        .functions
        .iter()
        .filter_map(|f| {
            f.schedule_interval
                .as_deref()
                .map(|interval| (f.name.as_str(), interval))
        })
        .collect();

    let mut out = String::new();

    // 1. DB init (optional — caller may have its own).
    if include_db_connect {
        let connect_await = propagation.await_suffix("VoxDb::connect");
        out.push_str("    // 1. Initialize the durable database.\n");
        out.push_str(
            "    //    Uses `DbConfig::resolve_canonical()` so the binary picks up\n\
             \x20   //    `VOX_DB_URL`/`VOX_DB_PATH` env vars (matches `emit_db_setup`).\n",
        );
        out.push_str(&format!(
            "    let {db_var_name} = std::sync::Arc::new(::vox_db::VoxDb::connect(\n\
             \x20       ::vox_db::DbConfig::resolve_canonical()\n\
             \x20           .expect(\"vox durable boot: resolve VoxDb config (VOX_DB_URL+TOKEN, or VOX_DB_PATH)\"),\n\
             \x20   ).{connect_await});\n\n",
        ));
    } else {
        out.push_str(&format!(
            "    // 1. Durable DB binding `{db_var_name}` is provided by the caller \
             (Arc<vox_db::VoxDb>).\n\n",
        ));
    }

    // 2. HIR module registration (ADR-041 §6(b)).
    out.push_str("    // 2. Register the process-global HirModule for workflow body lookup.\n");
    out.push_str("    //    The HirModule is serialized to JSON at codegen time and embedded\n");
    out.push_str("    //    as a `const &str` (see `load_hir_module_from_embedded` below).\n");
    out.push_str("    ::vox_workflow_runtime::workflow::set_current_hir_module(\n");
    out.push_str("        load_hir_module_from_embedded()\n");
    out.push_str("    );\n\n");

    // 3. Scheduler.
    if scheduled_fns.is_empty() {
        out.push_str("    // 3. No `@scheduled` functions in this module — scheduler not started.\n\n");
    } else {
        out.push_str("    // 3. Register every `@scheduled` function and start the runner.\n");
        for (name, interval) in &scheduled_fns {
            // Each duration literal is delegated to the runtime SSOT parser
            // (`::vox_workflow_runtime::parse_duration_str`), which returns a
            // structured DurationParseError on bad input — see ADR-041 M-3.
            // We `.expect()` here intentionally: the only way to reach this
            // line is if the user wrote `@scheduled("..bad..")` and the
            // boot-time panic surfaces a clean error pointing at the literal.
            // The previous inline parser silently fell back to 60s on parse
            // failure, which was M-3's footgun.
            let register_await =
                propagation.await_suffix(&format!("scheduled::register({name})"));
            out.push_str(&format!(
                "    ::vox_workflow_runtime::scheduled::register(\n\
                 \x20       {name_lit},\n\
                 \x20       ::vox_workflow_runtime::parse_duration_str({interval_lit})\n\
                 \x20           .unwrap_or_else(|e| panic!(\"@scheduled({interval_lit}) on fn `{fn_call}`: {{e}}\")),\n\
                 \x20       std::sync::Arc::new(|| Box::pin(async {{\n\
                 \x20           let _ = {fn_call}().await;\n\
                 \x20           Ok(())\n\
                 \x20       }})),\n\
                 \x20       {db_var_name}.clone(),\n\
                 \x20   ).{register_await};\n",
                name_lit = rust_string_literal(name),
                interval_lit = rust_string_literal(interval),
                fn_call = name,
                db_var_name = db_var_name,
                register_await = register_await,
            ));
        }
        let start_await = propagation.await_suffix("scheduled::start");
        out.push_str(&format!(
            "    let scheduled_handle = ::vox_workflow_runtime::scheduled::start({db_var_name}.clone()).{start_await};\n\n"
        ));
    }

    out
}

/// Emit the `load_hir_module_from_embedded()` free function used by the
/// durable boot prelude. Append AFTER the enclosing `fn main()` closes.
///
/// P9 (2026-05-24): extracted from `emit_main_boot` so production
/// `emit_main` (http.rs) can append the helper at the same level as its
/// other generated free functions. See module docs.
pub fn emit_durable_boot_helpers(module: &HirModule) -> String {
    emit_hir_embed_helper(module)
}

/// Emit the `load_hir_module_from_embedded()` helper.
///
/// The HirModule is serialized to JSON at codegen time and embedded into the
/// generated binary as a raw-string `const &str`. At boot, `main()` decodes
/// the JSON via `::serde_json::from_str(...)` and hands the resulting
/// `HirModule` to `::vox_workflow_runtime::workflow::set_current_hir_module`.
///
/// The raw-string delimiter is chosen dynamically: we start with `r#"…"#`
/// and bump the hash count whenever the serialized JSON contains a matching
/// closing delimiter that would prematurely terminate the literal. JSON
/// escapes `"` as `\"`, so in practice `"#` cannot appear and a single-hash
/// delimiter suffices — but the loop guarantees correctness for any input.
fn emit_hir_embed_helper(module: &HirModule) -> String {
    let serialized = serde_json::to_string(module)
        .expect("HirModule serializes to JSON (Serialize derive guaranteed at decl.rs:29)");

    // Pick the smallest `#`-count whose closing delimiter (`"` + N hashes)
    // does not appear inside the serialized JSON. Start at 1 and grow.
    let mut hash_count: usize = 1;
    loop {
        let mut closer = String::with_capacity(1 + hash_count);
        closer.push('"');
        for _ in 0..hash_count {
            closer.push('#');
        }
        if !serialized.contains(&closer) {
            break;
        }
        hash_count += 1;
        // Sanity: bound the search so a pathological input cannot infinite-loop.
        // 16 hashes is absurdly more than any real input would need.
        debug_assert!(hash_count <= 16, "raw-string delimiter escalation exceeded 16 hashes");
        if hash_count > 16 {
            break;
        }
    }
    let hashes: String = std::iter::repeat('#').take(hash_count).collect();

    let mut out = String::new();
    out.push_str(
        "/// Decode the codegen-time-embedded HirModule JSON back into a runtime\n\
         /// `HirModule`. Called once from `main()` to register the process-global\n\
         /// module for `current_hir_module()` lookups (ADR-041 §6(b)).\n",
    );
    out.push_str("fn load_hir_module_from_embedded() -> ::vox_compiler::hir::HirModule {\n");
    out.push_str(&format!(
        "    const EMBEDDED_HIR: &str = r{hashes}\"{serialized}\"{hashes};\n"
    ));
    out.push_str(
        "    ::serde_json::from_str(EMBEDDED_HIR)\n\
         \x20       .expect(\"embedded HirModule deserializes (codegen wrote it; should round-trip)\")\n",
    );
    out.push_str("}\n");
    out
}

/// File-level doc comment + uses for the generated `main.rs`.
const MAIN_BOOT_HEADER: &str = "\
// Generated by Vox Compiler — durable-binary main() boot routine.
// See docs/superpowers/plans/2026-05-23-durable-functions-completion.md (Task 5.1)
// and docs/src/adr/041-durable-functions-completion-2026.md §6(b).
//
// The contract here is:
//   DB init  →  HIR register  →  scheduler register+start  →  ctrl-C  →  graceful shutdown.
// HTTP serving still lives in the per-route emit (http.rs); factoring that
// into a reusable vox-http-runtime crate is DEFERRED under §6(c) — see
// docs/src/architecture/http-runtime-extraction-2026.md for constraints.

";

// PARSE_DURATION_LITERAL retired 2026-05-24 (ADR-041 M-3 + M-7). The emit now
// calls `::vox_workflow_runtime::parse_duration_str` directly — one parser, no
// silent fallback. Keeping a comment here so future maintainers can find the
// rename via grep.

#[allow(dead_code)]
const _PARSE_DURATION_LITERAL_RETIRED_2026_05_24: &str = "\
/// (RETIRED) replaced by ::vox_workflow_runtime::parse_duration_str — see
/// crates/vox-workflow-runtime/src/duration_literal.rs.
fn parse_duration_literal(s: &str) -> std::time::Duration {
    let s = s.trim();
    let (digits, unit_secs): (&str, u64) = if let Some(rest) = s.strip_suffix(\"ms\") {
        return std::time::Duration::from_millis(rest.trim().parse().unwrap_or(60_000));
    } else if let Some(rest) = s.strip_suffix('s') {
        (rest.trim(), 1)
    } else if let Some(rest) = s.strip_suffix('m') {
        (rest.trim(), 60)
    } else if let Some(rest) = s.strip_suffix('h') {
        (rest.trim(), 60 * 60)
    } else if let Some(rest) = s.strip_suffix('d') {
        (rest.trim(), 60 * 60 * 24)
    } else {
        (s, 1)
    };
    let n: u64 = digits.parse().unwrap_or(60);
    std::time::Duration::from_secs(n * unit_secs)
}
";

/// Emit `s` as a Rust string literal with escaping for `\\`, `\"`, and control
/// characters. Used for `@scheduled` function names + interval literals — both
/// untrusted-ish (they come from source).
fn rust_string_literal(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                out.push_str(&format!("\\u{{{:x}}}", c as u32));
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}
