use std::env;
use std::path::{Path, PathBuf};
use std::process::Command;

/// Kernels bundled as PTX. Each has a matching `src/<name>.cu`.
const KERNEL_NAMES: &[&str] = &[
    "affine", "binary", "cast", "conv", "fill", "indexing", "quantized", "reduce", "sort",
    "ternary", "unary",
];

/// `reduce.cu` uses C++17 + relies on MSVC conformant-preprocessor mode on Windows.
/// All other kernels compile with the plain flag set.
const CXX17_KERNELS: &[&str] = &["reduce"];

fn main() {
    println!("cargo::rerun-if-changed=build.rs");
    println!("cargo::rerun-if-changed=src/ptx");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let ptx_path = out_dir.join("ptx.rs");
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let src_dir = manifest_dir.join("src");
    let ptx_src_dir = src_dir.join("ptx");

    // Re-run if any kernel source (.cu) or shared header (.cuh) changes so stale
    // PTX is regenerated. Without this, editing a .cu would not retrigger nvcc.
    for name in KERNEL_NAMES {
        println!("cargo::rerun-if-changed=src/{name}.cu");
    }
    for cuh in ["binary_op_macros.cuh", "compatibility.cuh", "cuda_utils.cuh"] {
        println!("cargo::rerun-if-changed=src/{cuh}");
    }
    // Opt-out / override knobs (documented in .gitignore + build-environment.mdc).
    println!("cargo::rerun-if-env-changed=CANDLE_KERNELS_NO_NVCC");
    println!("cargo::rerun-if-env-changed=CANDLE_KERNELS_PTX_ARCH");
    println!("cargo::rerun-if-env-changed=CUDA_PATH");

    let _ = std::fs::create_dir_all(&ptx_src_dir);

    // Resolve nvcc once. `None` means we cannot self-heal and fall back to
    // whatever .ptx already exist (with a loud warning for any that are missing).
    let nvcc = if env::var_os("CANDLE_KERNELS_NO_NVCC").is_some() {
        None
    } else {
        find_nvcc()
    };
    // PTX virtual arch. sm_80 is forward-compatible: the driver JIT-compiles it
    // to the live GPU (e.g. sm_89 Ada) at module load. Override via env if needed.
    let arch =
        env::var("CANDLE_KERNELS_PTX_ARCH").unwrap_or_else(|_| "sm_80".to_string());

    let mut ptx_rs = String::from(
        "// Auto-generated by candle-kernels build.rs — DO NOT EDIT.\n\
         // PTX is compiled on demand from src/*.cu when nvcc is available,\n\
         // otherwise loaded from committed src/ptx/*.ptx bundles.\n\n",
    );

    let mut any_missing = false;
    for name in KERNEL_NAMES {
        let cu_file = src_dir.join(format!("{name}.cu"));
        let ptx_file = ptx_src_dir.join(format!("{name}.ptx"));

        // Regenerate when the PTX is missing or older than its .cu source,
        // provided nvcc is available. This is the self-healing path that lets a
        // fresh checkout (PTX is gitignored) produce working kernels with no
        // manual nvcc pass — exactly what the .gitignore documents as intended.
        let needs_build = !ptx_file.is_file() || is_stale(&cu_file, &ptx_file);
        if needs_build {
            if let Some(nvcc) = &nvcc {
                if cu_file.is_file() {
                    match compile_ptx(nvcc, &cu_file, &ptx_file, &src_dir, &arch, name) {
                        Ok(()) => {
                            println!(
                                "cargo::warning=candle-kernels: compiled PTX for '{name}' via nvcc ({arch})"
                            );
                        }
                        Err(e) => {
                            println!(
                                "cargo::warning=candle-kernels: nvcc failed for '{name}': {e}"
                            );
                        }
                    }
                } else {
                    println!(
                        "cargo::warning=candle-kernels: source {} missing; cannot compile '{name}'",
                        cu_file.display()
                    );
                }
            }
        }

        if ptx_file.is_file() {
            // Use `pub static` (not `pub const`) so the string bytes are forced
            // into a named memory location and survive LTO. With `pub const`,
            // rustc treats the value as inlinable and `lto = "thin"` strips the
            // string data when no direct use-site is visible through several
            // layers of indirection (cudarc LoadingPolicy::Eager →
            // Driver::compile_ptx → &Module.ptx()), leading to empty PTX at
            // cuModuleLoadData and CUDA_ERROR_INVALID_IMAGE at first kernel
            // launch. See evidence trail in PR #92.
            ptx_rs.push_str(&format!(
                "pub static {}: &str = include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/src/ptx/{}.ptx\"));\n",
                name.to_uppercase(),
                name
            ));
        } else {
            println!(
                "cargo::warning=Missing pre-compiled PTX for kernel '{name}' at {ptx_file:?}"
            );
            // Provide an empty string so downstream compiles but the kernel will be unusable.
            ptx_rs.push_str(&format!("pub static {}: &str = \"\";\n", name.to_uppercase()));
            any_missing = true;
        }
    }

    if any_missing {
        let hint = if nvcc.is_none() {
            "nvcc was not found (and CANDLE_KERNELS_NO_NVCC may be set). Install the CUDA \
             toolkit and a host C++ compiler (cl.exe on Windows / a dev shell), or commit \
             prebuilt .ptx into src/ptx/."
        } else {
            "nvcc was found but one or more kernels failed to compile — see the per-kernel \
             warnings above. On Windows nvcc needs cl.exe on PATH (run from a VS dev shell)."
        };
        println!(
            "cargo::warning=One or more PTX bundles are missing. CUDA inference will fail \
             with CUDA_ERROR_INVALID_IMAGE when those kernels load. {hint}"
        );
    }

    std::fs::write(&ptx_path, ptx_rs).unwrap();

    // MOE kernels are GPU-specific and require nvcc to compile.
    // They are not bundled as PTX because they depend on WMMA intrinsics
    // that vary per GPU architecture. MOE paths are disabled in the pure-Rust
    // build — the feature flag `moe` (not enabled by default) gates them.
    // No link directives for libmoe or cudart here; cudarc handles the
    // runtime CUDA linkage at runtime via dlopen.
}

/// True when `ptx` is missing or older than `cu` (source edited after last compile).
fn is_stale(cu: &Path, ptx: &Path) -> bool {
    let cu_mtime = cu.metadata().and_then(|m| m.modified()).ok();
    let ptx_mtime = ptx.metadata().and_then(|m| m.modified()).ok();
    match (cu_mtime, ptx_mtime) {
        (Some(c), Some(p)) => c > p,
        // If we can't stat the .cu, don't force a rebuild; if we can't stat the
        // .ptx it's effectively missing and handled by the `is_file()` check.
        _ => false,
    }
}

/// Locate an `nvcc` executable. Checks PATH first (respecting a dev shell), then
/// `CUDA_PATH` / `CUDA_HOME` / `CUDA_ROOT`, then the highest-versioned default
/// Windows CUDA install. Returns `None` when none is found.
fn find_nvcc() -> Option<PathBuf> {
    let exe = if cfg!(windows) { "nvcc.exe" } else { "nvcc" };

    // 1. On PATH (covers a configured dev shell / Linux toolkits).
    if Command::new(exe).arg("--version").output().map(|o| o.status.success()).unwrap_or(false) {
        return Some(PathBuf::from(exe));
    }

    // 2. Explicit CUDA root env vars.
    for var in ["CUDA_PATH", "CUDA_HOME", "CUDA_ROOT", "CUDA_TOOLKIT_ROOT_DIR"] {
        if let Some(root) = env::var_os(var) {
            let cand = PathBuf::from(root).join("bin").join(exe);
            if cand.is_file() {
                return Some(cand);
            }
        }
    }

    // 3. Highest-versioned default Windows install.
    if cfg!(windows) {
        let base = PathBuf::from("C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA");
        if let Ok(entries) = std::fs::read_dir(&base) {
            let mut versions: Vec<PathBuf> = entries
                .filter_map(|e| e.ok().map(|e| e.path()))
                .filter(|p| p.join("bin").join(exe).is_file())
                .collect();
            // Lexicographic sort on "vMAJOR.MINOR" names approximates version order
            // closely enough for picking the newest (v12.x < v13.x).
            versions.sort();
            if let Some(newest) = versions.pop() {
                return Some(newest.join("bin").join(exe));
            }
        }
    }

    None
}

/// Compile a single `.cu` to `.ptx` with the documented flag set.
fn compile_ptx(
    nvcc: &Path,
    cu: &Path,
    ptx: &Path,
    include_dir: &Path,
    arch: &str,
    name: &str,
) -> Result<(), String> {
    let mut cmd = Command::new(nvcc);
    cmd.arg("-ptx")
        .arg(format!("-arch={arch}"))
        .arg("-O3")
        .arg("--use_fast_math");

    if CXX17_KERNELS.contains(&name) {
        cmd.arg("-std=c++17");
        // MSVC needs conformant-preprocessor mode for these headers.
        if cfg!(windows) {
            cmd.arg("-Xcompiler").arg("/Zc:preprocessor");
        }
    }

    cmd.arg(cu)
        .arg("-o")
        .arg(ptx)
        // Fused `-I<path>` form (unambiguous across nvcc/cl arg parsing).
        .arg(format!("-I{}", include_dir.display()));

    let output = cmd
        .output()
        .map_err(|e| format!("spawning nvcc: {e}"))?;
    if !output.status.success() {
        // nvcc sometimes writes diagnostics to stdout rather than stderr, so
        // surface both, trimmed, to make build-time warnings actionable.
        let mut diag = String::new();
        for stream in [&output.stderr, &output.stdout] {
            let s = String::from_utf8_lossy(stream);
            for line in s.lines().filter(|l| !l.trim().is_empty()).take(4) {
                if !diag.is_empty() {
                    diag.push_str(" | ");
                }
                diag.push_str(line.trim());
            }
        }
        if diag.is_empty() {
            diag.push_str("(no nvcc output captured)");
        }
        return Err(format!("exit {:?}: {diag}", output.status.code()));
    }
    Ok(())
}
