// AUTO-GENERATED by style-dictionary. Do not edit. Run `pnpm tokens:build`.
export const tokens = {
  "color": {
    "neutral": {
      "50": "#fafafa",
      "300": "#d4d4d8",
      "400": "#a1a1aa",
      "700": "#3f3f46",
      "800": "#27272a",
      "900": "#18181b",
      "950": "#09090b"
    },
    "brass": {
      "default": "#d4af37"
    },
    "status": {
      "pass": "#a7f3d0",
      "fail": "#fca5a5",
      "warn": "#fde68a",
      "info": "#bfdbfe"
    },
    "bg": {
      "base": "#09090b",
      "surface": "#18181b",
      "elevated": "#27272a"
    },
    "text": {
      "primary": "#fafafa",
      "secondary": "#d4d4d8",
      "muted": "#a1a1aa"
    },
    "border": {
      "subtle": "#3f3f46",
      "strong": "#a1a1aa"
    },
    "accent": {
      "default": "#d4af37"
    }
  },
  "space": {
    "0": "0px",
    "1": "4px",
    "2": "8px",
    "3": "12px",
    "4": "16px",
    "6": "24px",
    "8": "32px",
    "12": "48px"
  },
  "radius": {
    "sm": "6px",
    "md": "10px",
    "lg": "16px",
    "xl": "24px"
  },
  "font": {
    "size": {
      "xs": "12px",
      "sm": "14px",
      "base": "16px",
      "lg": "18px",
      "xl": "24px",
      "2xl": "32px"
    },
    "weight": {
      "regular": "400",
      "medium": "500",
      "semibold": "600",
      "bold": "700"
    },
    "leading": {
      "tight": "1.25",
      "normal": "1.5"
    }
  },
  "motion": {
    "fast": "120ms",
    "base": "200ms",
    "slow": "400ms"
  },
  "z": {
    "base": "0",
    "dropdown": "1000",
    "modal": "1300",
    "toast": "1500"
  }
} as const;
