//! Emits the transport-neutral channel runtime (`vox-channel.ts`) from the channel
//! contract. The runtime exposes `voxChannel.subscribe(name, cb)` which resolves a
//! transport lazily and guarded: the Tauri transport (wrapping `listen`) is loaded
//! ONLY when `__TAURI_INTERNALS__` exists; otherwise a dev-mock transport is used,
//! and any channel declaring `poll:` falls back to interval refetch. Nothing here
//! imports `@tauri-apps` at module load — that is the bare-browser crash fix.

use super::channels::ChannelContract;
#[cfg(test)]
use super::channels::load_channel_contract;

/// Emit the full `vox-channel.ts` source from the channel contract.
pub fn emit_channel_runtime(contract: &ChannelContract) -> String {
    let mut out = String::new();
    out.push_str("// GENERATED by vox-codegen-ts channel_runtime_emit. Do not edit.\n");
    out.push_str("export type ChannelName =\n");
    for ch in &contract.channels {
        out.push_str(&format!("  | \"{}\"\n", ch.name));
    }
    out.push_str(";\n\n");

    // name → wire uri table
    out.push_str("const CHANNEL_URI: Record<ChannelName, string> = {\n");
    for ch in &contract.channels {
        out.push_str(&format!("  {}: \"{}\",\n", ch.name, ch.uri));
    }
    out.push_str("};\n\n");

    // optional poll table
    out.push_str("const CHANNEL_POLL: Partial<Record<ChannelName, { command: string; everyMs: number }>> = {\n");
    for ch in &contract.channels {
        if let Some(p) = &ch.poll {
            out.push_str(&format!(
                "  {}: {{ command: \"{}\", everyMs: {} }},\n",
                ch.name, p.command, p.every_ms
            ));
        }
    }
    out.push_str("};\n\n");

    out.push_str(RUNTIME_BODY);
    out
}

/// Static runtime body: guarded lazy transport resolution + subscribe + poll fallback.
const RUNTIME_BODY: &str = r#"export interface VoxChannelTransport {
  subscribe(uri: string, onFrame: (raw: unknown) => void): Promise<() => void>;
}

function hasTauri(): boolean {
  return typeof (globalThis as any).__TAURI_INTERNALS__ !== "undefined";
}

async function tauriTransport(): Promise<VoxChannelTransport> {
  // Dynamic import so @tauri-apps is never pulled in at module load.
  const { listen } = await import("@tauri-apps/api/event");
  return {
    subscribe: (uri, onFrame) =>
      listen(uri, (e: { payload: unknown }) => onFrame(e.payload)),
  };
}

const mockTransport: VoxChannelTransport = {
  subscribe: async () => () => {},
};

async function resolveTransport(): Promise<VoxChannelTransport> {
  if (hasTauri()) {
    try { return await tauriTransport(); } catch { return mockTransport; }
  }
  return mockTransport;
}

export const voxChannel = {
  subscribe(name: ChannelName, onFrame: (payload: any) => void): Promise<() => void> {
    const uri = CHANNEL_URI[name];
    return resolveTransport().then((t) => {
      if (t === mockTransport) {
        const poll = CHANNEL_POLL[name];
        if (poll) {
          // Transparent fallback: the GUI host registers a refetch handler keyed by
          // command name; if absent this is a harmless no-op interval.
          const id = setInterval(() => {
            const fn = (globalThis as any).__voxPoll?.[poll.command];
            if (typeof fn === "function") void fn();
          }, poll.everyMs);
          return () => clearInterval(id);
        }
        return () => {};
      }
      return t.subscribe(uri, onFrame);
    });
  },
};
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn runtime_has_guarded_transport_and_no_toplevel_tauri_import() {
        let c = load_channel_contract();
        let src = emit_channel_runtime(&c);
        // Typed channel union present.
        assert!(src.contains("export type ChannelName"));
        // Guarded resolution present.
        assert!(src.contains("__TAURI_INTERNALS__"));
        assert!(src.contains("export const voxChannel"));
        // CRITICAL: no static top-level `import ... @tauri-apps`. The only reference
        // must be the dynamic `await import("@tauri-apps/api/event")`.
        for line in src.lines() {
            let l = line.trim_start();
            if l.starts_with("import ") {
                assert!(
                    !l.contains("@tauri-apps"),
                    "static @tauri-apps import would crash bare browser: {line}"
                );
            }
        }
        // A channel that declares poll must appear in the poll table.
        if c.channels.iter().any(|ch| ch.poll.is_some()) {
            assert!(src.contains("everyMs:"), "poll table missing");
        }
    }
}
