use vox_ast::decl::Module;
use crate::component::generate_component;
use crate::routes::generate_routes;
use crate::adt::generate_types;
use crate::activity::{generate_activity, generate_activity_runner};

/// Output from the TypeScript code generator.
pub struct CodegenOutput {
    /// List of (filename, content) pairs.
    pub files: Vec<(String, String)>,
}

/// Generate TypeScript files from a Vox module.
pub fn generate(module: &Module) -> Result<CodegenOutput, String> {
    let mut files = Vec::new();

    // Generate type definitions
    let types_content = generate_types(module);
    if !types_content.is_empty() {
        files.push(("types.ts".to_string(), types_content));
    }

    // Generate components
    for decl in &module.declarations {
        if let vox_ast::decl::Decl::Component(comp) = decl {
            let (filename, content) = generate_component(&comp.func, !comp.styles.is_empty());
            files.push((filename, content));
        }
    }

    // Generate v0 component placeholders
    for decl in &module.declarations {
        if let vox_ast::decl::Decl::V0Component(v0) = decl {
            let filename = format!("{}.tsx", v0.name);
            let prompt_comment = if !v0.prompt.is_empty() {
                format!("Prompt: {}", v0.prompt)
            } else if let Some(ref img) = v0.image_path {
                format!("From image: {}", img)
            } else {
                "No prompt provided".to_string()
            };
            let content = format!(
                "// @v0 generated component\n// {}\nimport React from \"react\";\n\nexport function {}(): React.ReactElement {{\n  return <div>{{/* TODO: Generate via v0.dev */}}</div>;\n}}\n",
                prompt_comment, v0.name
            );
            files.push((filename, content));
        }
    }

    // Generate server routes
    let routes_content = generate_routes(module);
    if !routes_content.is_empty() {
        files.push(("server.ts".to_string(), routes_content));
    }

    // Generate activities
    let activities: Vec<_> = module.declarations.iter().filter_map(|d| {
        if let vox_ast::decl::Decl::Activity(a) = d { Some(a) } else { None }
    }).collect();

    if !activities.is_empty() {
        let mut activities_content = String::new();
        // Add the executeActivity runtime helper
        activities_content.push_str(&generate_activity_runner());
        activities_content.push('\n');
        // Add each activity as an async function
        for activity in &activities {
            activities_content.push_str(&generate_activity(activity));
        }
        files.push(("activities.ts".to_string(), activities_content));
    }

    // Generate table interfaces + schema
    let tables: Vec<_> = module.declarations.iter().filter_map(|d| {
        if let vox_ast::decl::Decl::Table(t) = d { Some(t) } else { None }
    }).collect();

    if !tables.is_empty() {
        let mut schema = String::new();
        schema.push_str("// Table interfaces generated by Vox compiler\n\n");
        for table in &tables {
            schema.push_str(&format!("export interface {} {{\n", table.name));
            schema.push_str("  _id: number;\n");
            for field in &table.fields {
                let ts_type = crate::component::map_vox_type_to_ts(&field.type_ann);
                schema.push_str(&format!("  {}: {};\n", field.name, ts_type));
            }
            schema.push_str("}\n\n");
        }
        files.push(("schema.ts".to_string(), schema));
    }

    // Generate scoped CSS modules for components with style blocks
    for decl in &module.declarations {
        if let vox_ast::decl::Decl::Component(comp) = decl {
            if !comp.styles.is_empty() {
                let filename = format!("{}.css", comp.func.name);
                let mut css = String::new();
                for block in &comp.styles {
                    css.push_str(&format!("{} {{\n", block.selector));
                    for (prop, val) in &block.properties {
                        // Convert Vox camelCase property names to CSS kebab-case
                        let css_prop = prop.chars().fold(String::new(), |mut acc, c| {
                            if c.is_uppercase() {
                                acc.push('-');
                                acc.push(c.to_ascii_lowercase());
                            } else {
                                acc.push(c);
                            }
                            acc
                        });
                        css.push_str(&format!("  {}: {};\n", css_prop, val));
                    }
                    css.push_str("}\n\n");
                }
                files.push((filename, css));
            }
        }
    }

    // Generate App.tsx with React Router for routes: declarations
    for decl in &module.declarations {
        if let vox_ast::decl::Decl::Routes(routes_decl) = decl {
            let mut app = String::new();
            app.push_str("import React from \"react\";\n");
            app.push_str("import { BrowserRouter, Routes, Route } from \"react-router-dom\";\n");
            // Import each referenced component
            for entry in &routes_decl.entries {
                app.push_str(&format!(
                    "import {{ {} }} from \"./{}.tsx\";\n",
                    entry.component_name, entry.component_name
                ));
            }
            app.push_str("\nexport default function App(): React.ReactElement {\n");
            app.push_str("  return (\n");
            app.push_str("    <BrowserRouter>\n");
            app.push_str("      <Routes>\n");
            for entry in &routes_decl.entries {
                app.push_str(&format!(
                    "        <Route path=\"{}\" element={{<{} />}} />\n",
                    entry.path, entry.component_name
                ));
            }
            app.push_str("      </Routes>\n");
            app.push_str("    </BrowserRouter>\n");
            app.push_str("  );\n");
            app.push_str("}\n");
            files.push(("App.tsx".to_string(), app));
        }
    }

    Ok(CodegenOutput { files })
}
