use serde_json::{Map, Value};
use vox_compiler::tokens::TokenRegistry;

/// Export a `TokenRegistry` to W3C Design Tokens Community Group (DTCG) format.
pub fn export_to_dtcg(registry: &TokenRegistry) -> Value {
    let mut root = Map::new();
    // Sort keys for deterministic output.
    let mut keys: Vec<&String> = registry.by_css_var.keys().collect();
    keys.sort();

    for key in keys {
        let val = registry.by_css_var.get(key).unwrap();
        // convert e.g. "color-primary" to ["color", "primary"]
        let parts: Vec<&str> = key.split('-').collect();
        if parts.is_empty() {
            continue;
        }

        // Determine W3C DTCG type based on first path segment
        let dtcg_type = match parts[0] {
            "color" => "color",
            "spacing" => "dimension",
            "radius" => "dimension",
            "shadow" => "shadow",
            "font" => "fontFamily",
            _ => "other",
        };

        let mut current = &mut root;
        for i in 0..parts.len() {
            let part = parts[i];
            if i == parts.len() - 1 {
                let mut leaf = Map::new();
                leaf.insert("$value".to_string(), Value::String(val.clone()));
                leaf.insert("$type".to_string(), Value::String(dtcg_type.to_string()));
                current.insert(part.to_string(), Value::Object(leaf));
            } else {
                let entry = current
                    .entry(part.to_string())
                    .or_insert_with(|| Value::Object(Map::new()));
                if let Value::Object(next_map) = entry {
                    current = next_map;
                } else {
                    break;
                }
            }
        }
    }
    Value::Object(root)
}

/// Import a W3C Design Tokens Community Group (DTCG) JSON value into a `TokenRegistry`.
pub fn import_from_dtcg(dtcg: &Value) -> TokenRegistry {
    let mut registry = TokenRegistry::default();
    walk_dtcg(dtcg, &[], &mut registry);
    registry
}

fn walk_dtcg(val: &Value, path: &[&str], registry: &mut TokenRegistry) {
    if let Value::Object(obj) = val {
        // If this is a token leaf (has a "$value")
        if let Some(Value::String(value_str)) = obj.get("$value") {
            let key = path.join("-");
            registry.by_css_var.insert(key, value_str.clone());
        } else {
            // intermediate node
            for (key, subval) in obj {
                if key.starts_with('$') {
                    continue;
                }
                let mut new_path = path.to_vec();
                new_path.push(key.as_str());
                walk_dtcg(subval, &new_path, registry);
            }
        }
    }
}

/// Emit TypeScript union type containing all design token keys.
pub fn emit_tokens_union_ts(registry: &TokenRegistry) -> String {
    let mut keys: Vec<&String> = registry.by_css_var.keys().collect();
    keys.sort();

    let mut out = String::from("// Generated by Vox compiler. Do not edit.\n\n");
    out.push_str("export type VoxTokenUnion =\n");
    if keys.is_empty() {
        out.push_str("  never;\n");
    } else {
        for key in keys {
            out.push_str(&format!("  | \"{key}\"\n"));
        }
        out.push_str("  ;\n");
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_dtcg() -> Value {
        serde_json::json!({
            "color": {
                "primary": {
                    "$value": "#3a86ff",
                    "$type": "color"
                },
                "background": {
                    "$value": "#ffffff",
                    "$type": "color"
                }
            },
            "spacing": {
                "md": {
                    "$value": "16px",
                    "$type": "dimension"
                }
            }
        })
    }

    #[test]
    fn test_import_dtcg() {
        let registry = import_from_dtcg(&sample_dtcg());
        assert_eq!(registry.lookup("color-primary"), Some("#3a86ff"));
        assert_eq!(registry.lookup("color-background"), Some("#ffffff"));
        assert_eq!(registry.lookup("spacing-md"), Some("16px"));
    }

    #[test]
    fn test_export_dtcg() {
        let mut registry = TokenRegistry::default();
        registry.by_css_var.insert("color-primary".to_string(), "#3a86ff".to_string());
        registry.by_css_var.insert("color-background".to_string(), "#ffffff".to_string());
        registry.by_css_var.insert("spacing-md".to_string(), "16px".to_string());

        let exported = export_to_dtcg(&registry);
        assert_eq!(exported, sample_dtcg());
    }

    #[test]
    fn test_emit_tokens_union() {
        let mut registry = TokenRegistry::default();
        registry.by_css_var.insert("color-primary".to_string(), "#3a86ff".to_string());
        registry.by_css_var.insert("spacing-md".to_string(), "16px".to_string());

        let ts = emit_tokens_union_ts(&registry);
        assert!(ts.contains("export type VoxTokenUnion ="), "{}", ts);
        assert!(ts.contains("| \"color-primary\""), "{}", ts);
        assert!(ts.contains("| \"spacing-md\""), "{}", ts);
    }
}
