[package]
name = "voxup"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = false
description = "The Vox toolchain multiplexer and hermetic installer"

[dependencies]
clap = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
url = { workspace = true }
workspace-hack = { workspace = true }
