// This file was autogenerated by some hot garbage in the `uniffi-bindgen-react-native` crate.
// Trust me, you don't want to mess with it!
/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
import nativeModule from "./vox_runtime_rn-ffi";
import { type UniffiRustFutureContinuationCallback, type UniffiForeignFutureDroppedCallback, type UniffiForeignFutureDroppedCallbackStruct,
} from "./vox_runtime_rn-ffi";
import { type FfiConverter, type UniffiByteArray, type UniffiGcObject, type UniffiHandle, type UniffiObjectFactory, AbstractFfiConverterByteArray, FfiConverterBool, FfiConverterInt32, FfiConverterObject, FfiConverterUInt8, RustBuffer, UniffiAbstractObject, UniffiEnum, UniffiError, UniffiInternalError, UniffiRustCaller, destructorGuardSymbol, pointerLiteralSymbol, uniffiCreateFfiConverterString, uniffiCreateRecord, uniffiTypeNameSymbol, variantOrdinalSymbol,
} from "@ubjs/core";
const uniffiCaller = new UniffiRustCaller(() => ({ code: 0 }));

const uniffiIsDebug =
  // @ts-ignore -- The process global might not be defined
  typeof process !== "object" ||
  // @ts-ignore -- The process global might not be defined
  process?.env?.NODE_ENV !== "production" ||
  false;

// Public interface members begin here.

/**
 * Build a desktop-profile config with the platform's default data + model
 * directories. Equivalent to [`vox_runtime::VoxConfig::desktop`] but
 * crosses the uniffi boundary so the JS side can request a sensible
 * default without hardcoding host-specific paths.
 */
export function defaultDesktopConfig(): VoxConfig {
    return ((__rb: Uint8Array) => {
        try {
            return FfiConverterTypeVoxConfig.lift(__rb);
        } finally {
            nativeModule().rustbuffer_free(__rb);
        }
    })(uniffiCaller.rustCall(
            /*caller:*/ (callStatus) => {
                return nativeModule().ubrn_uniffi_vox_runtime_rn_fn_func_default_desktop_config(
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
    ));
    }

/**
 * Build a mobile-profile config rooted at `data_dir`. Counterpart of
 * [`vox_runtime::VoxConfig::mobile`].
 */
export function defaultMobileConfig(dataDir: string): VoxConfig {
    return ((__rb: Uint8Array) => {
        try {
            return FfiConverterTypeVoxConfig.lift(__rb);
        } finally {
            nativeModule().rustbuffer_free(__rb);
        }
    })(uniffiCaller.rustCall(
            /*caller:*/ (callStatus) => {
                return nativeModule().ubrn_uniffi_vox_runtime_rn_fn_func_default_mobile_config(
        FfiConverterString.lower(dataDir, nativeModule().rustbuffer_alloc),
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
    ));
    }

// Hermes (React Native ≥ 0.74) ships TextEncoder and encodeInto, but not
// TextDecoder. For single-string decode (bytesToString), we polyfill via the
// C++ string_from_buffer helper using a duck-typed object matching the
// standard TextDecoder.decode signature. Once Hermes ships a real
// TextDecoder, the `typeof` check will pick it up automatically.
//
// For array-of-strings decode (readStringFromBuffer), we keep a dedicated C++
// helper: the polyfill path (new Uint8Array view + decode) measured ~40%
// slower on getStringArray benchmarks than a direct (buf, offset, length)
// call, due to the per-read view allocation and extra property lookups in
// string_from_buffer.
const stringConverter = (() => {
    const encoder = new TextEncoder();
    const decoder: { decode(input: UniffiByteArray): string } =
        typeof TextDecoder !== "undefined"
            ? new TextDecoder()
            : {
                  decode: (bytes: UniffiByteArray) =>
                      nativeModule().ubrn_uniffi_internal_fn_func_ffi__string_from_buffer(
                          bytes,
                          undefined as any,
                      ) as string,
              };
    return {
        // Single-string lower() uses the C++ helper — TextEncoder.encode
        // measured ~43% slower on takeString benchmarks.
        stringToBytes: (s: string) =>
            nativeModule().ubrn_uniffi_internal_fn_func_ffi__string_to_buffer(s, undefined as any),
        bytesToString: (ab: UniffiByteArray) => decoder.decode(ab),
        // Direct C++ call — bypasses uniffiCaller.rustCall() overhead.
        // Matters for N-element arrays.
        stringByteLength: (s: string) =>
            nativeModule().ubrn_uniffi_internal_fn_func_ffi__string_to_byte_length(s, undefined as any) as number,
        // Encode directly into the RustBuffer backing store via
        // TextEncoder.encodeInto — zero intermediate allocation. Replaces
        // the old C++ write_string_into_buffer helper.
        writeStringIntoBuffer: (s: string, buf: any, offset: number): number => {
            const view = new Uint8Array(
                buf.arrayBuffer,
                offset,
                buf.arrayBuffer.byteLength - offset,
            );
            return encoder.encodeInto(s, view).written;
        },
        // Dedicated C++ helper — avoids per-read Uint8Array allocation and
        // the double property-lookup in string_from_buffer.
        readStringFromBuffer: (buf: any, offset: number, length: number): string =>
            nativeModule().ubrn_uniffi_internal_fn_func_ffi__read_string_from_buffer(buf, offset, length) as string,
    };
})();
const FfiConverterString = uniffiCreateFfiConverterString(stringConverter);

/**
 * Runtime execution profile (uniffi-exposed mirror of
 * [`vox_runtime::RuntimeProfile`]).
 */
export enum RuntimeProfile {
    /**
     * Desktop (Tauri 2): multi-threaded scheduler, periodic journal flush,
     * eager model retention.
     */
    Desktop,
    /**
     * Mobile (React Native + Expo + uniffi): single-threaded scheduler,
     * journal-on-lifecycle, lazy model retention with memory-pressure
     * unload.
     */
    Mobile
}

const FfiConverterTypeRuntimeProfile = (() => {
    const ordinalConverter = FfiConverterInt32;
    type TypeName = RuntimeProfile;
    class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
        read(from: RustBuffer): TypeName {
            switch (ordinalConverter.read(from)) {
                case 1: return RuntimeProfile.Desktop;
                case 2: return RuntimeProfile.Mobile;
                default: throw new UniffiInternalError.UnexpectedEnumCase();
            }
        }
        write(value: TypeName, into: RustBuffer): void {
            switch (value) {
                case RuntimeProfile.Desktop: return ordinalConverter.write(1, into);
                case RuntimeProfile.Mobile: return ordinalConverter.write(2, into);
            }
        }
        allocationSize(value: TypeName): number {
            return ordinalConverter.allocationSize(0);
        }
    }
    return new FFIConverter();
})();

/**
 * Runtime configuration carried at construction (uniffi-exposed mirror of
 * [`vox_runtime::VoxConfig`]). Fields are explicit `String` for the paths
 * because uniffi doesn't expose `PathBuf` across the FFI boundary; the
 * strings are interpreted as paths inside the Rust side.
 */
export type VoxConfig = {
    /**
     * Where workflow journal + durable state live.
     */
    dataDir: string,
    /**
     * Where on-device ML model files live.
     */
    modelDir: string,
    /**
     * Log level for the `tracing` subscriber (`error` / `warn` / `info` /
     * `debug` / `trace`; unrecognized values fall back to `info`).
     */
    logLevel: string,
    /**
     * Profile dispatching every per-target policy.
     */
    profile: RuntimeProfile
}

/**
 * Generated factory for {@link VoxConfig} record objects.
 */
export const VoxConfig = (() => {
    const defaults = () => ({
    });
    const create = (() => {
        return uniffiCreateRecord<VoxConfig, ReturnType<typeof defaults>>(defaults);
    })();
    return Object.freeze({
        create,
        new: create,
        defaults: () => Object.freeze(defaults()) as Partial<VoxConfig>,
    });
})();

const FfiConverterTypeVoxConfig = (() => {
    type TypeName = VoxConfig;
    class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
        read(from: RustBuffer): TypeName {
            return {
                dataDir: FfiConverterString.read(from), 
                modelDir: FfiConverterString.read(from), 
                logLevel: FfiConverterString.read(from), 
                profile: FfiConverterTypeRuntimeProfile.read(from)
            };
        }
        write(value: TypeName, into: RustBuffer): void {
            FfiConverterString.write(value.dataDir, into);
            FfiConverterString.write(value.modelDir, into);
            FfiConverterString.write(value.logLevel, into);
            FfiConverterTypeRuntimeProfile.write(value.profile, into);
        }
        allocationSize(value: TypeName): number {
            return FfiConverterString.allocationSize(value.dataDir) +
             FfiConverterString.allocationSize(value.modelDir) +
             FfiConverterString.allocationSize(value.logLevel) +
             FfiConverterTypeRuntimeProfile.allocationSize(value.profile);
            
        }
    };
    return new FFIConverter();
})();


// Flat error type: VoxRnError
export enum VoxRnError_Tags {
    NotInitialized = "NotInitialized",
    Internal = "Internal"
}
/**
 * Errors raised across the uniffi boundary.
 */
export const VoxRnError = (() => {
    /**
     * The runtime was used before [`VoxRuntimeHandle`] was constructed.
     */
    class NotInitialized extends UniffiError {
        /**
         * @private
         * This field is private and should not be used.
         */
        readonly [uniffiTypeNameSymbol]: string = "VoxRnError";
        /**
         * @private
         * This field is private and should not be used.
         */
        readonly [variantOrdinalSymbol] = 1;

        readonly tag = VoxRnError_Tags.NotInitialized;

        constructor(message: string) {
            super("VoxRnError", "NotInitialized", message);
        }

        static instanceOf(e: any): e is NotInitialized {
            return (
                instanceOf(e) && (e as any)[variantOrdinalSymbol] === 1
            );
        }
    }
    /**
     * Caller-provided context for unexpected failures.
     */
    class Internal extends UniffiError {
        /**
         * @private
         * This field is private and should not be used.
         */
        readonly [uniffiTypeNameSymbol]: string = "VoxRnError";
        /**
         * @private
         * This field is private and should not be used.
         */
        readonly [variantOrdinalSymbol] = 2;

        readonly tag = VoxRnError_Tags.Internal;

        constructor(message: string) {
            super("VoxRnError", "Internal", message);
        }

        static instanceOf(e: any): e is Internal {
            return (
                instanceOf(e) && (e as any)[variantOrdinalSymbol] === 2
            );
        }
    }

    // Utility function which does not rely on instanceof.
    function instanceOf(e: any): e is VoxRnError {
        return (e as any)[uniffiTypeNameSymbol] === "VoxRnError";
    }
    return {
        NotInitialized,
        Internal,
        instanceOf,
    };
})();

// Union type for VoxRnError error type.
/**
 * Errors raised across the uniffi boundary.
 */
export type VoxRnError = InstanceType<
    typeof VoxRnError['NotInitialized' | 'Internal']
>;

const FfiConverterTypeVoxRnError = (() => {
    const intConverter = FfiConverterInt32;
    type TypeName = VoxRnError;
    class FfiConverter extends AbstractFfiConverterByteArray<TypeName> {
        read(from: RustBuffer): TypeName {
            switch (intConverter.read(from)) {
                case 1: return new VoxRnError.NotInitialized(
                    FfiConverterString.read(from)
                );
            
                case 2: return new VoxRnError.Internal(
                    FfiConverterString.read(from)
                );
            
                default: throw new UniffiInternalError.UnexpectedEnumCase();
            }
        }
        write(value: TypeName, into: RustBuffer): void {
            const obj = value as any;
            const index = obj[variantOrdinalSymbol] as number;
            intConverter.write(index, into);
        }
        allocationSize(value: TypeName): number {
            return intConverter.allocationSize(0);
        }
    }
    return new FfiConverter();
})();

/**
 * Live runtime instance, returned by [`VoxRuntimeHandle::new`].
 *
 * Holds the parsed [`InnerConfig`] internally; mirror getters expose the
 * fields back across uniffi without leaking `PathBuf` (which uniffi can't
 * transit).
 */
export interface VoxRuntimeHandleLike {
    
/**
 * The runtime's data directory as a UTF-8 string.
 */
    dataDir(): string;
/**
 * Emit a tracing event from the JS side. The `level` string is
 * interpreted the same way [`InnerConfig::log_level_parsed`] handles
 * it — unknown values are silently coerced to `info` so this method
 * never fails for a bad level argument.
 */
    log(level: string, message: string): void;
/**
 * The runtime's model directory as a UTF-8 string.
 */
    modelDir(): string;
/**
 * The runtime's [`RuntimeProfile`].
 */
    profile(): RuntimeProfile;
/**
 * Whether this profile requires the JS shell to wire suspend / resume
 * lifecycle hooks (true on Mobile, false on Desktop).
 */
    requiresSuspendHooks(): boolean;
}
/**
 * @deprecated Use `VoxRuntimeHandleLike` instead.
 */
export type VoxRuntimeHandleInterface = VoxRuntimeHandleLike;


/**
 * Live runtime instance, returned by [`VoxRuntimeHandle::new`].
 *
 * Holds the parsed [`InnerConfig`] internally; mirror getters expose the
 * fields back across uniffi without leaking `PathBuf` (which uniffi can't
 * transit).
 */
export class VoxRuntimeHandle extends UniffiAbstractObject implements VoxRuntimeHandleLike {

    readonly [uniffiTypeNameSymbol] = "VoxRuntimeHandle";
    readonly [destructorGuardSymbol]: UniffiGcObject;
    readonly [pointerLiteralSymbol]: UniffiHandle;
/**
 * Construct a new runtime handle from the given configuration.
 *
 * Validates the config inline (parses log level via
 * [`InnerConfig::log_level_parsed`]) so callers can't construct a
 * handle with a wildly invalid profile + log-level combo.
 */
    constructor(config: VoxConfig) {
        super();
        const pointer =
            uniffiCaller.rustCall(
            /*caller:*/ (callStatus) => {
                return nativeModule().ubrn_uniffi_vox_runtime_rn_fn_constructor_voxruntimehandle_new(
        FfiConverterTypeVoxConfig.lower(config, nativeModule().rustbuffer_alloc),
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
    );
        this[pointerLiteralSymbol] = pointer;
        this[destructorGuardSymbol] = uniffiTypeVoxRuntimeHandleObjectFactory.bless(pointer);
    }

    

    
/**
 * The runtime's data directory as a UTF-8 string.
 */
    dataDir(): string {
    return ((__rb: Uint8Array) => {
        try {
            return FfiConverterString.lift(__rb);
        } finally {
            nativeModule().rustbuffer_free(__rb);
        }
    })(uniffiCaller.rustCall(
            /*caller:*/ (callStatus) => {
                return nativeModule().ubrn_uniffi_vox_runtime_rn_fn_method_voxruntimehandle_data_dir(
                uniffiTypeVoxRuntimeHandleObjectFactory.clonePointer(this),
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
    ));
    }
    
/**
 * Emit a tracing event from the JS side. The `level` string is
 * interpreted the same way [`InnerConfig::log_level_parsed`] handles
 * it — unknown values are silently coerced to `info` so this method
 * never fails for a bad level argument.
 */
    log(level: string, message: string): void {uniffiCaller.rustCall(
            /*caller:*/ (callStatus) => { nativeModule().ubrn_uniffi_vox_runtime_rn_fn_method_voxruntimehandle_log(
                uniffiTypeVoxRuntimeHandleObjectFactory.clonePointer(this),
        FfiConverterString.lower(level, nativeModule().rustbuffer_alloc),
        FfiConverterString.lower(message, nativeModule().rustbuffer_alloc),
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
    );
    }
    
/**
 * The runtime's model directory as a UTF-8 string.
 */
    modelDir(): string {
    return ((__rb: Uint8Array) => {
        try {
            return FfiConverterString.lift(__rb);
        } finally {
            nativeModule().rustbuffer_free(__rb);
        }
    })(uniffiCaller.rustCall(
            /*caller:*/ (callStatus) => {
                return nativeModule().ubrn_uniffi_vox_runtime_rn_fn_method_voxruntimehandle_model_dir(
                uniffiTypeVoxRuntimeHandleObjectFactory.clonePointer(this),
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
    ));
    }
    
/**
 * The runtime's [`RuntimeProfile`].
 */
    profile(): RuntimeProfile {
    return ((__rb: Uint8Array) => {
        try {
            return FfiConverterTypeRuntimeProfile.lift(__rb);
        } finally {
            nativeModule().rustbuffer_free(__rb);
        }
    })(uniffiCaller.rustCall(
            /*caller:*/ (callStatus) => {
                return nativeModule().ubrn_uniffi_vox_runtime_rn_fn_method_voxruntimehandle_profile(
                uniffiTypeVoxRuntimeHandleObjectFactory.clonePointer(this),
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
    ));
    }
    
/**
 * Whether this profile requires the JS shell to wire suspend / resume
 * lifecycle hooks (true on Mobile, false on Desktop).
 */
    requiresSuspendHooks(): boolean {
    return FfiConverterBool.lift(uniffiCaller.rustCall(
            /*caller:*/ (callStatus) => {
                return nativeModule().ubrn_uniffi_vox_runtime_rn_fn_method_voxruntimehandle_requires_suspend_hooks(
                uniffiTypeVoxRuntimeHandleObjectFactory.clonePointer(this),
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
    ));
    }
    

    uniffiDestroy(): void {
        const ptr = (this as any)[destructorGuardSymbol];
        if (ptr !== undefined) {
            const pointer = uniffiTypeVoxRuntimeHandleObjectFactory.pointer(this);
            uniffiTypeVoxRuntimeHandleObjectFactory.freePointer(pointer);
            uniffiTypeVoxRuntimeHandleObjectFactory.unbless(ptr);
            delete (this as any)[destructorGuardSymbol];
        }
    }

    static instanceOf(obj_: any): obj_ is VoxRuntimeHandle {
        return uniffiTypeVoxRuntimeHandleObjectFactory.isConcreteType(obj_);
    }

    
}

const uniffiTypeVoxRuntimeHandleObjectFactory: UniffiObjectFactory<VoxRuntimeHandleLike> = (() => {
    
    return {
    create(pointer: UniffiHandle): VoxRuntimeHandleLike {
        const instance = Object.create(VoxRuntimeHandle.prototype);
        instance[pointerLiteralSymbol] = pointer;
        instance[destructorGuardSymbol] = this.bless(pointer);
        instance[uniffiTypeNameSymbol] = "VoxRuntimeHandle";
        return instance;
    },

    
    bless(p: UniffiHandle): UniffiGcObject {
        return uniffiCaller.rustCall(
            /*caller:*/ (status) =>
                nativeModule().ubrn_uniffi_internal_fn_method_voxruntimehandle_ffi__bless_pointer(p, status),
            /*liftString:*/ FfiConverterString.lift
        );
    },

    unbless(ptr_: UniffiGcObject) {
        ptr_.markDestroyed();
    },

    pointer(obj_: VoxRuntimeHandleLike): UniffiHandle {
        if ((obj_ as any)[destructorGuardSymbol] === undefined) {
            throw new UniffiInternalError.UnexpectedNullPointer();
        }
        return (obj_ as any)[pointerLiteralSymbol];
    },

    clonePointer(obj_: VoxRuntimeHandleLike): UniffiHandle {
        const pointer = this.pointer(obj_);
        return uniffiCaller.rustCall(
            /*caller:*/ (callStatus) => nativeModule().ubrn_uniffi_vox_runtime_rn_fn_clone_voxruntimehandle(pointer, callStatus),
            /*liftString:*/ FfiConverterString.lift
        );
    },

    freePointer(pointer: UniffiHandle): void {
        uniffiCaller.rustCall(
            /*caller:*/ (callStatus) => nativeModule().ubrn_uniffi_vox_runtime_rn_fn_free_voxruntimehandle(pointer, callStatus),
            /*liftString:*/ FfiConverterString.lift
        );
    },

    isConcreteType(obj_: any): obj_ is VoxRuntimeHandleLike {
        return obj_[destructorGuardSymbol] && obj_[uniffiTypeNameSymbol] === "VoxRuntimeHandle";
    },
}})();
const FfiConverterTypeVoxRuntimeHandle = new FfiConverterObject(uniffiTypeVoxRuntimeHandleObjectFactory);


/**
 * This should be called before anything else.
 *
 * It is likely that this is being done for you by the library's `index.ts`.
 *
 * It checks versions of uniffi between when the Rust scaffolding was generated
 * and when the bindings were generated.
 *
 * It also initializes the machinery to enable Rust to talk back to Javascript.
 */
function uniffiEnsureInitialized() {
    // Get the bindings contract version from our ComponentInterface
    const bindingsContractVersion = 30;
    // Get the scaffolding contract version by calling the into the dylib
    const scaffoldingContractVersion = nativeModule().ubrn_ffi_vox_runtime_rn_uniffi_contract_version();
    if (bindingsContractVersion !== scaffoldingContractVersion) {
        throw new UniffiInternalError.ContractVersionMismatch(scaffoldingContractVersion, bindingsContractVersion);
    }
    if (nativeModule().ubrn_uniffi_vox_runtime_rn_checksum_func_default_desktop_config() !== 2007) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_vox_runtime_rn_checksum_func_default_desktop_config");
    }
    if (nativeModule().ubrn_uniffi_vox_runtime_rn_checksum_func_default_mobile_config() !== 34032) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_vox_runtime_rn_checksum_func_default_mobile_config");
    }
    if (nativeModule().ubrn_uniffi_vox_runtime_rn_checksum_constructor_voxruntimehandle_new() !== 48480) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_vox_runtime_rn_checksum_constructor_voxruntimehandle_new");
    }
    if (nativeModule().ubrn_uniffi_vox_runtime_rn_checksum_method_voxruntimehandle_data_dir() !== 43129) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_vox_runtime_rn_checksum_method_voxruntimehandle_data_dir");
    }
    if (nativeModule().ubrn_uniffi_vox_runtime_rn_checksum_method_voxruntimehandle_log() !== 15601) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_vox_runtime_rn_checksum_method_voxruntimehandle_log");
    }
    if (nativeModule().ubrn_uniffi_vox_runtime_rn_checksum_method_voxruntimehandle_model_dir() !== 2882) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_vox_runtime_rn_checksum_method_voxruntimehandle_model_dir");
    }
    if (nativeModule().ubrn_uniffi_vox_runtime_rn_checksum_method_voxruntimehandle_profile() !== 49962) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_vox_runtime_rn_checksum_method_voxruntimehandle_profile");
    }
    if (nativeModule().ubrn_uniffi_vox_runtime_rn_checksum_method_voxruntimehandle_requires_suspend_hooks() !== 43115) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_vox_runtime_rn_checksum_method_voxruntimehandle_requires_suspend_hooks");
    }

    }

export default Object.freeze({
  initialize: uniffiEnsureInitialized,
  converters: {
    FfiConverterTypeRuntimeProfile,
    FfiConverterTypeVoxConfig,
    FfiConverterTypeVoxRnError,
    FfiConverterTypeVoxRuntimeHandle,
  }
});